openpnp/openpnp

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/importer/EagleBoardImporter.java

Fixed bug in JobPanel where it would crash with NULL error if you "cancel" out of the board importer dialog.  Note this was not trapped as an exception by Java so I have to explicitly test for "null"
Hopefully fixed a bug where after importing a board that has parts that are not already in my Parts and Packages they are not created.

Fixed bug in JobPanel and EagleBoardImporter

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java

When the strip is located at 180 degrees and the X coordinates of the two holes are the same (for example if they are put manually), the code computes the angle as atan(0,0), because the two if conditions are false. I have changed the second condition to <= to compute the correct angle based on the Y coordinates.

solves issue #178 (error picking a strip located at 180 degrees

---

src/main/java/org/openpnp/machine/reference/driver/LinuxCNC.java

1) Updated to use protocol version 1.1
2) mdi commands issued will not respond until the movement is complete. Tested in LinuxCNC SIM only but seems to work fine.
3) Enabled verbose, ACK and NAK messages in the reply can be used to determine if the last command completed with or without errors.

LinuxCNC driver update

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1873 - “ "static final" arrays should be "private" ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1873
Please let me know if you have any questions.
Ayman Abdelghany.

"static final" arrays should be "private"

---

src/main/java/org/openpnp/gui/support/HeadCellValue.java
src/main/java/org/openpnp/model/Location.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1206 - “ equals(Object obj) and hashCode() should be overridden in pairs ”. You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1206
Please let me know if you have any questions.
Ayman Abdelghany.

equals(Object obj)" and "hashCode()" should be overridden in pairs

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java

This pull request is focused on resolving occurrences of Sonar rule squid:S2184 - “ Math operands should be cast before assignment”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2184
Please let me know if you have any questions.
Ayman Abdelghany.

Math operands should be cast before assignment

---

src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/vision/LensCalibration.java

In ReferenceCamera#transformImage, adjust the size of the image before rotating so that the full rotated image will fit in the new frame. Fixes #228

Don't crop rotated frames in ReferenceCamera

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/spi/PartAlignment.java

Altered partAlignment interface to allow the alignmentProcessor to signal if it has done all the necessary component rotations (such as a remote centering stage), it now gets passed all the information it needs to calculate the final rotation

Altered partAlignment interface

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceTrayFeederConfigurationWizard.java

This feature adds a "Reset" button to the Tray Feed count as requested by issue 276: [https://github.com/openpnp/openpnp/issues/276](url) 
The biggest change is from lines 121 - 130. This adds the buttons functionality and sets its design to be a simple button. Once the user selects the "Reset" button, it will then set the Feed Count to be 0 and then update the value.
Other lines had properties added to them to make their Grid width 2. This allows for the button to maintain a small size, while the other elements in the column are able to resize with the rest of the window.

Feature - Reset Feed Count

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceTrayFeeder.java

This fix was in response to issue #321 
The major change is instead of the feeder increment on line 95, the code now uses the setFeedCount method to increase the number. The setFeedCount method takes in the new number given and then updates the screen accordingly.

Bug Fix - Tray Feeders feed count was not updating

---

src/main/java/org/openpnp/gui/tablemodel/PlacementsTableModel.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/model/Placement.java

This feature allows the user to do a Fiducial Check of an individual board prior to placing it. This is in regards to Issue #319.
In the PlacementTableModel.java there is an extra column added for the Check Fids which has a checkbox element within it.
In the Placement.java there is the Check Fids attribute. This will determine if the placement has requested a Check Fid for the board.
Lastly the ReferencePnpJobProcessor.java adds a method that will override the fiducial locations of the board being called. This method is then called in the doPlace() method just before a boardLocationFiducialOverrides check.

Feature - Check Fiducials Before Individual Placement

---

src/main/java/org/openpnp/machine/reference/signaler/ActuatorSignaler.java

This is what i acutally ment since if they are present the signaler will go off in a machineError even if that was not configured in the XML. I will also edit the Wiki to show the different options

Removing default values in Actuator Signaler

---

src/main/java/org/openpnp/gui/FeedersPanel.java

Changed "Configuration" border into a tab like other panels.
Before: 
After:

Feeder panel layout in line with other panels

---

src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java
src/main/java/org/openpnp/machine/reference/camera/LtiCivilCamera.java
src/main/java/org/openpnp/machine/reference/camera/OnvifIPCamera.java
src/main/java/org/openpnp/machine/reference/camera/OpenCvCamera.java
src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java
src/main/java/org/openpnp/machine/reference/camera/VfwCamera.java
src/main/java/org/openpnp/machine/reference/camera/Webcams.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceAutoFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceDragFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceTrayFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceTubeFeeder.java
src/main/java/org/openpnp/spi/base/AbstractFeeder.java

Changed for available camera objects but with some remarks:
- ImageCamera, IPCamera, OpenCVCamera, SimulatedUpCamera and Webcams
work fine
- Webcams give however a warning in the log file
log4j:WARN No appenders could be found for logger
(com.github.sarxos.webcam.Webcam).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
more info.
- Lticivil cam give, when trying to add on the cameras panel:
Caused by: com.lti.civil.CaptureException:
java.lang.UnsatisfiedLinkError: no civil in java.library.path
- Vfw cam gives, when selecting in the machine setup tree and also after
returning to Cameras panel and selecting it:
The vonnieda.org Java video capture kit is unable to load it's native
layer.
Please make sure you …

Configuration tabs within "Machine Setup" panel now with titles (partly #172)

---

src/main/java/org/openpnp/gui/MachineSetupPanel.java
src/main/java/org/openpnp/machine/reference/camera/LtiCivilCamera.java

Apart from feeders, cameras and Gcode driver all objects wizards return
no title. For those cases "Untitled"  is replaced by "Configuration"
which is much neater to see.
LtiCivilCamera override code has been removed so base class supplies the
getPropertySheets method with titles for the two panels.
These two should be the finishing touch on issue #172

Untitled machine setup tabs filled

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

Gcode driver used to:
1) add headmovable offset to target location on every entry --> giving twice or more the physical move
2) stop processing when there is no action thus preventing subdrivers to take control --> unnecessary tweaks in machine.xml 
This PR:
1) keeps original target location aside for every next iterative call --> offsets are used correctly
2) just skips part of the code to always reach the point where subdrivers take control --> no tweaks necessary in machine.xml for this bug HOWEVER same tweaks still necessary for other bug (see text in #376)

Improve Gcode driver (see #376)

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

getLocation() was only reporting axes found on the main Gcodedriver.
Axes defined on subdrivers where thus lost and not in DRO and also not available for next relative move.
A tweak was to define the missing axes on the main driver as well but this has other implications and is not ideal.
First solution thought of was to have GcodeDriver.getAxis() look on all subdrivers but that gave problems in GcodeDriver.moveTo(). So this solution is based getLocation() looking on subdrivers.
@vonnieda I had to use a typecast (ReferenceDriver to GcodeDriver). Maybe you know a better way.
In the meantime I tested this solution on my machine (Z2 on maindriver, XYZ1C on subdriver) and found no problems whatsoever.
This concludes the bugs found in #376 so that issue maybe closed

DRO update works on Gcodedriver, even when axis info is on subdrivers

---

src/main/java/org/openpnp/gui/MainFrame.java

**MainFrame.java modified**
- added `Windows` menu with one item to control window layout style
- added method `splitWindows()`, called at the end of the class constructor
- added preferences property `PREF_WINDOW_STYLE_MULTIPLE` to store the current window layout style + default value set to single window mode
- elevated `panelCameraAndInstructions `& `panelMachine `to become class member variables
[
](url)
**Operation mode**
- Main-Window / Windows / Multiple Window Style ... enable OR disable
- With the window-layout/managment in discussion the current implementation requires to restart the application to get the different mode active.
[
](url)
**Further changes if it fits the needs.**
- Apply the setting immediately, if "Multiple Window Style" is changed.
[
](url)
**Issue**
- If one …

add 2 more windows

---

src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/importer/DipTraceImporter.java

Hi, first pull request ever. Please scrutinize as needed. Wiki on the topic of first pull request  was awesome. 
What it does
This allows native DipTrace PCB pick and place exports to be imported without change. 
Why not use the default 'NamedCSVImporter'?
This could be done (see below). But the error messages and log output were hard to decipher and pretty much required the dev environment to be installed to make heads or tails of why the CSV was being rejected. In order to use the default importer, the CSV exported by DipTrace needs the line 0 header item changed from 'Name' to 'Footprint'. There is no way to change this header name in the DipTrace tool.  It must be done outside of Diptrace PCB.
Why not add the option to use 'name' as a footprint column in the 'NamedCSVImporter'?
This …

Import support for DipTrace PCB

---

src/main/java/org/openpnp/Main.java
src/main/java/org/openpnp/logging/SystemLogger.java

Hey there,
i managed to redirect the output, but there are some things to know about this:
1. No overwrite of the `System.out.write(int b)` primitive char printing as this does not make sense in the LogTab.
2. I had to change the addWriter to writer because the consoleWriter which is default attached by tinylog will create a circular dependency: System.out=> SystemLogger => Logger (Console Writer) => System.out
3. Initialization in Main class as the first logging is done there and i do not want config changes in between setup logging and setup of Log Panel.
Class was named SystemLogger because tinylog uses reflection and the class name will be used for tagging the LogEntry. I found no way to overwrite this in a simple way.
Unfortunately there is no generic log function where one could …

Adding a SystemLogger class for redirecting stdout and stderr to tinylog, related to #288

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/support/Helpers.java
src/main/java/org/openpnp/gui/support/Icons.java
src/main/resources/icons/position-camera-move-next.svg

This was sketched out here with a picture: https://groups.google.com/forum/#!topic/openpnp/SpG09TKEVWg. The goal is to augment the "move camera to board" and "move camera to part" buttons with similar buttons with an arrow that performs the same action BUT then it advances the board or part table to the next line. The buttons also keep focus, allowing you to quickly move the camera through the PCB origins or part origins using the space bar so that you can verify the board origins in a panel, for example, are correct. And in part mode, this allows you to quickly zip from part to part and using the rotating gratical you can quickly see if part rotations are as expected.
Without this feature, you had to bounce between "move camera" button and then go click the next line in the table, and …

Center camera and move to next part

---

src/main/java/org/openpnp/vision/pipeline/stages/ScriptRun.java

It is useful to have arguments passed to the ScriptRun OpenCV pipeline stage. This PR adds a string parameter `args` to the stage, which can then be parsed from inside the script.
Example parsing, from inside a ScriptRun stage with `args=size:[45,60],tol:5` 
```
eval("var args={" + args + "}");
for (var i in args)
print(i,args[i]);
```
LOG window shows:
```
2017-03-29 01:33:01 SystemLogger INFO: size 45,60
2017-03-29 01:33:01 SystemLogger INFO: tol 5
```

Add arguments to ScriptRun OpenCV pipeline stage

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

Added a var to count the number of parts placed, and then in addition to the already computed job time in the log, also print out the number of parts per hour the last placement achieved. Very helpful for machine tuning and comparing various strategies.
Verified no issue  with empty job (eg zero placements).
PS @pfried, the logging stuff is awesome

Added PPH metric to job time log item

---

src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/gui/support/CameraItem.java
src/main/java/org/openpnp/gui/support/HeadMountableItem.java
src/main/java/org/openpnp/gui/support/NozzleItem.java

This is continuation of #504....This is to check if on the right path (not a lot of changes were needed). There was CameraItem and NozzleItem already. Looks like these are used to give a nice output string. I created a headmountableitem and derived cameraitem and nozzleitem from that, and then used the headmountable item in the combo box. Combobox populates as expected (with nozzle and head camera) and DRO reads as expected based on which is selected in the listbox. 
One bug I might have found that is unrelated to these changes: If you have two nozzles, one offset of -10,-10 and another of -5, -5, and you XY park, your absolute park location seems to depend on which nozzle was selected when you parked. That seems not right to me as the docs say park should park the head at its park …

Add Camera to Nav Combobox and then show selected item coords in DRO

---

TEST.md
src/main/java/org/openpnp/vision/pipeline/stages/FilterRects.java
src/main/java/org/openpnp/vision/pipeline/stages/ImageCapture.java
src/main/java/org/openpnp/vision/pipeline/stages/ImageRead.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java

Original image:
`MinAreaRectContours` OpenCV pipeline stage selects rects based on contour area:
The contours above have approximately the same area, which makes it difficult to distinguish within a safe margin, although the have quite different dimensions.
It would be useful to be able to filter objects based on their expected dimensions, and not only on their contour area. The proposed OpenCV pipeline  stage adds this functionality.
With FilterRects and the example image above, specifying `width = 60, height = 50, tolerance = 5` yields the following rect:
while specifying `width = 85, height = 80, tolerance = 5` yields the following rect:

Add FilterRects stage to OpenCV pipeline to filter rects based on width and height

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

I used the non-squareness factor for my PNP machine. But when I moved the head only in Y-direction, I noticed that the X coordinate hasn't changed accordingly.  The original code doesn't change the x-coordinate when there is no x-movement. This is the reason why the non-squareness factor isn't used in this case.
My fix recalculates the X coordinate as soon as there is a change of the Y coordinate.
Every user who is using the non-squareness factor will be effected by the problem. In some rare cases when the machine is only moving in the Y direction, the position will be wrong because of not using the non-squareness factor to correct the X coordinate.
- First test: I used some plotting paper and moved the head only in Y direction. With the help of the …

Fixed an issue with the non-squareness factor

---

src/main/java/org/openpnp/vision/pipeline/stages/DrawImageCenter.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java

New OpenCV pipeline stage `DrawImageCenter`. Draws a configurable mark at the center of the current image.
This is complementary to #537: `Draw a mark at the center of each RotatedRect`, and aims to aid in camera alignment and visual comparisons of detected features. Here is what it does:
The new stage is intended to be used mostly at the end of the pipeline, after image processing has finished. Setting of the center mark is straight forward, by tweaking the `color`, `showImageCenter`, `size` and/or `thickness` properties of the new stage:
In the image above, the bottom camera position needs to be better aligned with the optical center of the camera.
In the image above, a comparison of the optical center with the center of a RoratedRect can help visualize successful alignment.
1. How did …

Created new pipeline stage: DrawImageCenter

---

src/main/java/org/openpnp/vision/pipeline/stages/MaskPolygon.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java

A new OpenCV pileline stage is proposed, named `MaskPolygon`, which offers masking of multiple image areas based on shapes derived from user provided data.
There are three OpenCV pipeline stages that provide a masking operation, namely: `MaskCircle`, `MaskRect` and `MaskHsv`. The two former apply the mask as a geometric shape at the center of the image,
while the latter operates on the whole image based on the color of the features.
The new `MaskPolygon` stage can apply multiple mask shapes anywhere on the image:
The above image was produced by  defining shape coordinates in parameter `shapes`:
```
shapes: 640,400 : 50; 440,532 : 540,532 : 540,632; 700,532 : 800,532 : 800,632 : 700,632
```
Multiple shapes can be used to mask out unwanted features scattered in the image. For example, the …

New OpenCV pipeline stage: MaskPolygon

---

src/main/java/org/openpnp/vision/pipeline/stages/DilateModel.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java

When building an OpenCV pipeline, there are cases where the detected models of parts contain unwanted content, e.g. portions of pins, shadows etc, which may be difficult to remove without affecting other parts of the image. While processing the image content directly may be difficult in such cases, there exists an alternative  path to take: **process the geometry of the model** instead.
A new OpenCV pipeline stage is thus proposed, named `DilateModel`, that performs dilation or contraction on the shape of a model. At present, it operates on Circles and RotatedRect models. The following series of images show an example of a dilate operation.
Original image:
Model masked (makes use of a `MaskModel` stage to isolate the original image content inside the model) :
The result of applying the …

New OpenCV pipeline stage: DilateModel

---

src/main/java/org/openpnp/vision/pipeline/stages/DilateModel.java

Return statement for single RotatedRect in DilateModel was missing.  The stage returned the result unchanged, no matter what the `delate` parameter was.

Added missing return statement

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

To submit a Pull Request for OpenPnP you must use this template or it will be deleted. 
Be sure to review the [[Developers Guide]] and the [Contributing Guidelines](https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md).
Fill out all the details below.
Added an overridden dispense() function to the gcode driver, along with pre-dispense, dispense and post-dispense commands which can take the dispense-time as …

Added paste dispense function to gcode driver with pre/post commands

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceLoosePartFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceLoosePartFeederConfigurationWizard.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java

Add feeder into pipeline in order that (script) stages can access feeder 
It is needed for looseFeeder to access Part and to …

added feeder to pipeline

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceLoosePartFeeder.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java

Added Nozzle variable to pipeline including getter/setter 
This allows accessing the nozzle, from scripts.
This is useful for stages that need to stitch images in order to get a wider field of view,
access to all classes behind nozzle, as part, nozzleTip, and differentiate to bottom or top vision.
If nozzle.getPart() is not null, the pipeline is uplooking because nozzle have part loaded.
Otherwise it is downlooking for the normal usage.
Special pipelines like NozzleTip Calibration pipeline are exceptions to this rules and as special
pipeline that rule don't need to be respected.
moveTo(pipeline.getNozzle().getLocation().add(new Location(LengthUnit.Millimeters,10,10,0,0)):
As note, inside StandaloneEditor, getNozzle return always null.
For Wizards that don't have access to the nozzle …

added nozzle variable to pipeline

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionConfigurationWizard.java

This is to continue discussion of the topic [here](https://groups.google.com/forum/#!topic/openpnp/iFQVZyUgnlA). This has not been tested on my actual machine yet (which I will do this weekend), but it's just a few lines, seems to work in the emulator, and it'd be good to have a look from Jason before then. Since it defaults to disabled, and since the no existing code paths are disturbed if disabled, it seems low risk. 
This adds a "Rotate parts prior to vision?" checkbox to the Bottom Vision config page. If the user opts to do this, then in findsOffsets() the part will be pre-rotated (taking any PCB rotation into account) before vision alignment is performed.
Later in that same function when the PartAlignmentOffset() is instantiated and returned, the flag is set appropriately.

Rotate before Align Option

---

src/main/java/org/openpnp/Main.java
src/main/java/org/openpnp/logging/SystemLogger.java

As promised I took a look at this. Had not much time recently, but today I found some hours.
1. Fix the StackOverflow on shutdown where Logger gets called but is no longer available (exception loop) #288 
2. Fix the double new line issues with the Script Runners #515
The Logger will attach a listener to the VM Shutdown. Otherwise I cannot know if the tinylog logger is still available. This could be replaced by a teardown function, but right now this stuff is split up between the `Main` class and the `MainFrame`.
The code for fixing the newline issue is not the best, but using the `StringBuilder` was my favorite option altough maybe not the best in this case (some bytearray might be better or something similar).
Best, Friedrich

Fix the double line breaks from the script runners

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java

Test prerotate feature with ClosedLoop Stage removed as wanted by  @vonnieda  comments.
It now work globally without the possibility to have it per part or to do better alignment using closed loop
vision process.
Superset of this feature was tested, it should work and just one picture was tested on this branch.
If first stage is ImageRead and second stage is Rotate it works on stored images.
I have leaved this feature for testing purposes.

Pre rotate test

---

src/main/java/org/openpnp/vision/pipeline/ui/PipelinePanel.java
src/main/java/org/openpnp/vision/pipeline/ui/PipelinePropertySheetTable.java

PropertyChangeListener is fired asynchronously, so when it is received the PropertySheetPanel may no longer reflect the items the change was fired for (as is the case when the user is editing a cell of a stage’s properties and clicks to another stage, cancelling the edit while the properties change to reflect the newly selected stage).
Addresses #597.
No change in existing behaviours.
1. How did you test the change? Tested the pipeline editor according to the repro steps described in the issue.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? I believe so.
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages …

CvPipelineEditor issue #597

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/gui/MainFrame.java

I am building a control panel for my system with jog wheels and buttons (using a teensy which will use a virtual HID keyboard interface.)
I added a few more hotkeys based on info from Jason and Cri S from https://groups.google.com/forum/#!topic/openpnp/knlnB8PrGw0 and https://github.com/openpnp/openpnp/issues/509
Hotkeys were added to MainFrame.java and some actions were added to JogControlsPanel.java to directly set a jog increment (as opposed to incrementing up / down). 
The coding style seems to favor separate actions vs a using parameters so I copied that.
IMHO It is always useful to have hotkeys available, and this makes a great low-impact workaround for supporting hardware buttons / joysticks, etc.
Ctrl-Shift-R: Starts a job
Ctrl-Shift-S: Steps through the job
Ctrl-Shift-A: Stops …

Added keyboard hotkeys for some more common functions.

---

src/main/java/org/openpnp/gui/MainFrame.java

Some users reported Ctrl-\<backtick\> does not work in windows.
https://groups.google.com/forum/#!topic/openpnp/knlnB8PrGw0
Added hotkey Ctrl-H as an alternative choice for HOME. 
While Ctrl-\<backtick\> works for me on my system, at best it is a confusing character to describe. 
Some users also report it as not working on their version of windows.
Ctrl-H acts as a mnemonic (second only to using the actual home key) 
I added Ctrl-H as an alternative leaving the original hotkey alone
Press Modifier-H to "Home" the pick and place head
Tested on live machine (Liteplacer conversion to openpnp) under Windows 7
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-st …

Added alternative HOME hotkey Ctrl-H (Modifier-H to be P.C.)

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/model/Location.java

This patch adds a feature that checks the nozzle position against the board position and Z distance. If the nozzle would move into the board either from the side or from the top it throws an exception.
Crashing the nozzle into board can damage the board as well as the nozzle. Therefore, it makes sense to prevent jog moves from accidentally crashing into the board. The code is generic and not machine specific.
1. Load a board and set the Z position.
2. Move your head above the board e.g. by using the camera.
3. Move the nozzle to the head position.
4. Try to move the nozzle into the board (be careful!).
5. When reaching the Z tolerance position an exception message will pop up.
6. To override the Z limit you can use the button in the jog panel.
The code has been tested on a real machine …

Protect board against nozzle

---

CHANGES.md
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/vision/FluentCv.java
src/main/java/org/openpnp/vision/Ransac.java
src/main/resources/org/openpnp/machine/reference/feeder/ReferenceStripFeeder-DefaultPipeline.xml

Fairly large-scale improvements to the Auto Setup feature of ReferenceStripFeeder. Addresses #411, Strip Feeder Auto Setup Improvements. Holes for all strips in the camera view are now correctly identified and grouped into per-strip lines. The logic around which line of holes to use is improved, as is the final selection of what reference holes to use. A few bugs were discovered in the process and squished. More setup errors are also caught and handled.
The Auto Setup feature is now very robust.
No user-facing changes other than better results and catching user-/setup-errors better.
Tested extensively with all the strips in the default job/reference machine, with correct user-behaviour, incorrect …

Reference strip feeder improvements

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/vision/FluentCv.java
src/main/java/org/openpnp/vision/pipeline/stages/BlurGaussian.java
src/main/java/org/openpnp/vision/pipeline/stages/BlurMedian.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectCirclesHough.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectFixedCirclesHough.java
src/main/resources/org/openpnp/machine/reference/feeder/ReferenceStripFeeder-DefaultPipeline.xml

- Changes to the ReferenceStripFeeder default CvPipeline to improve detection accuracy with real-world cameras (works with the simulated camera too). Tested and proven quite reliable on white tape, black tape, and even transparent(!) tape
- Added descriptions for some Hough circle parameters
- Exposed the threshold/detection related parameters from DetectFixedCirclesHough, as only the feature size ought to be fixed
- Added odd-numbers-only check to BlurGaussian and BlurMedian, to avoid an assertion in OpenCV. Matches the assertion (and description) in ThresholdAdaptive for blockSize.
- Auto Setup: The best-fit line of holes for Auto Setup is now taken as the longest line that is within our desired distance ranges rather than the closest, as that would often get influenced by falsely …

ReferenceStripFeeder CvPipeline improvements

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

Only display the error message box once (but always log), until we get a situation that no longer causes errors. Fixes #644, "Stripfeeder Autosetup pop-up loop with broken pipeline".
Fixes #644.
N/A
Tested with known-working pipeline, disabled the "results" stage, observed only a single error message box was displayed, re-enabled "results" stage, observed it was working correctly, re-disabled "results" stage and observed that a single message box was once again displayed. Checked Log tab to ensure that all errors were still being logged, and they were. Re-re-enabled "results" stage. Everything worked as expected.
Yes
3. If you made changes in the …

Only display the error message box once (but always log)

---

src/main/java/org/openpnp/gui/JobPanel.java

Solves #652 
Adding a tooltip to the job table where the full filename of a board will be shown if hovering the first column (short filename column).
Was suggested by tisco24 and Jason liked the idea. Also I needed a short break of my other stuff.
Hover the first column of the job board list and a tooltip displaying the full filename will come up
Manual testing with the example files. Also ran the tests

Adding a tooltip showing the full filename of a board within a job

---

src/main/java/org/openpnp/spi/base/AbstractCamera.java

New event to turn on lighting earlier than triggered by Camera.BeforeCapture. Leaves the camera time to settle indeed to the new lighting conditions. Fires early enough if the lighting starts with a little delay.
The settle time is granted to the camera to adapt to new lighting conditions if dynamically switching light and to have the machine parts standing still. Would be great to be able to change the lighting condition at the beginning of the settle time, which the new event allows for.
use as Camera.BeforeCapture. SettleBeforeCapture is triggered "Settle Time" earlier than BeforeCapture.
Yes, script is fired as expected.
Yes.
3. If you made …

New event "Camera.BeforeSettle"

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceFiducialLocator.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceFiducialLocatorConfigurationWizard.java

While fiddling with the machine I found it would be nice if the number of "dial ins" while recognizing fiducials would be configurable. Additionally some type of averaging as option would be great. With just 3 repetitions and without averaging it happens sometimes, the machine goes back and forth in a very small amount but never hitting the exact center... For my setup this improved the accuracy of detection (used 6 matches instead default 3). 
Maybe how the average is calculated could be thought over: Is it better to calculate a moving average while dialing in or just apply the average in the end, as it is implemented now.
Giving the user the ability to configure the number of repetitions and averaging enables him with little effort to check whether the accuracy can be enhanced further …

Configurable repetition of fiducial recognition and averaging result

---

src/main/java/org/openpnp/gui/LogPanel.java

Fixes #680 as there seems to be an issue with JPanel Border Layout if there is no center element.
Fixes small issue with the graphics
Set the button JPanel to Center instead of East which fixes the issue. The buttons are still not visible or usable, but at least we get no problems with displaying.

Fixes #380: overflow of the buttons in the JPanel

---

src/main/java/org/openpnp/machine/reference/signaler/SoundSignaler.java

The sound signaler is shipped with two default free sounds for indicating success or error. This PR allows users to override those files.
Solves #668
There are two files which can be replaced and need to be wav files: 'error.wav' and 'success.wav'.
Place them in the OpenPnP configuration directory under sounds e.g. '~/.openpnp/sounds/success.wav' or 'C:\Users\pfried\.openpnp\sounds\success.wav' 
@vonnieda If you accept this PR I will update the Wiki accordingly

Allowing users to override the default sounds of the sound signaler

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

had issues editing the pipeline for a feeder but didn't know what the problem was. the error message was unclear to me:
so I changed the title of the pipeline editor, since it is feeder specific, not part specific...
if a part is deleted and a feeder had it assigned, the feeder has no part any more. editing the pipeline gives the error, which is unexpected and doesn't indicate the problem.
no instructions...
started openpnp and edited a strip feeder without part assigned. -> works now.
yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional …

renamed pipeline editor title for stripfeeder to prevent nullpointerexception

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/machine/reference/ReferencePasteDispenseJobProcessor.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/spi/JobProcessor.java

Gives the user one more option on how to handle errors while assembly. The new option ignore and continue allows the user to ignore errors raised from alignment per bottom vision as if everything is right.
if user checked for pick being ok, it should be allowed to continue.
1. pick a part with insufficient vac (vac sensor needed) and click continue -> it goes to alignment
2. picked part will be checked on bottom camera -> if it fails, one could continue anyway.
unit test and on real machine (vac insufficient and bottom vision failed if removed part).
yes
3. If you made changes in the …

Added option to ignore error and continue assembly

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

until today if skipping a part due to an error (vac/aligning failed) always nozzle 1 is cleared per discarding a part into the discard box. this patch fixes this an takes the right nozzle into account.
it's very annoying to have the wrong nozzle cleared and investigate which part was assembled, which not and remember which parts to fix in next run...
click "skip" if an error occured. now the correct nozzle is cleared and the assembly for the rest goes on.
tested on my machine with 2 nozzles on one head.
I tested 2 cases:
1: removed nozzle tip from nozzle 1. pickup from feeder failed of course, vacuum sense check failed and it gave me the option to skip/retry, etc. -> clicked skip -> nozzle 1 went to …

Bugfix: On Skip discard right nozzle

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/model/BoardLocation.java
src/main/java/org/openpnp/util/Utils2D.java

fixes #663: if having fiducials checked, placed flag is set correctly.
don't know whether it's an naive approach or it breaks something else? but at least it fixes the bug ;)
it's annoying to have the placement flags not set properly.
use as expected, no matter if with or without checking.
on my machine in a testrun
think so
no changes
4. Be sure to run `mvn test` before submitting the Pull …

Mark placed again

---

src/main/resources/scripts/Examples/Python/use_module.py
src/main/resources/scripts/Examples/Python/utility.py

Add a Python example the imports another Python module, similar to `Move_Machine.js`.
This shows users how they can decompose their software into more than one Python module.
Tested in OpenPnP

Add Python script example that imports another Python module

---

src/main/resources/scripts/Examples/Python/call_java.py

Reproduce Javascript `Call_Java.js` in Python.
Add another example in Python.
Run Scripts | Examples | Python | call_java.py. A java window should pop up.
Tested in OpenPnP

Add Python script example that calls Java

---

src/main/resources/scripts/Examples/Python/move_machine.py

Add Python script that moves the nozzle in a similar way to the Javascript example `Move_Machine.js`
There is currently no Python script example that moves the 
Enable the machine, select Scripts | Examples | Python | move_machine.py
Tested on virtual device/driver.

Add Python script example that moves the nozzle

---

src/main/resources/scripts/Examples/Python/Print_Nozzle_Info.py
src/main/resources/scripts/Examples/Python/print_nozzle_info.py

Make nozzle script Python 3 compatible and PEP8 style compliant.
This will be used as an example by others, so helping them write code that is Python 3 compatible will be useful.
According to the Python PEP8 style guide, modules should be lower_snake_case so this makes this module adhere to that standard.
The `str.format` method is used to simplify the `print` calls.
Tested in the virtual device/driver and performs the same.

Make nozzle info script Python 3 compatible

---

src/main/resources/scripts/Examples/Python/Print_Hallo_OpenPnP.py
src/main/resources/scripts/Examples/Python/print_hallo_openpnp.py

Use parenthesis when calling `print` to make Python 3 compatible.
This will be used as an example by others, so helping them write code that is Python 3 compatible will be useful.
According to the Python PEP8 style guide, modules should be `lower_snake_case` so this makes this module adhere to that standard.
N/A
This code was tested using the virtual device/driver and behaves the same as it did.

Make hallo openpnp script Python 3 compatible

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

When having a non-zero Y home, the non-squareness factor X offset is not applied to the internal X coordinate immediately after homing. Instead the internal X is simply set to the non-square machine home X. If you capture the home location and later return to it, you will have an offset. Best observed with a homing fiducial. 
NOTE that this bug (and its resolution) does not concern the machine operation after that. The discrepancy between internal (square) coordinates and machine (non-square) coordinates is resolved as soon as the first move command is issued. Because the controller moves in absolute mode, the offset is corrected.  
The homing fiducial is a useful point of reference. It is useful to capture this after-homing location as a park location. This is currently broken if you …

Adjust homing location for non-squareness when Y home non-zero

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java

This reintroduce the option to support multiple uplooking parallel cameras without the need of recompile the sources.
This …

reintroduce multiple uplooking camera support

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/tablemodel/PlacementsTableModel.java
src/main/java/org/openpnp/model/BoardLocation.java

Added indicator label how many active and how many completed placements are listed in this board.
It provides the user with better overview of the current placement progress (like a progress bar - maybe a good future addition) and before starting a job provides valuable information about the number of placements planned for this PCB.
The label automatically updated whenever a placement is set to "fiducial", "ignore", "place", when a placed flag is set or when a placement side is changed. It also automatically updates during job runs and when a job placement status is reset.
1. How did you test the change? 
I used the nulldriver and with multiple boards and also tried the autopanel feature.
In autopanel mode the active placements are "per" board. …

active placement number indicator

---

.gitignore
src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/components/CameraPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceDragFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceDragFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceMachineConfigurationWizard.java
src/main/java/org/openpnp/spi/Machine.java
src/main/java/org/openpnp/spi/PnpJobProcessor.java

- Filter PlacementsTableModel, show only active board side.
- Added option to AutoHome after machine enabled. To activate, need to set checkbox in machine settings.
- Windows saves sizes and position in Multiple Windows Mode
- Save configureation menu button
- Camera window can be split in vertical or horizontal style
- Added new approach to pick rotation for Strip Feeder. To activate, need to set checkbox in machine settings. https://github.com/openpnp/openpnp/issues/715
- Some changes in job order. Now user can change job order by sorting table.
- Job autosave after each placement.
- Added peel off actuator option for Drag Feeder.
- Drag Feeder improve accurance of feed, now drag distance can be adaptive with vision enabled.
- Drag Feeder can work with 0402.

My changes and impromevents

---

CHANGES.md
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipConfigurationWizard.java

The Dwell Pick and Dwell Place times have been added to Nozzle Tip class and the Nozzle Tip Wizard GUI.
I also added a note that the total dwell time is the sum of both nozzle dwell time and nozzle tip dwell time.
I have found no reference of where/how getPlaceDwellMilliseconds() is actually used (in job planner or machine driver?) so I need some guidance before I can finish this feature.

Nozzle Tip: Dwell Time

---

src/main/java/org/openpnp/gui/FeedersPanel.java

Also Correct wrong javadoc param
Clears the feeder search textfield when a new feeder is created so it can be selected in the list, avoids the index error filed in #714
Its best to show the new feeder in the list. If it is not visible the user might think it has not been created
Clears the textfield and triggers search

Clear search field on new feeder created, fixes #714

---

src/main/java/org/openpnp/machine/openbuilds/OpenBuildsDriver.java
src/main/java/org/openpnp/machine/reference/driver/AbstractReferenceDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/LinuxCNC.java
src/main/java/org/openpnp/machine/reference/driver/wizards/AbstractReferenceDriverConfigurationWizard.java

With this Pull Request the OpenPNP drivers OpenBuildsDriver, GcodeDriver and LinuxCNC disconnect when the Machine is disabled.
The disconnect allows for a serial port to be reused in another program (i.e. Pronterface) or unplugged, or the controller reset without closing OpenPNP. If the serial port becomes available again, the machine can be enabled again and the connection is successfully re-established.
Before this change this failed at least under Windows where a COM port name is blocked until explicitly closed by the process. Even resetting/re-plugging the controller will not free the port and also not re-establish the connection as long as a process sits on it. OpenPNP has to be closed and the controller reset/re-plugged one more time, before a freshly started OpenPNP can then …

OpenBuildsDriver, GcodeDriver and LinuxCNC disconnect when disabled.

---

src/main/java/org/openpnp/Scripting.java
src/main/java/org/openpnp/gui/support/MessageBoxes.java

Jython exceptions with messages like `NameError: name 'prit' is not defined in <script> at line number 2` got truncated in the GUI message box because of the angle brackets. Also, since the script's filename was not populated prior to execution, the error message unhelpfully stated that the error occured in `<script>`.
The change improves script error handling for developers and users who did not set the loglevel to debug prior to execution.
Just execute any script that throws an exception.
I tested with a bunch of broken and exception-raising Python scripts. I could not find other causes for truncation of the messages.

Improve display of scripting exceptions 

---

src/main/java/org/openpnp/machine/reference/driver/SerialPortCommunications.java

My system based on Mac has 10+ serial devices connected, but openpnp with SerialPortList.getPortNames() can see only 6 of them.
This patch worked for me, now i see all devices and can easily work with them, including /dev/tty.Bluetooth...

serial fix

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

This will add new Gcode MOVE_TO_COMMAND coordinate variables XF, YF, ZF, RotationF that are force-output even if the coordinate has not changed according to the internal Axis getCoordinate() record. 
These variables may be employed for shared axes, where OpenPNP cannot not keep track of when an axis has physically moved behind its back through a shared actuator. Consequently getCoordinate() may not reflect the actual physical coordinate. By always forcing the axis coordinate output, the controller will take care of restoring the shared axis' correct position, if necessary. As we are always moving in absolute coordinates this has no ill effect if it results in no position change after all (i.e. when there was no coordinate change behind its back).
Switching back and forth between shared …

Add new Gcode MOVE_TO_COMMAND variables XF, YF, ZF, RotationF

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java

Change the functionality of the Move camera to next placement button.
Old behavior: The camera would move to the current location and the highlighted part would move to the next part. Then when you want to adjust the placement location you must select the part you are actually looking at as the next part is already selected in the placements panel.
New behavior: The highlighted part is moved and then the camera is moved to its location.
This way, the part in the camera view and the part highlighted in the parts list are the same. Then if you adjust the placement, when you press the "Set placement to current camera location" etc the correct part will be edited instead of the next part in the list.
To quickly move the camera to the next placement in the placement table just press the "Move …

Update the Move Camera to Next Placement button.

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/JobPlacementsPanel.java

Fixed Camera move to next buttons and made button focus better.
This change makes the board highlighted in the Job panel the same as the the board shown in the camera view
Just push the button and the camera will move to the next board or placement depending which button is pressed.
Jogged my machine around using the button and space bar to go to the next boards and next placements.
Yes
4. Be …

Fixing move camera to next buttons

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java

Continue to #804. This PR adds
1. automatic removal of nozzle tip offset locations that are above offsetThreshold and
2. sorting the pipeline's result list by linear distance to the bottom camera if multiple results are returned.
3. some minor changes + debug output
to 1) wrong configured pipelines may return large offsets -> these are eliminated by this change
to 2) if there are multiple results (though it is recommended to configure the pipeline to have only ONE result), the list is sorted by distance to bottom camera. the location with the smallest distance is taken as valid for further processing. this may improve results, but doesn't have to since there can't be made any educated guesses which is a valid offset location.
There will be added a offsetThreshold value to the GUI later. …

More Robust Nozzle Tip Calibration

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java

Add scripting events NozzleTip.BeforeLoad and NozzleTip.BeforeUnload
Script events before loads/unloads allows full access to the nozzle change process and can be used to adjust behavior as needed. 
Add NozzleTip.BeforeLoad.js and/or NozzleTip.BeforeUnload.js to the Events directory.
Tested by forcing nozzle changes, both with and without scripts in the Events directory.
mvn test run was clean and without errors.

Add NozzleTip.BeforeLoad and BeforeUnload events

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/util/VisionUtils.java

The PR contains the following extensions and cleanup:
* Bottom Vision now stores the rotation offset in the `PartAlignmentOffset`. 
* The angle calculation is simplified with regard to [distributive modulo equivalences](https://en.wikipedia.org/wiki/Modulo_operation#Equivalences).
* pre-rotate BottomVision is done in a multi-pass loop until a good fix is obtained.
* X, Y offsets are obtained together with the rotation offset, so with a good fix only one vision pass is needed.
* X, Y offsets are therefore compensated for rotation.
* Maximum allowed linear and angular offsets can be configured (GUI).
* `angleNorm()` is used instead of duplicated code in `findOffsetsPostRotate()`
* a redundant `Location.derive()` is removed in `findOffsetsPostRotate()`
By storing the rotation offset in the …

BottomVision should store rotation offset in the PartAlignmentOffset

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

fix error message 'Unable to parse CSV file names' to 'Unable to find relevant headers' names.'
The previous message was unclear to an unaware person.
Added a link to wiki too in the message.

fix error message 'Unable to parse CSV file names' to 'Unable to find relevant headers' names.'

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

Users may use extended ascii char. In particular the µ char for µF.
As a result the µ char is not correctly rendered in the gui:
Current implementation opens csv file as 7bits ascii file (US-ASCII).
Switching to ISO-8859-1 does not change anything for people using only 7bits chars but allows the µ char to be displayed as it should:
Imported files with µ char in.

open csv file as ISO-8859-1 to allow the use of 8 bits ascii char.

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/AdvancedLoosePartFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceLoosePartFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceFiducialLocatorConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceFiducialLocatorPartConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipConfigurationWizard.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditorDialog.java
src/main/java/org/openpnp/vision/pipeline/ui/PipelinePanel.java

Initialize CVPipelineEditor with last stage selected and stage grid focused
User see immediately the result of the pipeline.
He can immediately navigate through stages using up/down arrow keys.
Open any pipeline editor, press up/down keys.
Manual tests.
Mini refactored the actual code to remove redundant parametering of the dialog.
Yes ! love them.
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and …

Initialize CVPipelineEditor with last stage selected and stage grid focused

---

src/main/java/org/openpnp/vision/pipeline/stages/MaskHsv.java
src/main/resources/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder-DefaultPipeline.xml
src/main/resources/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder-DefaultTrainingPipeline.xml
src/main/resources/org/openpnp/machine/reference/vision/ReferenceBottomVision-DefaultPipeline.xml

Description:
Since hue is a circular quantity it is perfectly reasonable to mask hues that cross the 255 - 0 boundary.  For instance, red hues range roughly from 235 through 21 (passing through the 255 - 0 boundary).  To mask such a range, the user would enter a hueMin (235) that is greater than hueMax (21).  Unfortunately the logic in mashHsv is incorrect in that case.  While it does correctly mask the desired hue range under that condition, the logic for masking saturation and value get inverted so that the returned image only contains pixels that have saturations and values that are in the range that should have been masked.
The fix to this problem is to create two masks, one for the hueMin to 255 range and one for the 0 to hueMax range, OR them together and then proceeding as in the …

Correct logic in maskHsv when hueMin is less than hueMax

---

src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java

- Bringing back the buttons to load/unload nozzle tips from the NozzleTip Wizards. The nozzle currently selected in the machine controls panel is used to perform the load/unload (or the default, if no nozzle is selected).
- Updating the Calibration Status info-text when a nozzle tip is loaded/unloaded or the if the currently selected nozzle changes in the machine controls panel. The latter is only relevant for the "unloaded" stand-in nozzle tip used to calibrate the naked nozzle. 
- Fix: when a nozzle tip is requested to be loaded on a nozzle tip, it needs to be unloaded first, if it is currently loaded on another nozzle.  
- EDIT: Removing the choice of the calibration system from the UI. On update, all configurations are forced to the "Model & Camera Offset" system. The calibration …

Nozzle Tip Changing and Calibration UI Touches

---

src/main/java/org/openpnp/machine/reference/ReferenceMachine.java

Adds new scripting event 'Machine.AfterHoming'.
Allows further setup after homing. In my case I'm using it to z-probe with vacuum sensor.
Add Machine.AfterHoming.py to the Events directory.

Add scripting event after homing is complete 'Machine.AfterHoming'

---

src/main/java/org/openpnp/machine/reference/driver/AbstractReferenceDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverSettings.java

This feature allows usage of Java style escape sequences to insert arbitrary Unicode characters in Gcode strings.  
Some machine controllers may require special character sequences to perform certain actions.  For instance, recovering a TinyG from a hard alarm state (such as after a limit switch hit) can be accomplished by sending a ctrl-x character (\u0018) to its serial port (typically as part of the DISABLE_COMMAND).
This feature is disabled by default and needs to be enabled  prior to use by checking the "Backslash Escaped Characters" checkbox on the GcodeDriver General Setting tab.  Then any occurrences of  \uxxxx (that is a backslash followed by a lower or upper case u followed by exactly four hexadecimal characters) in any Gcode string will be replaced by the Unicode character …

Allow escaped character sequences in Gcode strings

---

src/main/resources/scripts/Examples/JavaScript/Pipeline.js

Pipeline.js example failed to execute.
This fixes a bug in the example Pipeline.js scripts
I changed the Pipeline.js script file and saw the blur.
Yes

fix XML syntax error

---

src/main/java/org/openpnp/gui/panelization/DlgAutoPanelize.java

It was ambiguous if you were wanting the distance from one point on a pcb to the same point on an adjacent pcb on a panel or the gap between the pcbs.

Simple text changes to address things I found ambiguous when starting

---

src/main/java/org/openpnp/gui/JogControlsPanel.java

Scripting events 'Job.BeforeDiscard' and 'Job.AfterDiscard' called from discards triggered via GUI.
Discards during jobs use a different code path that discards triggered via the GUI. This adds the scripting events to the later.  
Add scripts/Events/Job.BeforeDiscard.js and/or scripts/Events/Job.AfterDiscard.js
Ran mvn test.
Compiled new build and ran discards with and without scripts installed.

Added scripting support to discards made via GUI

---

src/main/java/org/openpnp/vision/pipeline/stages/ActuatorWrite.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java

I have added Cv pipeline stage which allows writing to actuators. 
This allows controlling actuators directly from Cv pipeline, without using external scripts ( there is a Cv pipeline stage which can execute such script). It helps e.g. to control light intensity directly (if you have such actuator - it is quite common case) 
Setup actuator name, value and type ( double of boolean) - in similar way as all other parameters for any stage.
This code was copied mainly from part controlling feeder actuators, it was just formatted to follow Cv stage classes implementation
Tested for positive (proper actuator) and negative cases ( wrong actuator name).
It supports all actuators ( machine and head based)

Added pipeline stage to write actuators

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceFiducialLocator.java

Fixes panel bottom fiducial detection.
Bugfix #905 fixed the board bottom fiducial detection, but the panel fiducials were still incorrect.  This is because the panel must always be treated as top side for the purpose of fiducial detection.  This will update the origin of each board in the panel to the lower left corner of the boards.
Set up the panel the same as for the top side.  If the fiducial locations are different, set them also.  Fiducials are referenced to the lower left corner of the lower left board (board 0 origin).
1. How did you test the change? I created a 2 x 3 panelized version of the pnp-test board with top and bottom panels.  Panel and board fiducials were properly located for top and bottom.  Components appeared in the correct positions.  I also tested on a live system …

Fix bottom side panel fiducial check

---

src/main/java/org/openpnp/gui/MachineControlsPanel.java

Just a small bugfix for a type cast error that pops up from time to time. I believe it was introduced when Actuators were allowed as selected tool in the machine controls.
The comboBox no longer contains `NozzleItem`s but `HeadMountableItem`s. See the "cameras" change listener following for symmetry. 
The change is also part of #859 and merging this would simplify the code review there.
Bugfix. 
1. I have run `mvn test` before submitting the Pull Request.

Removed type cast error in machine controls "nozzles" change listener.

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/test/resources/config/BasicJobTest/machine.xml

Solves Issue #913
Removing backward compatibilty stuff from the 
src\main\java\org\openpnp\machine\reference\ReferenceNozzleTip.java
and added missing middle 2 positions to 
src\test\resources\config\BasicJobTest\machine.xml
to fulfill the automatic tests 
it solves issue #913 
used it and added new nozzle tip and the problem of missing line and not able to write the machine.xml is gone. now it starts with 0.000.
AFAIK just copy and pasted the new constructor...
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these …

getting rid of toolchanger config backward compatibility due to issue #913

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java

getPickLocation() is using visionLocation value to calculate pick location. visionLocation already contains value that was previously corrected in updateVisionOffsets().
l value (pick location) is calculated from lineLocations, which may be calculated using visionLocation in getIdealLineLocations().
Vision offset was added twice and pick location error was increasing with feed count so much, that it was almost impossible to use strips longer than ~20-30 parts.

Remove duplicated vision offset correction

---

src/main/java/org/openpnp/machine/reference/ReferenceHead.java
src/main/java/org/openpnp/spi/Head.java

A method on the Head can be called to determine whether a HeadMountable can go to the specified location within the soft-limits. 
The soft-limits check is currently only implemented inside ReferenceHead.moveTo(). In order to proactively check whether a location is within soft-limits, the check is refactored into a separate method.
The method is used in my upcoming feeder to check the eligibility of fiducials on the feeder. 
Use `head.isInsideSoftLimits(hm, location)` to check if the HeadMountable `hm` can go to `location`.
1. The refactored soft-limit checking on moveTo() was successfully tested on purpose. It was also very useful in developing, when things went wrong. The new method was also successfully used for the feeder I'm developing, to select eligible fiducials for feeders that …

Method to determine if a location is inside soft-limits.

---

src/main/java/org/openpnp/model/Length.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/vision/Ransac.java

In order to ease merging an upcoming large feeder PR, I'd like to break these small additions out:
* divide and modulo of Lengths
* derive and unit-adapt one (partial) Location to another
* bugfix in Ransac if the indicesOnLine turns out empty
Division and Modulo of Lengths is just a logical extension of the present methods. Doing it outside the class is very ugly (and units are often forgotten). Used multiple times in the upcoming PR. 
Even in my past PRs, the need to derive (partially) from one Location and unit-adapt to another Location was ever-present. This typically resulted in hard-to-read, easy-to-bungle, lengthy statements. In the new feeder it was turning ugly. I finally wrapped this into a safe method.
The bug in Ransac occured when I tried to solve one vision problem. I later …

Various small additions to utils, one bugfix

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/components/LocationButtonsPanel.java

Add scripting event after camera move to position.
Add a scripting event after moving the camera to position by pressing the Position the Camera Icon.
Most of the time when pressing the Position the Camera Icon, I want to look at something, so I have to turn on the down light.  I thought it would be nice if the light could be turned on automatically so I added this scripting event.
Put a Camera.AfterPosition script in the scripts/Events directory.  For example:
Camera.AfterPosition.js
> /**
>     Controls lighting for the down camera 
>  */
>  var downCamLights = machine.getActuatorByName("DownCamLights");
>  downCamLights.actuate(true);
1. How did you test the change?  Added above script and verified light was turned on when using the Position the Camera Icon.
2. Did you follow the …

Add scripting event when using the "Position the Camera" button.

---

src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceLeverFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceLeverFeederConfigurationWizard.java

ReferenceLeverFeeder supports feeders where a lever is pushed one or more times to feed the parts (such as Alex Feeder).  Made from ReferenceDragFeeder.
While the ReferenceDragFeeder can be used for this type of feeder, it has some issues.  It doesn't support part pitch greater than 4 and the feed operation is not optimal.
You will need a Head Mountable Actuator defined.  It doesn't have to do anything for this feeder.  You can also define a cover take-up actuator if needed.  Add a new ReferenceLeverFeeder and use the wizard to set it up.  Setting the part pitch to 2mm will pick 2 parts per feed.  If the pitch is greater than 4mm, the appropriate number of feeds will be performed for each pick.
1. How did you test the change? I tested it on my machine set up with 15 feeders of various …

New ReferenceLeverFeeder

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleToolChangerWizard.java
src/main/java/org/openpnp/spi/Nozzle.java

Note, this is a repeat of what the #939 was intended to be. The changes were reverted in the merge, due to a git misunderstanding on my side.
---
A pick in the Feeder Panel does not behave like one would in a Job. So this PR aims to implement a more "job like" behavior for the manual pick operation:
- The selected feeder is prepared (like all of them would in a Job).
- This results in the desired behaviour with the BlindsFeeder, otherwise it would sometimes end up in a ridiculous NozzleTip changing frenzy.
- You can now switch on automatic NozzleTip change on manual feed in the "Tool Changer" wizard of the Nozzle.
- If enabled, the NozzleTip is automatically changed for one that is compatible with the package in the feeder.
- If disabled, the pick is aborted if the NozzleTip is …

Feature/A More Job Like Manual Pick (Repeat)

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleToolChangerWizard.java
src/main/java/org/openpnp/spi/Nozzle.java

Reverts openpnp/openpnp#940
@markmaker I think the history of this commit got tied up in the BlindsFeeder PR so that when I merged the BlindsFeeder PR Github thought this had been merged as well, so it closed the PR and marked it merged, but it was not actually merged.
I'm not quite ready to merge this yet, so reverting and will discuss in the PR.

Revert "Feature/A More Job Like Manual Pick (Repeat)"

---

src/main/java/org/openpnp/gui/support/AbstractConfigurationWizard.java

The setWizardContainer method was changed to prevent it from creating bindings more than once.  This fixes a bug introduced/uncovered by PR 934.  That PR added a call to a feeder wizard's setWizardContainer  method to set the container to the feeders panel.  Unfortunately, the setWizardContainer method also called the wizard's createBindings method which resulted in bindings being created twice.  This caused noticeable problems with the reference slot auto feeder wizard - probably due to the unique way it set-up bindings.  The other feeder wizards didn't seem to display the same issue although their bindings were also being created twice.
Makes the reference slot auto feeder wizard work correctly.
No special instructions needed.
**1. How did you test the change?** Duplicated the problem …

Prevent setWizardContainer from creating bindings more than once

---

src/main/java/org/openpnp/gui/importer/KicadPosImporter.java

The fix is for handling placement for bottom parts, imported from KiCad pos files. The bottom parts need to be mirrored at the 90°/180° axis.
The fix enables importing KiCad bottom part placement/position files for populating boards.
n/a, simply import KiCad files. Bottom part position and orientation will be updated so parts can be placed with OpenPnP
Tested with with a PCB having parts on the bottom (capacitors, SOT-23 parts) in different orientation (90/180/0/45/135/270 degrees). They all worked fine with the change/fix.
yes.
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` …

Handling of KiCad bottom part rotation

---

src/main/java/org/openpnp/gui/components/LocationButtonsPanel.java

Due to
https://github.com/openpnp/openpnp/commit/61ef27ebd64fe358291034cb84338e029e0c8574
there are exceptions, when pressing the tool capture button. No message box is displayed, it just silently fails.
```
Exception in thread "AWT-EventQueue-0" java.lang.Error: Cannot call invokeAndWait from the event dispatcher thread
at java.awt.EventQueue.invokeAndWait(EventQueue.java:1331)
at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
at org.openpnp.gui.components.LocationButtonsPanel$2.lambda$0(LocationButtonsPanel.java:230)
at org.openpnp.util.UiUtils.messageBoxOnException(UiUtils.java:97)
at org.openpnp.gui.components.LocationButtonsPanel$2.actionPerformed(LocationButtonsPanel.java:223)
```
The camera capture …

Fix/LocationButtonsPanel invokeAndWait usage

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/wizards/ReferencePnpJobProcessorConfigurationWizard.java
src/main/resources/org/openpnp/translations.properties

Currently the job processor has a hardcoded vision retry. Added a new property and corresponding UI element.
Test via mvn test, and with both clean and existing openpnp configs.

Add a setting that allows max vision retries to be changed.

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

Currently the 'PartHeight' job order sorts only based on height. When placing many different parts with the same height the actual order is not defined: it may place 603-10k -> 603-1k -> 603-10k.
This change uses the part id as a secondary sort option. Parts will be placed in order of height, and when multiple parts are the same height they will be grouped together: 603-1k -> 603-10k -> 603-10k.
Current height based placement is impossible to predict when multiple parts have the same height. This is a big time sink when manually feeding (or dealing with problem feeders).
Tested with mvn test, and by running jobs various jobs.

Sort 'PartHeight' jobs by id as a secondary field.

---

src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/feeder/SchultzFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/SlotSchultzFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/SchultzFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/SlotSchultzFeederConfigurationWizard.java

Adds a regular feeder and slot feeder.  The slot feeder version makes use of the ID in the feeder EEPROM to know which feeder is in the slot.
Adds new functionality which many users will find useful.
Open the Feeders tab and add a new feeder.  Select SchultzFeeder or SlotSchultzFeeder and use the wizard to set it up.  I will add a section to the wiki after this is merged.  In the meantime, there are some instructions on my github [wiki](https://github.com/bilsef/SchultzController/wiki).  I have scripts to help with setting up the slots.  These feeders have a fiducial, so I make use of it and added a button to the SlotSchultzFeeder wizard to precisely set the feeder location based on the fiducial.  There is a script to automate that as well, when feeders are swapped out.
1. How did you …

Add support for Siemens Schultz feeders

---

src/main/java/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder.java
src/main/java/org/openpnp/vision/pipeline/stages/ClosestModel.java

The AdvancedLoosePartFeeder sometimes fails with a Null Pointer Exception or sometimes with a Class Cast Exception.  This change fixes those so that the feeder correctly reports "No parts found." instead.  
Makes it easier for the user to understand what is going wrong.
No special instructions needed.
1. Had a setup on my machine which could reliably cause the two previously stated exceptions.  After making the change, re-ran and the feeder correctly reported "No parts found."
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?  Yes.
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and …

Fixed null pointer and class cast exceptions in AdvancedLoosePartFeeder

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java

Fixes a small logic error in Revision: bd3a78a5f2890aa430858fed540963a5797cc93e which leads to the pump constantly being switched on and off. Observed this in the log while testing something else (my machine does not actually actuate the pump, it runs on a hysteresis instead).
The pump must only be enabled before the valve switches on and only be disabled after the valve switches off. Same for the value setting variant with blow off. 
See the past change:
https://github.com/openpnp/openpnp/commit/bd3a78a5f2890aa430858fed540963a5797cc93e#diff-b380475a49f8df054452d2236b8bb376
Obvious.
Look into the log with tracing level. Do a small job. 
1. Tested on machine. Observed log. My machine does not actually actuate the pump.  …

Bugfix/Pump Actuation

---

src/main/java/org/openpnp/gui/components/LocationButtonsPanel.java
src/main/java/org/openpnp/gui/support/Icons.java
src/main/resources/icons/position-actuator-no-safe-z.svg

The LocationButtonsPanel already has an option to display a No-Safe-Z button for the selected tool mode. This PR adds the same for the Actuator mode. 
Need to move the actuator with no Safe Z when definition the lever actuation for the `ReferencePushPullFeeder` in #977 .
Without the PR the panel will use the tool instead:
Use the button with the blue line above the red dot instead of the one with the red dot.
1. This was tested inside #977 and is now broken out (so it cannot be tested).
4. Sucessful `mvn test` before submitting the Pull Request.

Feature/Actuator No-Safe-Z button for the LocationButtonsPanel

---

src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/support/Icons.java
src/main/resources/icons/process-activity-1.svg
src/main/resources/icons/process-activity-2.svg

OpenPNP provides a special instructions panel, that pops up underneath the camera views to guide you through setup processes, step-by-step. 
This panel is currently used by the multiple location board location setup process:
If you press the button, "nothing" seems to happen, as the showing of the instructions is quite subtle and all the other user interface elements remain fully active. It is easy to start the process and never finish it. 
This PR adds a blinking icon to the process instructions to attract the users' attention. 
The red icon will blink on and off and the instructions are now hard to ignore. 
The PR also makes sure that the standard dialog font is used, instead of the out-of-place serifed HTML default font.
The process instruction will be used with #977 to setup a region …

Feature/Better Process Instructions Visibility

---

src/main/java/org/openpnp/vision/pipeline/CvStage.java
src/main/java/org/openpnp/vision/pipeline/ui/MatView.java
src/main/java/org/openpnp/vision/pipeline/ui/ResultsPanel.java

This adds the ability for a CvStage to expose a LengthUnit and subsequent display of mouse coordinates in the status line of the ResultsPanel MatView.
For pipelines to remain stable between different camera models, resolutions, lenses, focal distances etc., all dimensions relating to physical objects should be expressed as proper length units rather than pixels. 
This PR prepares the ability for a CvStage to override the `getLengthUnit()` method and expose the LengthUnits in which the stage will express and store such dimensional properties. 
For the user to be able to specify such dimensional properties in a stage, the mouse coordinates are now also displayed as offsets from the camera center, in said LengthUnits, and oriented as Machine coordinates (i.e. Y pointing up rather than down). …

LengthUnits Mouse Coordinates display in Pipeline Editor

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleToolChangerWizard.java
src/main/java/org/openpnp/spi/Nozzle.java

Note, this is a revert of the revert of the repeat of what the #939 was intended to be. 
---
A pick in the Feeder Panel does not behave like one would in a Job. So this PR aims to implement a more "job like" behavior for the manual pick operation:
- The selected feeder is prepared (like all of them would in a Job).
- This results in the desired behaviour with the BlindsFeeder, otherwise it would sometimes end up in a ridiculous NozzleTip changing frenzy.
- You can now switch on automatic NozzleTip change on manual feed in the "Tool Changer" wizard of the Nozzle.
- If enabled, the NozzleTip is automatically changed for one that is compatible with the package in the feeder.
- If disabled, the pick is aborted if the NozzleTip is incompatible (of course, this is up for discussion, like …

Feature/A More Job Like Manual Pick (Repeat 2)

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/BlindsFeederConfigurationWizard.java

I was mistaken, when I said in #979 that the nozzle to be used for the `pick()` is not provided in a `feed()`. This PR now correctly propagates the `feed()` nozzle into the cover actuation and prefers its use. 
In the same spirit the Open/Close buttons in the Wizard will try to use the nozzle selected in the machine controls. 
Note, the preferred nozzle is still subject to its loaded nozzle tip allowing dragging & pushing. Otherwise, a different nozzle with nozzle tip allowing dragging & pushing will be used or (optionally) a nozzle tip change will be performed. 
The change only concerns the BlindsFeeder, therefore risk to other (i.e. more broadly used) code is absent. Even though I couldn't test it fully, because I have no multi-nozzle machine, it would be nice to have this merged in …

Fix/BlindsFeeder: Prefer the nozzle given in feed() to actuate the cover.

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/gui/processes/RegionOfInterestProcess.java
src/main/java/org/openpnp/gui/tablemodel/PackagesTableModel.java
src/main/java/org/openpnp/machine/reference/ReferenceFeeder.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/BlindsFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullMotionConfigurationWizard.java
src/main/java/org/openpnp/model/Package.java
src/main/java/org/openpnp/model/RegionOfInterest.java
src/main/java/org/openpnp/spi/Feeder.java
src/main/java/org/openpnp/spi/base/AbstractFeeder.java
src/main/java/org/openpnp/util/OpenCvUtils.java
src/main/java/org/openpnp/vision/SimpleHistogram.java
src/main/java/org/openpnp/vision/pipeline/stages/AffineUnwarp.java
src/main/java/org/openpnp/vision/pipeline/stages/AffineWarp.java
src/main/java/org/openpnp/vision/pipeline/stages/MatchTemplate.java
src/main/java/org/openpnp/vision/pipeline/stages/SimpleOcr.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java
src/main/resources/org/openpnp/machine/reference/feeder/BlindsFeeder-DefaultPipeline.xml
src/main/resources/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder-DefaultPipeline.xml

_This is the reinstated #977 (after mistaken merge & revert) for continued discussion and improvement._
Generic implementation for a feeder that can feed parts by performing push and pull (and other) motions using a head-mounted Actuator.  
- Uses a semantic vision concept based on sprocket holes and knowledge of the EIA 481 standards. 
- Simple OCR vision stage that can read the part from a label on the feeder. 
- OCR based automatic feeder slot swapping, part changing or even new feeder creation. 
- Automatic and learning "only when needed" calibration for feeders that are mounted with large tolerances (+/-2mm). 
- Any part pitch, any feed pitch, any tape width.
- Multi-feed: 2mm pitch/0402 support. For speed, you can also use a multiplier for any pitch. 
- Easy to clone & sync settings …

Feature/ReferencePushPullFeeder (Reinstated)

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/BlindsFeederConfigurationWizard.java

For the 3D-printed BlindsFeeder you can extract the OpenSCAD model files directly from OpenPNP.
For more information see the Wiki.
https://github.com/openpnp/openpnp/wiki/BlindsFeeder#modelling-the-feeder
On some platforms (Linux, Debian Buster) the `java.awt.Desktop.getDesktop().edit()` is not supported, [users have reported](https://groups.google.com/d/msg/openpnp/Ew7drDA3J60/a-XU02moDAAJ).
This bugfix catches any exceptions and continues to extract the second file. It reports the error to the user.
Bugfix.
See also:
https://groups.google.com/d/msg/openpnp/Ew7drDA3J60/a-XU02moDAAJ
Just use the
1. I prompted an exception by debugger.
3. No changes in the `org.openpnp.spi` or …

Fix/BlindsFeeder: OpenSCAD File Extraction on Linux

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/components/SimpleGraphView.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipPartDetectionWizard.java
src/main/java/org/openpnp/spi/Nozzle.java
src/main/java/org/openpnp/util/SimpleGraph.java

This PR adds advanced methods of part-on/part-off vacuum testing to OpenPNP, while keeping the previous simple functionality available. 
1. Easier setup with Measurement Method combo box. Detection can be switched off without having to overwrite your values.
2. The method combo box controls the visible fields in the Wizard, so it can be easy or it can be advanced, as users like it. 
3. New "Difference" method allows you to specify the permissible _change_ in the vacuum level, in addition to the absolute level.
4. Therefore, much finer nuances in changes of the vacuum level can be discriminated, which is essential for the very small nozzle tips with high air flow resistance and/or strong pumps and/or vacuum reservoir systems and/or multi-nozzle systems with crosstalk.
6. The vacuum level …

Feature/Advanced Vacuum Checks

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

https://github.com/openpnp/openpnp/issues/944
Added a function that perform a scaling transform to axes in the GcodeDriver. The axis will move less or more depending on scale factor and report to machine.
This is used on machines that don't directly support the length and angle units given by OpenPnP.
Add the property "scale-factor" to GCode part of machine.xml.
<transform class="org.openpnp.machine.reference.driver.GcodeDriver$ScalingTransform" scale-factor="0.1"/>
Maven test completed successfully. 
Tested on hardware (Siemens MS-90) with X and Y scale-factor beeng -100 and rotation scale-factor beeing -11.
Tested configuring to scaleFactor = 0. There will be a log entry and factor changes to 1.0.
Default factor is …

Added ScalingTransform according to feature request 944

---

src/main/java/org/openpnp/spi/base/AbstractCamera.java

Added the Script Trigger `Camera.AfterSettle` as a counterpart to `Camera.BeforeSettle`. So you can properly switch off LED lights after the settle and final capture. 
**EDIT: Autosettling +** Scripted LED lighting doesn't work in OpenPnP 2.0, it seems. 
See
https://groups.google.com/d/msg/openpnp/jnvon8elGzI/tovchONrAAAJ
EDIT: If you use the FixedTime methode (positive Settle Time in the previous version) there is a Thread.sleep() that will make sure there is no unlit frame in the buffer, so this does not happen. During the Thread.sleep there is also no call to `capture()`, so no AfterCapture script can turn the LED back off.
However, if you use Autosettle (negative Settle Time in the previous version) there is a loop of `capture()` calls, each of which turns the LED back off by …

Feature/New Script Trigger Camera.AfterSettle added.

---

src/main/java/org/openpnp/machine/marek/MarekNozzle.java
src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/reference/ReferenceActuator.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/ReferenceDriver.java
src/main/java/org/openpnp/machine/reference/ReferenceHead.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/NullDriver.java
src/main/java/org/openpnp/spi/Movable.java
src/main/java/org/openpnp/spi/base/AbstractActuator.java
src/main/java/org/openpnp/spi/base/AbstractCamera.java
src/test/java/BasicJobTest.java
src/test/java/VisionUtilsTest.java
src/test/java/org/openpnp/machine/reference/driver/test/TestDriver.java

The moveTo() command in the Movable-interface (and all classes implementing it) now accepts optional flags, that are described in the enum "MoveToOption".
In the GcodeDriver these options are evaluated.
This allows other functions selectively to disable certain features, that usually improves the movement quality, but might not suitable in this situation.
Examples:
- backslash compensation can create mechanical stress during nozzle change (pressing into the nozzle tip holder)
- small movements without the need for precision are way slower with backslash compensation. (e.g. "stirring in a heap feeder)
only used by developers.
Tested it in the simulator. Larger tests following with the HeapFeeder …

Added(optional) option-flags to the moveTo command.

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java

This is a bugfix for my own #991. 
The new `methodPartOn` and `methodPartOff` properties are initialized to `null` so we can recognize an upgrade and properly migrate the method in the @Commit handler. But when a brand new NozzleTip is created, the `@Commit` method is not called (I was somehow convinced otherwise). So I need to initialize a null method, when it is first accessed.
Bug.
Create a new NozzleTip.
1. Tested by creating a new NozzleTip before/after bugfix.

Fix/NozzleTip Part-On/Part-Off Method Initialize

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

This change forces the GcodeDriver sendCommand to flush the response queue before sending a new command to the controller.  In some cases, prior responses could be queued up and be erroneously interpreted as command completions before the command was actually completed by the controller causing bad things to happen (see the discussion at https://groups.google.com/forum/#!topic/openpnp/Hqo05GerezE).  The Homing regex and Move regex waiting loops were updated to call sendCommandNoFlush which doesn't flush the queue so that responses that the loops are waiting for do not get flushed.  Checking was also added to both loops to throw an exception in the event of a controller error.
This change also fixes backlash compensation that was broken by PR 998 which accidentally set all axis backlash …

Flush response buffer before sending a command and fix backlash comp

---

src/main/java/org/openpnp/gui/wizards/CameraVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipPartDetectionWizard.java

Bugfix of my own #995 and #991. 
Used the wrong event handler to get combo box `selectedItem` and checkbox `selected` changes in Wizards. It seems the change of these "properties" are not deemed "property changes" in Java Swing but "item state changes" (the documentation is so abstract, it is useless). 
The wrong events still worked on Windows, due to side effects. Those helpful side effects seem not present on other plattforms/looks & feels. 
Also cleaned up superfluous imports from before.
Bugfix.
See also:
https://groups.google.com/d/msg/openpnp/hP4PdTdvjgo/kz3vSg1FAgAJ
In the Camera Vision Wizard change the Method combo box and/or the Diagnostics checkbox. The visible Wizard dialog elements should adapt to the choice.
In the Nozzle Tip Part Detection Wizard change one of the …

Bugfix/Wrong event handler for ComboBox/Checkbox changes.

---

src/main/java/org/openpnp/gui/components/CameraView.java

This lacks information about the board rotation, but as uses generally try to XY align their boards it might still be an improvement. Could also be changed to snapping to 15° angles
Snaps the visible camera jogging button when holding down the ALT button.
I saw the youtube video about the visual jogging and saw Jason struggling with getting the angle right
Use visual jogging and hold down the ALT button. The rotation will snap into multiples of 45°
@vonnieda Feel free to reject. I know that the camera lacks knowledge of the real orientation of the board, but as most machines mount the PCB in some axis aligned fashion this still seems as an improvement to me

Snap the camera jogging angle when holding down the ALT button

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/support/AbstractConfigurationWizard.java

When a feeder property is dirty, changing the selected feeder by clicking on the list causes
a dialog ( "loose changes" or "cancel")
Changed behaviour to "xxx has changed. Apply changes? Yes / no / cancel"
Much faster than doing "no", then "apply" then reclick on listview.
Change a value in feeder's inspector, click in feeders' listview and see the magic.
trivial test.
Yes
No
4. Be sure to run …

Apply in feeder dialog

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

Fixes bug #1017 where ACTUATOR_READ_WITH_DOUBLE_COMMAND fails for sub-drivers.
1. How did you test the change? Be descriptive. Untested code will not be accepted. Tested on live machine.
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. n/a
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.  All tests passed

Fix for bug #1017

---

src/main/java/org/openpnp/gui/importer/KicadPosImporter.java
src/main/java/org/openpnp/gui/importer/KicadPosImporterDialog.java

Until now importing a kicad.pos file you had the choice between importing only the positions or import the positions, assign existing parts and if parts does not exist automatically create a new part.
This change allows (default on) assigning only existing parts.
I think the use case where only existing parts should be imported is not so uncommon.
Just import the .pos file.
If automatic assignment is not wanted, uncheck the checkbox in the import dialog.
Other check-boxes work unchanged.
1. How did you test the change? Unittest and existing .pos
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for …

allow auto assign known parts

---

pom.xml
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/camera/GstreamerCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/GstreamerCameraConfigurationWizard.java

This camera uses a textbox to specify an
arbitrary gstreamer launch pipeline.
Ann appsink is appended to this pipeline and
samples are pulled and fed to openPnP.
The pipeline should end with an explicit capsfilter element.
------
Adds GstreamerCamera class, based on ReferenceCamera class which allows use of
an arbitrary gstreamer pipeline as a video source. This can be for example a v4l2src,
nvarguscamerasrc, rpicamsrc, rtsp receiver and decoder, media file reader and playbin, etc., etc.
Other camera sources are available which can read from v4l2 devices, perhaps even using
gstreamer to do so, however the pipelines used are fixed by the libraries. Although many
offer good controls, none allow arbitrary gstreamer sources to be used. This rules out their
use where a specific, non-standard …

Add Gstreamer Camera

---

src/main/java/org/openpnp/util/OpenCvUtils.java
src/main/java/org/openpnp/vision/pipeline/stages/CreateFootprintTemplateImage.java

The `CreateFootprintTemplateImage` pipeline stage was refactored to extract the actual template image creation into a generic method of `OpenCvUtils`. Both the stage and the method were enhanced with new parameters and features.
The footprint image can now be colored to allow for full color template matching in difficult low contrast situations and for inverted (black on white) fiducials etc. 
The stage was also enhanced to allow creating part templates as seen both from above and below and including the part body.
On the group users repeatedly asked for ways to recognize fiducials that have different colors and/or are negated (dark on bright). 
See also:
https://groups.google.com/g/openpnp/c/in0uHToytPo/m/fjw1fV_wBgAJ
The refactored method will be used in the upcoming "global axes" PR, …

Feature / Enhanced Footprint Template Image Creation

---

src/main/java/org/openpnp/gui/MachineSetupPanel.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OpenPnpCaptureCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceDragFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceLeverFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/vision/OpenCvVisionProvider.java
src/main/java/org/openpnp/spi/Camera.java
src/main/java/org/openpnp/vision/pipeline/stages/DrawTemplateMatches.java
src/test/java/SampleJobTest.java
src/test/java/VisionUtilsTest.java

In the course of developing and testing the upcoming "Global Axes" PR, I found some bugs and cleaned up some code. These are now broken out in this PR to reduce the size of the upcoming PR.
When changing objects in the Machine Setup Panel, the currently opened Wizard Tab is re-selected if the new object has the same class. Due to some race condition, if you click around quickly, this sometimes throws an index out of bounds exception, leaving the Panel in a half crashed way, with redraw issues, permanently. There were various reports in the group, etc.. 
This is fixed and enhanced in this PR: The Panel now remembers which Wizard Tab is selected for which class. Changing between objects will reliably re-select the tab. As it is stored per class, it will now remember the tab even if you …

Fix / Various assorted bugfixes broken out

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

Reword to avoid common case of "error: error:" appearing in the dialog.
Cosmetic change to gcode error dialog text
Avoids confusing "error: error:" text when ERROR_REGEX begins with "error:"
N/A
String constant change only.

Tweak error response exception message.

---

src/main/java/org/openpnp/machine/reference/driver/ReferenceDriverCommunications.java
src/main/java/org/openpnp/machine/reference/driver/SerialPortCommunications.java
src/main/java/org/openpnp/machine/reference/driver/TcpCommunications.java

Factorize serial and tcp serial communication using primitive read/write functions
writeLine and readLine are duplicated code which can be factorized using simple abstract read and writeBytes function.
Tested over a simple query/reply protocol

Factorize Communication code

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleToolChangerWizard.java

For machines that have no automatic nozzle tip changer, one can disable the automatic changer on the nozzle:
OpenPnP will then only use the **Last Location** of the Nozzle Tip Tool Changer setup. A user can just capture a location that is convenient to manually load/unload Nozzle Tips:
This PR improves the usability by naming the nozzle and nozzle tip in the messages. Furthermore, the nozzle is now moved to the **Last Location** and the message shown for _both_ the unload _and_ the load operation (formerly only unload):
This now also works, if no nozzle tip was loaded to begin with. 
When these Messages are shown, the current Job or GUI action is aborted. The user needs to resume the Job or re-execute the GUI action (this in itself is not new). However, because the unload / load now shows …

Feature / Better manual Nozzle Tip Change

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/reference/HttpActuator.java
src/main/java/org/openpnp/machine/reference/ReferenceActuator.java
src/main/java/org/openpnp/machine/reference/ScriptActuator.java
src/main/java/org/openpnp/machine/reference/axis/wizards/ReferenceControllerAxisConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/driver/GcodeAsyncDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/NullDriver.java
src/main/java/org/openpnp/machine/reference/driver/ReferenceAdvancedMotionPlanner.java
src/main/java/org/openpnp/model/Motion.java
src/main/java/org/openpnp/spi/Driver.java
src/main/java/org/openpnp/spi/MotionPlanner.java
src/main/java/org/openpnp/spi/base/AbstractActuator.java
src/test/java/org/openpnp/machine/reference/driver/test/TestDriver.java

These are some refinements and bugfixes for #1061, #1065.
* Extensive tests on the machine.
* Contact Z-Probing remodeled for custom Gcode M114 or GcodeAsyncDriver's reported Locations
* Bug-fix in interpolation when special interval snapping would exactly match the next interval.
* Correct graphical rendition of "dithering" in motion interpolation, i.e. when one axis is moving so little that some of its interpolation steps collapse to zero. See the discussion [in Section "Interpolation Step Feed-rate Issue" in the blog](https://makr.zone/smoothieware-new-firmware-for-pnp/500/). 
Best possible testing version. ;-)
Download the testing version
- https://openpnp.org/test-downloads/
Follow the instructions of the Wiki documentation:
- …

Feature/Advanced Motion Control  - Update 2

---

src/main/java/org/openpnp/gui/components/SimpleGraphView.java
src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/machine/reference/driver/GcodeAsyncDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/driver/ReferenceAdvancedMotionPlanner.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeAsyncDriverSettings.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverSettings.java
src/main/java/org/openpnp/machine/reference/driver/wizards/ReferenceAdvancedMotionPlannerConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/driver/wizards/ReferenceAdvancedMotionPlannerDiagnosticsWizard.java
src/main/java/org/openpnp/model/AbstractMotionPath.java
src/main/java/org/openpnp/model/Motion.java
src/main/java/org/openpnp/util/SimpleGraph.java

This is a further update of #1061, #1065, #1066, #1071, #1072.
Changes:
* A Test Motion will now always be diagnosed as a whole, even if interlock happens across multiple drivers (diagnostics spans multiple motion plans).
* You can click the Motion Planner Diagnostics graph to cycle through visibility of planned, interpolated or both graphs.
* Motion Planner Diagnostics graph has better anti-aliasing and transparency rendering.
* Added Enabled and Safe Z option to the Test Motion. Displays CAUTION labels when Safe Z is disabled.
* Test Motion now slowly moves to Safe Z after test. 
* Make location confirmation optional in GcodeAsyncDriver. Alternatively use confirmation flow control (waiting for "ok") and wait for the last command confirmation for drivers without axes. Instructions linked …

Feature / Advanced Motion Control - Update 5

---

src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/camera/MjpgCaptureCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/MjpgCaptureCameraWizard.java

This pull request adds MjpgCaptureCamera and MjpgCaptureCameraWizard to OpenPNP.  This class allows you to use IP cameras which output Mjpg streams.
My pick and place machine is using an Mjpg camera for its up camera and this feature should be generally useful for anyone who wants to use one of these cameras.  
In the machine configuration GUI you can add an MjpgCaptureCamera anywhere that you are able to use any other type of camera (e.g. OpenPnpCaptureCamera, OpenCvCamera, etc)
There is currently only one setting which is the IP address and port number to pull the MJPG stream from:
1. I have tested the code on my pick and place machine which uses a this type of camera.  I tested editing pipelines on this camera type as well as simply viewing the stream in the OpenPnP gui
2. I used the …

Mjpg camera feature

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

This feature tells the user how many of a the currently selected part are used by the currently loaded job.  It is useful because with strip feeders you need to pull back the tape to uncover enough parts for the job to complete and it can be tedious to go back and forth between panes to add this information up.
It saves me a lot of time for people using strip feeders.
See the attached image, next to the part selection combo box, OpenPNP will tell you how many parts are used.
1. How did you test the change?  - I added a new label to the wizard and a function to update the label based on the part selected.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?  Yes
3. No changes to the model were needed.
4. mvn test completes with no …

Implemented part count display on the ReferenceStripFeederConfigurationWizard

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/AbstractReferenceFeederConfigurationWizard.java

Added more lines on parts combo boxes.
It's easier to select with a bigger list.
open a job or a leverFeeder
open the part combobox.
I would have been pleased to use a constant but I did not find any clue on where to put it.

set list length of combo boxes to 20 items.

---

src/main/java/org/openpnp/machine/reference/camera/MjpgCaptureCamera.java

MjpgCaptureCamera was missing a line of code to implement image transforms.  I discovered this while testing my mjpg up camera which is rotated 90 degrees on my table.
This code change is required for the image transform options in the camera setup to work correctly.
To reproduce the bug simply try to use any of the image transform options on mjpg camera.
1. I have an up camera on my pnp which is rotated 90 degrees.  After fixing the bug I tested the various options on the transform tab.
2. This code follows the coding style
3. No changes were made to the model
4. mvn test runs with no errors.

MjpgCaptureCamera was missing image transform support.  Added the missing code

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

Updates my recent changes to ReferenceStripFeederWizard to use nicer loop syntax and fix a bug where the part count did not update correctly when the part combo box is changed.
Syntax change was suggested by mark and this code fixes an inconsistency in the UI.
ReferenceStripFeederWizard displays the number of parts used by the currently loaded job next to the part combo box.
1. Tested by interacting with some reference strip feeders and a test board.  Changing the part in each feeder correctly updates the count.
2. This code follows the coding style.
3. There are no model changes.
4. mvn test passes with no errors

Improved loop syntax, fixed code to update the part info whenever the part combo is changed

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/model/Solutions.java

This is Update 7 of the [`advanced-motion-control`](https://github.com/openpnp/openpnp/issues?q=label%3Aadvanced-motion-control) series.
This is intended to be the last PR in the `testing` branch.
- Bug-fix: Rotation coordinates (angles) must not be length unit converted to/from driver units in the GcodeDriver. 
- The homing command for TinyG must name the axes to be homed (Gcode suggested by Issues & Solutions).
- Cosmetic color change in Issues & Solutions. "Fundamental" issues are now blue rather than scary red. They are _important_ and _fundamental_ but they should not be _alarming_ in any way. 
See also:
https://groups.google.com/g/openpnp/c/ObzQGzK5HW0/m/NgM3ahU0AwAJ
- [General Advanced Motion Control documentation keeps getting linked …

Feature / Advanced Motion Control - Update 7

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java

Fixes issue #755 which was caused by a divide by zero when the user incorrectly configures a strip feeder.
Fixes a bug
No change in usage of ReferenceStripFeeder
1. I configured a strip feeder with holes very close together (less than one partPitch distance) and the new code uses the user-supplied part pitch rather than using a computed "adjustedPartPitch".  This spaces the pick locations along a vector in the direction between the two supplied points.  I also configured a feeder with two holes exactly on top of each other and in this case, all pick locations will be computed as the same as pick location zero.  In all cases "reasonable" behavior for an incorrectly configured feeder.
2. The code follows the standard
3. No model changes
4. mvn test passes with no issues

Fix for issue 755 "ReferenceStripFeeder Breaks When Part Pitch > Hole to Hole Distance"

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceSlotAutoFeederConfigurationWizard.java

The ReferenceAutoFeederCongiruationWizard used dropdowns for actuators and even had a "test" button for the ReferenceAutoFeeder. I noticed the ReferenceSlotAutoFeeder had text fields for the actuators and no test buttons. I replicated the functionality from the auto feeder wizard into the slot auto feeder wizard.
I am a little worried about the amount of duplication between those two classes, but it liked like there was a lot of existing duplication so I did not try and refactor it.
This makes it much easier to configure your actuators when using the ReferenceSlotAutoFeeder. You're far less likely to get it wrong when you can just select from a list instead of trying to copy it into a field exactly.
Steps:
1. In the "Machine Setup" tab, select the "Actuators" label and click the green …

Closes #1005: Replace actuator text field with combobox

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/JobPanel.java

Description
A feeder in feeder's list is grayed out if no active placement uses it.
Justification
I have 30 feeders on my machine, all full.
When I start a new job, I need to add new parts. Therefore, I need to empty one feeder and of course one that will not
be used by the new job. Today there's no fast way to find unused feeders.
Instructions for Use
Open new session.
go to feeders panels, there are all grayed out.
open a job -> feeders that are in used by the job are white.
Check uncheck placements / boardslocation, see the result in feeder's panel
Implementation Details
How did you test the change? Be descriptive. Untested code will not be accepted.
manual gui tests.
Did you follow the coding style?
I think.
If you made changes in …

a feeder in feeder's list is grayed out if no active placement uses it.

---

src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java

to avoid probing with every pick and place command by scripting.
A ContactProbeNozzle probes with every pick an place command. If one will avoid these we can now set a flag by script. If not set the machine behaves as before.
Probing has an impact on speed and can cause errors. Probing with discard devices e.q. makes no sense.
Setup a ContactProbeNozzle for your machine as descriped here in detail https://github.com/openpnp/openpnp/pull/859.
After that the machine will probe with every pick and place command. To avoid these for certain action we can use https://github.com/openpnp/openpnp/wiki/Scripting. Job.BeforeDiscard.js to disable and Job.AfterDiscard.js to enable e.g. with discard devices action. The script could be similar to this example:
Job.BeforeDiscard.js:
// Import some …

Added possibility to disable ContactProbeNozzle actuator temporarily..

---

src/main/java/org/openpnp/spi/base/AbstractCamera.java

This brings back #999 after it got lost in a faulty conflict resolution somewhere in #1086.
NOTE: due to indentation, best [look at the changes ignoring whitespace](https://github.com/openpnp/openpnp/pull/1089/files?diff=unified&w=1).
See the [user group discussion](https://groups.google.com/g/openpnp/c/j4ucK1JuyH0/m/hvmpc2hmBQAJ).
See #999.
1. Assuming original PR tests are conclusive.
2. Original did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
4. Successful run of `mvn test` before submitting the Pull Request.

Fix / Bring back Camera.AfterSettle (lost in merge conflict)

---

src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/machine/reference/ScriptActuator.java
src/main/java/org/openpnp/model/Configuration.java
src/main/java/org/openpnp/scripting/ScriptFileWatcher.java
src/main/java/org/openpnp/scripting/Scripting.java

The Scripting class is used to execute scripts (through a menu item) or execute events (triggered in various places in the code). The Scripting class was also handling copying example scripts over from project resources as well as starting a file watcher which updated a menu in the GUI.
This diff:
- Moves the Scripting class to an org.openpnp.scripting package.
- Refactors the scriptsDirectory to be a parameter passed into the Configuration class.
- Adds a ScriptFileWatcher class in the scripting package that handles copying the example scripts over and handles synchronizing the menu in the GUI application.
This is mostly to clean up the code for testability. We don't have tests relying on scripting (e.g. verifying that events are sent off properly) just yet, but the scripting engine was …

Remove GUI dependencies from Scripting

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

This change adds a 'maxFeedCount' field to ReferenceStripFeeder.  When the feeder's feedCount exceeds 'maxFeedCount' then it will throw an exception indicating that it is out of parts.  The message shown to the user will display the part and feeder name.  If the user leaves 'maxFeedCount' at the default value of zero, this feature will be ignored so we don't force everyone to immediately set maxFeedCount on all of their feeders.
This is a much-needed feature for projects using strip feeders that cannot fit all of a given part into one strip.  For example I have a project which uses 64 leds and there is no way to safely use OpenPNP to populate those parts on my machine because it continues to feed past the end of the strip.
If the user wants to use the new maxFeedCount option on …

Added maxFeedCount feature to ReferenceStripFeeder

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

This adds a few more details to the 'maxFeedCount' feature of ReferenceStripFeeder
- When a feeder feeds its last part, it will automatically disable itself.  This causes OpenPNP to automatically switch to another feeder for that part (if there is one)
- There is a new button for automatically setting the MaxFeedCount based on the configured reference hole locations
This further improves the behavior of ReferenceStripFeeder when you need more parts than will fit in one strip.
If you press the 'Auto Set MaxFeedCount' button, the MaxFeedCount field will be set based on the distance between the reference hole locations you have selected and the pitch of the part.  If you configure multiple strip feeders for a given part and one of them runs out of parts, OpenPNP will automatically start …

Improved "MaxFeedCount" for Reference Strip Feeder

---

src/main/java/org/openpnp/gui/MachineControlsPanel.java

Bug-Fix for #1095 and #1106 : Auto Tool Select must **not** act on HeadMountables that are not actually mounted on a head, such as a bottom camera or machine actuators. Those cannot be moved and are therefore not eligible for the Machine Controls Panel.
See testing report:
https://groups.google.com/g/openpnp/c/nOnmi3PyUbw/m/zprS8tthCwAJ
Please refer to #1095 and #1106.
1. Tested in the Simulation Machine.
3. No further changes in the `org.openpnp.spi` or `org.openpnp.model` packages.

Feature/ Actuator Profiles, Camera Lights -- Round 3

---

src/main/java/org/openpnp/gui/FeedersPanel.java

Fixed a nullpointer exception that occurred opening the feeder tab if a job is loaded, with some parts are not yet assigned.
restore expected behavior
no change
1. How did you test the change? Loaded job that made the problems before, works now.

fix null pointer exception in feeder tab

---

src/main/java/org/openpnp/gui/components/CameraPanel.java
src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/gui/components/CameraViewPopupMenu.java
src/main/java/org/openpnp/gui/processes/EstimateObjectZCoordinateProcess.java
src/main/java/org/openpnp/gui/wizards/CameraConfigurationWizard.java
src/main/java/org/openpnp/spi/Camera.java
src/main/java/org/openpnp/spi/Locatable.java
src/main/java/org/openpnp/spi/base/AbstractCamera.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java
src/test/java/VisionUtilsTest.java

1. Cameras can now be calibrated at two different heights which permits more accurate measurements and camera jogging when the height of an object is known to be at something other than the height at which the camera was calibrated.  When upgrading from earlier versions of OpenPnP, the existing calibration remains in effect until calibration is re-run at two different heights.
2. The camera views are enhanced to allow the operator to adjust the height of the reticle so that it is scaled appropriately for any desired height.  This height is also used to scale camera drag and shift-click jogging so that it is correct for that height.
3. The camera views are enhanced to allow the operator to estimate object heights based on two different perspectives of the object.  This feature is mainly …

Add support for units per pixel calibration at different heights

---

src/main/java/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder.java
src/main/resources/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder-DefaultPipeline.xml
src/main/resources/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder-DefaultTrainingPipeline.xml

Fixed synchronization so that it works with the async gcode driver:
- In the default pipelines made sure the "settle-first" is enabled
- Added explicit synchronization in the code to make sure the next call to the vision pipeline is called after movement finished
Added a safety feature, to make sure the vision pipeline can not "run away" during the location. Ensures the pick location stays inside the camera field of view if the camera is above the feeder location.
fixed bug and added safety feature.
no changes
1. How did you test the change? Pipelines not tested, but tested with own pipelines, works normal again
3. If you made changes in the `org.openpnp.spi` or …

AdvancedLoosePartFeeder: Support for the async gcode driver

---

src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverSettings.java

This adds support for the Duet 3D firmware in Detection and [Issues & Solutions](https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions). The new firmware version 3.3beta now supports all mandatory OpenPnP Advanced Motion Control features. 
Issues & Solutions recognizes the firmware using `M115` and compares major and minor version number to make sure a 3.3 version is at least present. Otherwise, it tells the user to upgrade. 
Firmware detection now also queries the axis configuration, if a Duet controller was detected. Based on this, Issues & Solutions makes sure, rotational axes are configured as linear for feed-rate calculations. Otherwise, it tells the user to use proper configuration using the `M584` `S0` [command option](https://duet3d.dozuki.com/Wiki/Gcode#Section_M584_Set_dri …

Feature/Duet Firmware Detect, Issues and Solutions, Bugfix

---

src/test/java/VisionUtilsTest.java

The change creates the Configuration object before the unit test is executed.
The Unit test would fail if executed alone or before other component tests which create the static configuration object
none
Obvious change.
mvn test works even in directory where unit test is executed first.

Fix VisionUtilsTest by creating a local configuration

---

src/main/java/org/openpnp/machine/reference/HttpActuator.java
src/main/java/org/openpnp/machine/reference/wizards/HttpActuatorConfigurationWizard.java
src/test/java/HttpActuatorTest.java

This change adds a read URL to read values from an http actuator.
I have a small c++ Program on my Rpi which implements a simple http server to actuate GPIO and
read Preassure (and possibly Distance ) sensor via http. The request looks like this:
http://192.168.0.42:8001/msr the response looks like this:
pump:11583
The idea is that the Pattern Matching is used to read then the preasure value.
Sadly the Null Driver has no pattern matching - it is thus not easy to test or should this be part of the HTTP actuator?
The regex to match the result is given in parallel to the URL to read. It's only available for non boolean
actuators.
1. How did you test the change? I can read the value with the read button, which should be the first MVP. …

Add read for http actuator

---

src/main/java/org/openpnp/machine/reference/ReferenceCamera.java

A bug was introduced when I optimized camera transforms to skip image conversion to OpenCv Mat and back when no transforms apply. Unfortunately this also skipped ongoing camera calibration, that was interwoven in the transform steps. 
The bug is now fixed.
I also reordered the predicates to match the order of the transforms to better see if all of them are covered. 
Thanks, @tonyluken, for correctly diagnosing this.
Image calibration no longer works unless you happen to have at least one transformation active. 
See also:
https://groups.google.com/g/openpnp/c/nsY9XU_8hFw/m/XOjhtNq4AAAJ
No change.
1. Performed a calibration on a camera with no transforms. Verified by debugger that optimization still works before/after calibration.  …

Fix / Camera Transforms while Calibrating.

---

src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java
src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/ImageCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/SimulatedUpCameraConfigurationWizard.java

Break-out from ongoing other work: Set the pixel Width and Height on `SimulatedUpCamera` and `ImageCamera` through the GUI.
The resolution of the bottom camera (`SimulatedUpCamera`) was reduced in recent PRs to speed up the lengthy `SampleJobTest`. However, the camera was now too small for large ICs. Rather than permanently increasing the resolution, it is now user settable. Large ICs can now again be rendered:
New Width and Height fields appear on the Device tab of the `SimulatedUpCamera` and `ImageCamera`:
1. Tested with large IC, alignment etc.

Feature/Set Width, Height on SimulatedUpCamera, ImageCamera

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java

Option to check package size during bottom camera part alignment.  Compares measured vs expected dimension with a part configurable tolerance.
Enables optical detection of badly picked parts which are not sitting flat on the nozzle.
1. Set the expected body dimension in the package (for the part) under the vision tab
2. Enable "Check size" checkbox under the Part ReferenceBottomVision tab
3. Adjust size tolerance under the Part ReferenceBottomVision tab.  Default 20%.
Only works when the bottom vision pipeline returns a single rectangle for the whole pacakge.  Is not expected to operate if individual pads are measured.
1. Tested on 0603 with a pick offset for high failure rate.  With a run of 20 parts found every instance of bad pick and rejected no instances of good picks.
One instance …

ReferenceBottomVision - Part size check option for detecting bad part pick

---

src/main/java/org/openpnp/vision/pipeline/stages/OrientRotatedRects.java

Hello,
Some of code that works with pipelines expect unambiguous orientation of oriented rectangle at the end of pipeline.
That are e.g. LoosePartFeeder and FullRotate option. Stage MinAreaRect in fact returns random 1 of 4 angles of
found rectangle. Sometimes it is required for pipeline to output 1 certain angle from those 4. When option SnapToAngle
will be selected, pipeline will return certain angle. This will work more like Align option for bottom vision. 
Where it is needed:
1. LoosePartFeeder - when I place small component that requires Down-looking camera alignmet before pick, and
this component has defined orientation. I can place it with known orientation (e.g. about 0 degrees). Then use Snap
option with SnapAngle set to 0 degree. Pipeline then will output angle in range of -45 …

Implement "Snap" option for OrientRotatedRets

---

src/main/java/org/openpnp/vision/pipeline/stages/CreateFootprintTemplateImage.java

The pipeline stage CreateFootprintTemplate didn't work in bottom vision, since the required attribute "footprint" was not set.
Changed the pipeline, to get the footprint with the attribute "nozzle" that is available.
Allow the generated footprint to be used in pipelines, e.g. using TemplateMatch.
```
<cv-pipeline>
<stages>
<cv-stage class="org.openpnp.vision.pipeline.stages.CreateFootprintTemplateImage" name="7" enabled="true" footprint-view="Fiducial">
<pads-color r="255" g="255" b="255" a="255"/>
<body-color r="0" g="0" b="0" a="255"/>
<background-color r="0" g="0" b="0" a="255"/>
</cv-stage>
<cv-stage class="org.openpnp.vision.pipeline.stages.ConvertColor" name="18" enabled="true" conversion="Bgr2Gray"/>
<cv-stage class="org.openpnp.vision.pipeline.stages.ImageCapture" name="0" …
```

Create footprint template if pipeline stage is used in bottom vision

---

src/main/java/org/openpnp/vision/pipeline/stages/CreateFootprintTemplateImage.java

Added a boolean value to disabling the default border around the part.
The border can make problems in some cases for template matching.  (template is to large => exception)
Just enable the checkbox in the stage settings, and the border disappears.
Warning: only works with symmetrical parts. Parts where the body is not in the center, one side will have border, the other will be cut off.
1. How did you test the change? Be descriptive. Untested code will not be accepted. on my machine with different parts
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages …

CreateFootprintTemplateImage: Allow to create minimal images

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/components/ThemeSettingsPanel.java
src/main/java/org/openpnp/gui/support/CustomBooleanRenderer.java
src/main/java/org/openpnp/gui/support/FlexibleColor.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverSettings.java
src/main/resources/org/openpnp/translations.properties

As the title says...
\+ Added more theme choices
\+ Added the option for the user to install more themes
This was requested by @vonnieda 
More choices are always better.
The user can install 3rd party IntelliJ themes by copying the `*.theme.json` file into the `.openpnp2/themes` directory. This directory is automatically created after the first run.
I checked the visual appearance manually for all themes. I did not touch any non visual code. This should not cause any problems
Yes

Changed table row visuals to alternate colors

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java

Fixed issues in partSizeCheck code found while testing this feature.
I tried the new version of size checking using the parts definition height and width added a few weeks ago.
I tried the partSizeCheck on a 1206 resistor and encountered a few problems.
(1) The partSizeCheck in findOffsetsPreRotate never returns an error even if I intentionally define wrong part size.
I found that a false result from the size check code only causes the "for(int pass = 0;;) " loop to reiterate until
maxVisionPasses is reached. The part is placed even if size check fails. I did not see any code to display an error message.
Also if the center offset or corner offset or angle offset is still to large after maxVisionPasses then partSizeCheck is never even called. 
I added the Exception Message display code …

Fixed issues in PartSizeCheck feature in ReferenceBottomVision

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceRotatedTrayFeeder.java

Just implemented the correct way of rotating a position matrix
to solve issue with the Reference Rotated tray Feeder
https://github.com/openpnp/openpnp/issues/1157
Just use the Reference Rotated tray feeder, now it will move the tool to the correct position even if the rotation is negative angle.
Tested it with a fresh installation of openpnp and used the slanted strips to virtually try out the rotation and feed positions
as far as I know...
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to …

Rotated tray feeder fix

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/gui/tablemodel/PartsTableModel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/model/Length.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/spi/Head.java
src/main/java/org/openpnp/spi/NozzleTip.java
src/main/java/org/openpnp/spi/base/AbstractHead.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java
src/main/java/org/openpnp/util/ImageUtils.java
src/main/java/org/openpnp/util/UiUtils.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java
src/main/java/org/openpnp/vision/pipeline/ui/PipelinePanel.java

This is a round-up of bug-fixes and conceptually missing utility features. These have popped up while working on #1164 (which will likely be re-submitted as a new one later). 
* Bug-fix for #1143 (null pointer exception when part is missing in feeder)
* Parts table does not update on part property changes.
* Inconsistent FIRMWARE detection in `GcodeDriverSolutions`.
* Edit Pipeline does not wait for machine in `ReferencePushPullFeederConfigurationWizard`, resulting in the lighting actuator failing.
* Test Alignment in `ReferenceBottomVisionPartConfigurationWizard` did not conserve rotation of selected nozzle.
* Nozzle tip calibration failed the homing cycle if enabled on homing, creating a chicken egg situation during machine setup. Added an option to switch off. Improved error messages. …

Fix/Round-up of Bug-Fixes and some Missing Utility Features

---

src/main/java/org/openpnp/gui/importer/KicadPosImporter.java

Assume UTF8 encoding when importing a kicad .pos file.
If non-ASCII character like "µ" are used, importing fails. See bug #1176 
No change in the behaviour. Only assumption is, that the file is now in UTF8, and not in an undefined character set.
1. How did you test the change? Tested from the bug reporting person
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. no
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. yes

Kicad importer: Assume UTF8 as charset

---

src/main/java/org/openpnp/gui/FeedersPanel.java

I noticed when working on the IndexFeeder's configuration panel that a PropertySheet has a getPropertySheetPanel method which returns a JPanel. The FeedersPanel always assumes that the return from that method can be cast to AbstractConfigurationWizard which is not 100% true for all tabs in my case. I have a "search" tab that will search for feeders, and therefore doesn't need revert/apply buttons. I decided to return just a raw JPanel which had the effect that my tabs showed up under the machine configuration panel, but not under the feeders tab. This caused an exception in the FeedersPanel class.
I'd say this just cleans up a mismatched interface. Since a developer can return just a JPanel (which I think is the correct behavior for property sheets), making FeedersPanel more intelligently …

Fixes use of JPanel in property sheet in FeedersPanel

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

This keeps the Z coordinate of the two reference hole locations intact through **Auto Setup**.
The bug appears to haven been brought in by adding property change firing here:
https://github.com/openpnp/openpnp/commit/ee7ea6fd1b402c4a9fe6fc7eca180ca5b8004f0b#diff-b348cb0fe5f0f395b42e79116b72ea0253f5343f07f653fd186850362bc83f25
Which is benign, of course. But Auto-Setup uses mixed direct model _and_ Wizard controls modifications here (see the `invokeLater`):
https://github.com/openpnp/openpnp/blob/e4f983f76f716593b7fedf72c9b75c68c9c95fc5/src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java#L608-L629
... which in earlier versions caused overwriting the zeroed Z with the old coordinate when Apply was pressed. Today the property change firing …

Fix/Keep the Z in ReferenceStripFeederConfigurationWizard Auto Setup.

---

pom.xml

Based on the conversation in #1189, removing the parameter to write output to a file.

Test output doesn't go to files anymore

---

src/main/java/org/openpnp/gui/MachineSetupPanel.java
src/main/java/org/openpnp/spi/base/AbstractControllerAxis.java
src/main/java/org/openpnp/spi/base/AbstractCoordinateAxis.java

Users reported sporadic GUI related exception. The issue was traced back to mullti-threading. 
`AbstractCoordinateAxis.setCoordinate(double)` and `AbstractControllerAxis.setDriverCoordinate(double)` must not `firePropertyChange()` as these changes are live from the machine thread. Coordinate changes must instead be handled through `MachineListener.machineHeadActivity(Machine, Head)`. 
A search revealed that these property names are not used in the source. These were introduced by me, copying the pattern over from other (GUI visible) properties on the axis, purely for completeness. 
Bug-fix.
See user case:
https://groups.google.com/g/openpnp/c/ULaw9j_t8-k/m/AvAd1iWSAgAJ
No visible changes.
1. Tested with extended simulation machine. …

Fix/Axis must not fire live Coordinate Property Changes

---

src/main/java/org/openpnp/gui/FeedersPanel.java

For the configuration wizard property sheet wrapper, it'd return the same instance every time getPropertySheetPanel was called. However, in my case, I was returning "new X" every time which was causing some really strange behavior because one instance had all the bindings and the other was what was displayed on the screen.

Fixed duplicate property panel creation in some circumstances

---

src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java

This adds a new **Test Placement Angle** field to the **Test Aligment** function in the  ReferenceBottomVision Wizard.
If you leave it at 0° the behavior is now again the same as before #1169.
Originally, Test Alignment could only test the Alignment for a fixed 0° placement angle. Then #1169 changed it to take the current nozzle angle as the nominal placement angle. But it turns out to be a bad user experience, especially if you align multiple times. Because the alignment offset is adjusted on the nozzle rotation, it is taken as the new "nominal" angle and the error is (seemingly) multiplied.
See also:
https://github.com/openpnp/openpnp/pull/1169#issuecomment-848406808
Just enter the **Test Placement Angle** in the field and press **Test Aligment**. 
Note: when **Center After Test** is …

Feature/Placement Angle for Test Alignment

---

src/main/java/org/openpnp/gui/components/LocationButtonsPanel.java

If the text field for a location is empty, it'll return a null value when you parse the length. This fixes that.
See Description
This should have no impact the user has to worry about. It essentially treats an empty text field as a 0 for the location.
Manual testing.
Yes
Nope, just the GUI.
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull …

Fixing empty location in location buttons panel

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java

The [Issues & Solutions](https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions) `HOME_COMMAND` suggested for TinyG should only include/home axes XYZ, not ABC.
TinyG will issue an error if an axis named is not configured for end-stop homing. 
The `HOME_COMMAND` is suggested by Issues & Solutions, when it is not yet set i.e. an existing `HOME_COMMAND` will **not** be overwritten, therefore this fix will only be effective... 
1. For a fresh configuration.
2. After the user manually deleted (emptied) the `HOME_COMMAND` from the GcodeDriver. 
1. Tested on TinyG rig.
4. Successful `mvn test` before submitting the …

Fix/Issues & Solutions HOME_COMMAND for TinyG: only home axes XYZ, not ABC

---

src/main/java/org/openpnp/gui/support/MutableLocationProxy.java

Simple typo on MutableLocationProxy

MutableLocationProxy: fix firePropertyChange with lengthZ

---

src/main/java/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceLoosePartFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceRotatedTrayFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceTrayFeeder.java

It was wrongfully assumed, that partOff() always works. (Since Simulator and test machine are equipped with vacuum sensor it didn't show during tests). This results in exceptions after recycling the part as on the mailing list reported.
Fixed the behavior to the expected-
No change.
1. How did you test the change? Tested in simulator. No feedback (yet) from the reporter of the problem.
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. no changes, only in the feeders
4. Be sure to run `mvn test` before submitting the Pull …

Bugfix: Only call "partOff" if configured during recyling

---

src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java

This refers to automatic feeder and part height probing using the ContactProbeNozzle, see #1174 and the Wiki:
https://github.com/openpnp/openpnp/wiki/Contact-Probing-Nozzle
Bug: The ContactProbeNozzle persisted height maps with objects as map keys instead of their IDs. 
Plain stupid bug.
If users used the ContactProbeNozzle and have in-deed probed heights on parts and feeders, their `machine.xml` structure is wrong. It will look similar to this:
```XML
<probed-feeder-height-offsets>
<entry>
<feeder class="org.openpnp.machine.reference.feeder.ReferenceTubeFeeder" version="1.1" id="FDR1682b249cd43b798" name="ReferenceTubeFeeder" enabled="false" part-id="TEST-OBJECT" feed-retry-count="3" pick-retry-count="0">
<location units="Millimeters" x="253.39191389757997" y="260.32085144101774" …
```

Fix/ContactProbeNozzle Height Maps must be persisted with IDs, not Objects

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java
src/main/java/org/openpnp/machine/reference/feeder/AdvancedLoosePartFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceLoosePartFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceRotatedTrayFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceTrayFeeder.java

* For the part on nozzle recycling feature, use the `Nozzle.moveToPickLocation()` method instead of `MovableUtils.moveToLocationAtSafeZ()`
* Fixed button/action enabling inconsistency bug.
* Fixed `BlindsFeeder` recycling logic error. 
* Fixed a `SimulatedUpCamera` race condition.
This bug is due to @doppelgrau and myself having developed two features #1143/#1174 in parallel, i.e. my refactoring did not cover @doppelgrau's work that was not yet merged at the time. 
I was introducing the `Nozzle.moveToPickLocation(Feeder)` and `Nozzle.moveToPlacementLocation(Location, Part)` methods that should now always be used instead of the generic `MovableUtils.moveToLocationAtSafeZ()`. 
Why? This is done to support on-the-fly contact probing when you have a `ContactProbeNozzle`. So if the feeder …

Fix/Part Recycling Feature should use Nozzle.moveToPickLocation()

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectCircularSymmetry.java

The DetectCircularSymmetry vision stage has been enhanced:
* Now supports sub-pixel accuracy detection.
* Added optional multi-target support.
* Added support for ReferenceStripFeeder 
* Added support for ReferencePushPullFeeder
* Fixed bug in ReferenceNozzleTipCalibration pipeline property.
The sub-pixel accuracy is needed for upcoming automatic [Backlash Compensation](https://github.com/openpnp/openpnp/wiki/Backlash-Compensation) offset calibration.
Multi-target support allows the use of the stage where multiple sprocket holes etc. need to be detected. Now supports ReferenceStripFeeder and ReferencePushPullFeeder.
For basic operation see the [Wiki page](https://github.com/openpnp/openpnp/wiki/DetectCircularSymmetry).
The stage has these new properties:
- **maxTargetCount**: Maximum …

Feature/Enhanced DetectCircularSymmetry Stage

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/spi/MotionPlanner.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java

When manual nozzle tip change is enabled, the user is prompted to load/unload a nozzle tip when needed. This is done by throwing an Exception, interrupting the current machine task and ultimately resulting in a message box being displayed: 
Bug: When the advanced motion planner is enabled, the move to the manual change location might only be queued and not yet be executed when the Exception is thrown. Instead, the motion commands remained in the queue and would unexpectedly be executed later. 
This PR fixes both problems: 
1. It waits for motion to complete, before throwing the Exception.
2. It clears queued commands from the planner, when the machine task/executor is aborted. Otherwise, these could unexpectedly be executed in the context of the next task.
Note: the second problem is more …

Fix/Manual Nozzle Tip Change Motion

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/spi/MotionPlanner.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java

In #1216 I introduced a new exception behavior that turns out faulty:
In case of an exception, the pending moves were cleared, but OpenPnP's advanced planner then still thought it is (planned to be) at the target position of these queued moves. So if it for instance thinks it is already at Safe Z, it will later not issue new move commands to go there, even if the machine is still down in Z. 
Before this latest change, the pending moves were retained in the queue _through_ any exception and then (unexpectedly!) executed when the next move (such as a jog by the user) was executed.
This PR changes it to the behavior that is present with the NullPlanner (older OpenPnP) i.e. before continuous/asynchronous execution of motion was introduced: Even in case of an exception the pending moves should …

Fix / Pending Motion must be executed even after Exception

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/BlindsFeederConfigurationWizard.java
src/test/java/BlindsFeederTest.java

Named group option for BlindsFeeder which acts in addition to fiducial location to determine connected feeders.
If multiple tiles of Blindfeeders are used in the same physical location for different jobs/builds the feeders configuration will be confused.
This benefits everyone using BlindsFeeders a significant amount.  Default behavior is by location.
- In the BlindsFeeder tape settings there is a new editable combo box. Either choose an existing group name or enter a new one to override location based grouping.
- Leave the group name as "Default" to get the normal location based behavior.
- Entering an existing group name for a feeder with default fiducial locations or a feeder with no other connected feeders will join it to that group and give it the correct fiducials.
- Each group name …

Feature/blinds feeder named group 

---

src/main/java/org/openpnp/model/Motion.java

Fixes a small bug where an axis linked to a driver with limited capabilities would degrade the whole motion, even if that axis (and therefore the driver) was not part of the motion.
The driver may for instance have the **ToolpathFeedRate** Motion Control Type, which will degrade motion control, as only the feed-rate limit is set. The minimum "useful" Motion Control Type is **EuclideanAxisLimits**. 
See also:
https://github.com/openpnp/openpnp/wiki/GcodeAsyncDriver#gcodedriver-new-settings
See bug report and discussion here:
https://groups.google.com/g/openpnp/c/uueGw-eweYM/m/X1xgDeRbBQAJ
No change.
1. Tested with user's machine.xml in simulation. Reproduced the bug and then confirmed the fix was working.  …

Fix / Avoid Degradation of Motion when limiting Axis is absent

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java

* Better error diagnostics for **Allow Pre-Move-Command** enabled drivers.
* More tolerant M115 firmware detection REGEX.
See 
https://groups.google.com/g/openpnp/c/WxDSbj5KkGw/m/V-tjvT6pAQAJ
Configurations errors will be (better) reported:
See also the Wiki about **Allow Pre-Move-Command**:
https://github.com/openpnp/openpnp/wiki/GcodeAsyncDriver#gcodedriver-new-settings

Fix/Better GcodeDriver Configuration Error Diagnostics

---

src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java

Apparently, on some systems, the components to tab index mapping is unreliable. This round-two-fix tries to circumvent that by comparing the tab title text (idea by @vonnieda).
See #1199
No change
4. No sense running `mvn test` before submitting the Pull Request.

Fix / Issues & Solutions Tab Title Snafu

---

src/main/java/org/openpnp/gui/FeedersPanel.java

Bugfix: FeedersPanel should not refuse moving the camera to the pick location if the wrong nozzle tip is loaded. 
The bug was brought in by #1174.
See also 
https://groups.google.com/g/openpnp/c/-aEEO821wGo/m/N0lOog87AAAJ
No change.
1. Tested on machine, inside #1220.
4. Successfully ran `mvn test`.

Fix / FeedersPanel Move to Pick Location should not require compatible Nozzle Tip

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/ContactProbeNozzleWizard.java
src/main/java/org/openpnp/spi/JobProcessor.java
src/main/java/org/openpnp/spi/base/AbstractPnpJobProcessor.java
src/main/java/org/openpnp/util/Cycles.java

Fixed null pointer bug for discard placement. Discarding is signalled by passing `part` as `null`. 
- The `NullPointerException` was brought in by #1205 (by accessing the null part id). Fixed.
- Added new option for the ContactProbeNozzle to probe on discard. The part can be brushed/tilted away from the nozzle. Probing will make sure there is no undue pressure even with an unknown part-on-nozzle state (i.e. including when picked badly, tomb-stoned, shifted etc.). On my machine, I'm using soft material to brush parts away from the nozzle (just switching off the valve does not reliably drop 0402 parts). 
- The empty MessageBox on exceptions that have no message is fixed. 
- A ContactProbeNozzle Issues&Solutions bug was fixed: when the firmware was unknown (neither Smoothieware, nor TinyG, …

Fix/Discard Contact Probing

---

src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java

The null part must not apply dynamic Safe Z (obviously). 
This bug was brought in by #1223, mistakenly thinking the null case can be generalized inside the helper method `getSafePartHeight()`. This has been reverted. 
Instead, ContactProbeNozzle must handle the null part case (for discard probing) specifically. 
See  
https://groups.google.com/g/openpnp/c/Y20VM7QZd9U/m/iDQLEHrfAAAJ
No change.
1. Tested in simulation (#1223 test regime).

Fix / Regression in null Part handling on Dynamic Safe Z

---

src/main/java/org/openpnp/util/GcodeServer.java

Let the GcodeServer ignore `$` commands (except `$H`), so the typical TinyG setup chatter is ignored. 
So I can test a TinyG user `machine.xml` against the GcodeServer controller simulator.
Like always, set **Communications Type** to **tcp** and assign `GcodeServer` as the IP Address:
You likely need to change the `COMMAND_CONFIRM_REGEX` to the standard, as the TinyG has a quirky one: 
Then you are ready to test with a TinyG `machine.xml`.
1. Tested as described in the Instruction for Use (above). Also tested if `$H` still works as a homing command. 

Fix / GcodeServer should ignore $ Commands

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceHeapFeeder.java

* Make setting and getting vacuum actuators a public interface of ReferenceNozzle.
* In return, setting, getting, resolving actuators by name should be avoided outside the Nozzle (fixed in ReferenceHeapFeeder.java)
* This also improves diagnostics (Exceptions) when the actuator is not found (by name) vs. when it simply is not set. The nozzle is named in the second error message, so users know where to fix it.
* A minor migration error was fixed (Valve actuator was suggested to be of Double type when in fact it is Boolean).
* PartOff/PartOn enabling was mistakenly depending on the presence of the _valve_ actuator instead of the _sensing_ actuator. 
This is a general move towards encapsulating the actuators' referencing by name. More specifically, it is in preparation for some actuator …

Cleanup / Setting and Getting Nozzle Vacuum Actuators

---

.github/workflows/build_and_deploy.yml

Update Install4J version to fix RPM package, fixes #1229 
Due to a regression, Install4J version 8 doesn't work on Fedora 33 and 34. This PR makes it work, making it possible for Fedora users to use the RPM package.
No changes to the workflow or installation procedure.
1. How did you test the change? 
I've made the change and allowed the scripts to run on my fork and created a Install4J trial license key to test and I have confirmed it works by installing it on my machine (Fedora 34).
The only thing which my edit diverts from what was done is that it is using Install4J servers and not the privately owned AWS service that @vonnieda seems to have.
3. If you made changes in the …

Update Install4J to 9.0.4 to make Fedora compatible

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java

Fixes a bug in the heuristic feeder parts similarity comparison function. Instead of comparing the similarity in part pitch with feeder1 and feeder2 respectively, it compared similarity with feeder1 and similarity with itself (always equal).
Not surprisingly, this created a 
`java.lang.IllegalArgumentException: Comparison method violates its general contract!`
as soon as the more important properties (tape spec, package, template status) were all equal, but part pitch was different.
See https://groups.google.com/g/openpnp/c/VDEKlvYKfTY/m/h3qBvl4GAwAJ
Same as before.
1. Cognitive test (see source code change).
4. …

Fix / Bug in Similarity Comparison Function

---

src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/reference/HttpActuator.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ScriptActuator.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceHeapFeeder.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleVacuumWizard.java
src/main/java/org/openpnp/spi/Actuator.java
src/main/java/org/openpnp/spi/Machine.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java
src/test/java/ReferenceJobProcessorRetryTests.java

* The ReferenceNozzle now stores Actuator object references internally, names are only used for persistence.
* Therefore, changing an actuator name no longer breaks the reference.
* Nozzle actuator setters/getters by name were removed. Code accessing these was refactored.
* The ReferenceNozzleVacuumWizard was reworked to use references instead of names.
* Bonus: The Nozzle adds simple reminders to Issues & Solutions, when vacuum actuators, assigned drivers, and/or their G-code command and/or regex are missing.
* `org.openpnp.spi.Actuator.isDriverless()` was added to declare when an Actuator does not need a driver. `HttpActuator` and `ScriptActuator` are ok to be driverless even though they are derived from `ReferenceActuator` which _needs_ a driver (the distinction is required for Issues …

Feature / Nozzle Vacuum Actuators by Reference, not by Name (Round 2)

---

src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectCircularSymmetry.java

Improves the DetectCircularSymmetry stage to support cropped search ranges. 
It automatically crops the search range to the image edges. Note, the area analyzed for circular symmetry must still fully be inside the image, that's why the search area indicated by the reddish heat map still has a margin to the edge (half of **maxDiameter**): 
If the nominal target location is close to the edge of the image, the search range can become asymmetric:
A search width and height can now also (optionally) be specified, in addition to the circular maximum search range (this is not yet employed/implemented in the feeder classes):
The PR also improves diagnostic heat-map and cross-hairs. The indicated circle hugs the circumference very precisely. Observe how asymmetries in the [Bresenham …

Feature / Better DetectCircularSymmetry Search Ranges

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/gui/components/SimpleGraphView.java
src/main/java/org/openpnp/gui/components/TemplateImageControl.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/axis/wizards/AbstractAxisConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/AutoFocusProvider.java
src/main/java/org/openpnp/machine/reference/camera/wizards/AutoFocusProviderConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/SimulationModeMachineConfigurationWizard.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/util/SimpleGraph.java
src/main/java/org/openpnp/util/UiUtils.java
src/main/java/org/openpnp/util/Utils2D.java

Round-up of UI and Utils improvements and some minor bug-fixes:
* `CameraView` now uses bi-cubic instead of only bi-linear interpolation in High Quality mode. 
* `SimpleGraph` now supports "flatlines", i.e. graphs where y<sub>min</sub> = y<sub>max</sub> (height of scale = 0).
* `SimpleGraphView` and `TemplateImageControl` use themed color in an improved/encapsulated way. Refactored in `ReferenceNozzleTip`.
* In `ReferenceNozzleTipCalibrationWizard` some new fields were not disabled when the calibration is disabled. 
* Minor improvements in UI layout of `AbstractAxisConfigurationWizard` and `SimulationModeMachineConfigurationWizard`.
* Interface cleanup in `AutoFocusProvider`.
* Catch empty nozzle in `AutoFocusProviderConfigurationWizard` with error message.
* Centralized angle norming in …

Feature / Round-up of UI and Utils Improvements

---

src/main/java/org/openpnp/gui/components/SimpleGraphView.java
src/main/java/org/openpnp/util/SimpleGraph.java

Adds the following enhancements to SimpleGraph and SimpleGraphView:
- Adds a setting to force the X-Y aspect ratio to be 1:1 which is useful for graphs whose x axis may have the same units as the y axis
- Adds a setting to enable/disable showing of the line which can be used to de-clutter graphs where only the data points are important
- Adds a setting to enable/disable showing of a data marker at each data point which can be used to highlight the data points rather than the connections between the data points
This change do not affect how OpenPnP currently operates but rather serves as a stepping stone to future enhancements.
No special instructions for the operator is required as this change in not currently visible to the operator.
**1. How did you test the change?** Ran Vision tests …

Add enhancements to SimpleGraph

---

src/main/java/org/openpnp/gui/components/IssuePanel.java
src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/axis/ReferenceControllerAxis.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/HeadSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/model/Length.java
src/main/java/org/openpnp/spi/base/AbstractCamera.java
src/main/java/org/openpnp/spi/base/AbstractCoordinateAxis.java

Enhancement and bug-fix round based on test version feed-back
* Copy static texts to clipboard in I&S `IssuePanel` using right mouse click. This is signalled by quickly flashing the text.
* I&S conservative solutions proposed when going back to more basic milestones (such as reverting a `GcodeAsyncDriver` to a `GcodeDriver`) are now only severity `Suggestion` (and not `Fundamental`) and they do no longer (reverse-) block dependent solutions.
* When replacing an `ImageCamera` or `SimulatedUpLookingCamera` with a real `OpenPnpCaptureCamera`, the old/new camera is now properly (un)registered in the `CameraView`. No OpenPnP restart required. Furthermore, should a USB device have been assigned in the meantime, the camera device is properly closed when the solution is undone.
* Fixed typo …

Feature/Automatic Machine Calibration using Issues & Solutions - Round 2

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/gui/components/IssuePanel.java
src/main/java/org/openpnp/gui/components/SimpleGraphView.java
src/main/java/org/openpnp/machine/reference/ReferenceActuator.java
src/main/java/org/openpnp/machine/reference/ReferenceHead.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java
src/main/java/org/openpnp/machine/reference/axis/ReferenceControllerAxis.java
src/main/java/org/openpnp/machine/reference/axis/wizards/ReferenceControllerAxisConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/AutoFocusProvider.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/HeadSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/model/Solutions.java
src/main/java/org/openpnp/spi/Head.java
src/main/java/org/openpnp/spi/Machine.java
src/main/java/org/openpnp/spi/Movable.java
src/main/java/org/openpnp/spi/base/AbstractHead.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java
src/main/java/org/openpnp/util/SimpleGraph.java
src/main/java/org/openpnp/util/UiUtils.java
src/main/resources/org/openpnp/machine/reference/vision/ReferenceFiducialLocator-CircularSymmetryPipeline.xml

This roundup of enhancements include the following:
- Merged develop into test
- Used @tonyluken 's new SimpleGraph improvements to better visualize backlash error data.
- Introduces `UiUtils.confirmMoveToLocationAndAct()` for UI actions that need to perform moves by the machine, that are possibly unexpected by the user. So this wrapper asks for confirmation and handles a disabled machine, threading issues and exception message boxes. Refactored `ReferencePushPullFeederConfigurationWizard` pre pipeline editing move (where this was extracted). Added a `ReferenceNozzleTipCalibrationWizard` pre pipeline editing move.
- Fix null pointer exception due to 3D UPP configuration error in `CameraView`.
- Move the `Head.isInsideSoftLimits()` to `Movable.isReachable()`, as it is actually not Head …

Feature/Automatic Machine Calibration using Issues & Solutions - Round 3

---

src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectCircularSymmetry.java
src/main/resources/org/openpnp/machine/reference/vision/ReferenceFiducialLocator-CircularSymmetryPipeline.xml

Just a small update to this testing round:
* Anti-aliased circle and cross-hairs diagnostics for `DetectCircularSymmetry`. If no match is found, a dashed red circle indicates the unmatched diameter.
* Separate boolean for circular symmetry heat map diagnostics. Normally switched off.
* Better description for feature diameter adjustments (see animation below). 
* Add super-sampling to the homing-fiducial pipeline that is assigned by Issues & Solutions.
See here:
https://groups.google.com/g/openpnp/c/-1VWW3uXOKw/m/cT-Wfct2BQAJ
See the Wiki:
https://github.com/openpnp/openpnp/wiki/Vision-Solutions#calibration-primary-fiducial
3. No changes in the `org.openpnp.spi` …

Feature/Automatic Machine Calibration using Issues & Solutions - Round 4

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java

Fies a nullpointer exception
Pushing covers of BlindsFeeder fails if no nozzle tip is loaded with an exception.
No change
1. How did you test the change? Not yet on machine, bug #1258 is currently a show stopper. But quite simple.

Catches the situation if no nozzle tip is loaded

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java

Fixes a bug in the nozzle tip tool changer vision calibration. When pixel coordinates are transformed to machine coordinates, the Y axis was not inverted, resulting in Y-mirrored template match offsets:
If a nozzle tip changer slot was offset in Y, it would actually compensate in the wrong direction. 
See
https://github.com/openpnp/openpnp/wiki/Nozzle-Tip-Changer
and more specifically
https://github.com/openpnp/openpnp/wiki/Nozzle-Tip-Changer#vision-calibration
1. The bug was detected during tests for another feature. Bug-fix was tested on machine.

Fix / Nozzle Tip Changer Vision Calibration, Y-Inversion 

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java

* In the FeederPanel, do the feed action with a compatible nozzle and nozzle tip, even though the pick does not actually happen.
* Refactored the feed action to be more job-like, with feeder preparation and nozzle tip change and calibration as needed, analogous to the pick action (which now uses the common code).
* Fix BlindsFeeder `feed()` for push cover: restore previous nozzle tip, if changed for cover opening.
See #1267
See #1267.
1. Tested FeederPanel in Simulation. Hoping for short-term confirmation via #1267 on BlindsFeeder fix.

Fix/Feeder Panel Feed compatible Nozzle and Tip, BlindsFeeder restore changed Nozzle Tip

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

Ensure the nozzle is at Safe Z when a Part-Off test is made before picking.
See #1281.
No change. See
https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration%3A-Vacuum-Sensing

Fix / Ensure Nozzle at Safe Z when sensing PartOff before Pick

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/gui/support/PercentIntegerConverter.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraTransformsConfigurationWizard.java

Based on #1276, this adds several improvements to color balance. This proved necessary after the simple linear white balance did not work well on the machine, showing non-linear response in the camera. 
* Added color Gamma to white-balance, implemented LUT based image processing with LUT cache,
* Implemented Gamma estimate in auto-balance method.
* Added a multi-level mapped color balance method.
* Added a graph of the color LUT to the Wizard. 
* Fixed bug in histogram smoothing.
* Fixed CameraView flashing on double-click (capturing snapshot).
It seems the RGB channels do not respond linearly to levels. This might or might not be caused by ambient light having a different cast and mixing in a non-linear fashion. 
The Wiki is work in progress.
1. Tested on machine.
2. Did follow the …

Feature/Better White Balance

---

src/main/java/org/openpnp/gui/components/CameraViewPopupMenu.java
src/main/java/org/openpnp/gui/components/reticle/GridReticle.java
src/main/java/org/openpnp/gui/components/reticle/RulerReticle.java

Adds an option to display a grid reticle in the camera views.  This is similar to the ruler reticle except the tick marks fill the entire width and height of the camera view. 
This is just an additional option for the operator.  A grid reticle is useful when evaluating camera lens distortion and may be useful for other measurement tasks as well.
From the camera view pop-up menu, select the Reticle->Grid option.  Just as with the ruler reticle, further options to change the Color, Units (inches/millimeters), and Units Per Tick are available under the pop-up menu Reticle->Options. 
**1. How did you test the change?** Selected the reticle grid option as detailed above and observed a full grid covering the image.  Selected various different options for Color, Units, and Units Per Tick and …

Add a grid reticle

---

src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java

(from the Wiki, [where this is already documented](https://github.com/openpnp/openpnp/wiki/Contact-Probing-Nozzle#z-calibration-inside-the-tool-changer))
The following does only apply, if **Auto Z Calibration** is set to **NozzleTipChange**, i.e. when Z calibration happens **per nozzle tip** and not per nozzle. For machines with uneven nozzle tips.
Z Calibration is referencing the coordinate system Z to the point of the nozzle tip (the red dashed line in the illustration below). This is obviously the most important Z reference point for a pick & place machine. However, when loading and unloading a nozzle tip, the point of the tip is not actually relevant, other features of the nozzle tip are: There are flanges etc. on the tip that come into contact with the changer slot and allow it to …

Fix / Unload Nozzle Tips without applying Z Calibration

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceHeapFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceHeapFeederConfigurationWizard.java

Some maintenance on the HeapFeeder.
- Adresses bug #1268 
- Removes an exception if the template match pipeline throws an exception (template larger than are marked in the camera picture)
- Failing to get parts from the Heap now counts as a feed failure. Avoids that in some circumstances (e.g. camera failures) dozens of fetch operations are executed.
- Minor maintenance
Improves the quality and usability of the HeapFeeder
If a parts are stored in a Heap that tend to clog/build rigid structures where the nozzle can not move easily (e.g. 1206 capacitors), you can now enable in the settings the "Poke for Parts" option. That means that during each move Z is lifted 2 1/4 times part size (but at least one mm) before moving back down. So the nozzle tip should never apply large forces to the …

HeapFeeder Maintenance

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/ReferenceCameraWhiteBalanceConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraTransformsConfigurationWizard.java
src/main/java/org/openpnp/util/VisionUtils.java

This builds on top of #1286 and #1276.
* Split `ReferenceCameraWhiteBalanceConfigurationWizard` from `ReferenceCameraTransformsConfigurationWizard`.
* Extract `VisionUtils.computeImageHistogram()` and refactored in `ReferenceCamera` and `CameraView`.
* Perform Auto-White-Balance actions in machine tasks.
On writing the Wiki, I noticed some usability issues that are corrected in this PR. The White Balance now has a separate "White Balance" tab, it is no longer on the "Transforms" tab. The new tab was moved after the Device 
See the [new Wiki page](https://github.com/openpnp/openpnp/wiki/Camera-White-Balance).
1. Tested in simulation with real machine snapshots.
3. No changes in the …

Feature/Better White-Balance and Wiki

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/LogPanel.java
src/main/java/org/openpnp/gui/PackageVisionPanel.java
src/main/java/org/openpnp/gui/PartSettingsPanel.java
src/main/java/org/openpnp/gui/components/ClassSelectionDialog.java
src/main/java/org/openpnp/machine/index/sheets/gui/FeederConfigurationWizard.java
src/main/java/org/openpnp/machine/neoden4/wizards/Neoden4CameraConfigurationWizard.java
src/main/java/org/openpnp/machine/neoden4/wizards/Neoden4DriverConfigurationWizard.java
src/main/java/org/openpnp/machine/rapidplacer/RapidFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/AutoFocusProviderConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/ImageCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/MjpgCaptureCameraWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OnvifIPCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OpenCvCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OpenPnpCaptureCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/SimulatedUpCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/wizards/WebcamConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverConsole.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverGcodes.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/AbstractReferenceFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceAutoFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceDragFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceHeapFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceLeverFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceRotatedTrayFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceSlotAutoFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/SchultzFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/SlotSchultzFeederConfigurationWizard.java

Simply removes all the inconsistent and old-style-looking `EdgedBorder.LOWERED` panel borders. 
Looks ugly:
No change.
1. Clicked around in OpenPnP.

Fix / Remove all EdgedBorder.LOWERED Borders

---

src/main/java/org/openpnp/vision/pipeline/stages/DetectRectangle.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectRectangleHough.java
src/main/java/org/openpnp/vision/pipeline/ui/CvPipelineEditor.java

Loosly based on the paper "Rectangle Detection based on a Windowed Hough
Transform" by Jung et al.
----------------------------------------------------------------------
This adds a new vision stage called DetectRectangle. It uses the HoughLines function of OpenCV and then does some further processing on the lines found. The first step is to organise lines into parallel pairs that are approximately symmetrical about the centre of the image. Pairs are then collected into quads that form rectangles. A score is applied to rectangles, based on the deviation from the expected size, along with a weighted score based on the strength of a line. Finally the corners are used to create a rotated rectangle, that can be used to get the part rotation and centre.
I had quite a bit of difficulty getting …

Add rectangle detection stage.

---

src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/model/Solutions.java

Another round of bug-fixes and improvements in the Automatic Machine Calibration using Issues & Solutions: 
* Make sure visual homing and backlash calibration are in no chicken and egg relation: The standard fiducial locator is (for once) replaced by the calibration locator, which has built-in worst case backlash calibration. 
* Reverse the sign of the built-in worst case backlash calibration to better correspond to what is later automatically calibrated.
* Perform a fresh visual homing after the backlash calibration, as the coordinate system might (still) slightly change. 
* Fix a nozzle head offsets calibration bug, that reset X, Y to zero, when only a small change in the offsets was detected. 
* Allow switching off the Issues & Solutions tab indicator through the `machine.xml` (there …

Feature/Automatic Machine Calibration using Issues & Solutions - Round 7

---

src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java

This is a quick fix for #1291.
Fix the automatic backlash calibration: After visual homing, a move back to the primary fiducial is needed.
See
https://groups.google.com/g/openpnp/c/dBg7txMB0R0/m/p4_oL0CYCAAJ
No change.
1. Tested in simulation, this time with a homing fiducial at a different location than the primary calibration fiducial.

Fix/Automatic Machine Calibration using Issues & Solutions - Round 7

---

src/main/java/org/openpnp/machine/reference/axis/ReferenceControllerAxis.java
src/main/java/org/openpnp/util/SimpleGraph.java

The `SimpleGraph` was made persistable, i.e. graphs can be saved in the `machine.xml` and they will not be lost, when exiting OpenPnP. 
Used on the `ReferenceControllerAxis`, where the Backlash Calibration graphs contain permanently useful info about the axis. 
Users reported the loss of the graphs as an error, they thought the underlying calibration was lost too. 
See discussion here:
https://groups.google.com/g/openpnp/c/dBg7txMB0R0/m/7yhfwuCQAgAJ
It just works.

Feature/SimpleGraph Persistence

---

src/main/java/org/openpnp/gui/components/SimpleGraphView.java
src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/axis/wizards/ReferenceControllerAxisConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ContactProbeNozzleWizard.java
src/main/java/org/openpnp/util/SimpleGraph.java

Another round in the [Automatic Machine Calibration using Issues & Solutions series](https://github.com/openpnp/openpnp/issues?q=label%3Aautomatic-calibration+is%3Aclosed).
* The `ContactProbeNozzle` now references its probing actuator by object, rather than by name. The name is only used for XML persistence.
* Added `ContactProbeNozzle` Issues & Solutions error for missing contact sensing actuator.
* Using `ContactProbeNozzle` cached Z offsets is immediately switched off, when the method is switched to **Off**. Previously, this has only become effective after a machine homing.
* Support dual shared axis nozzles, i.e. axis transforms in Issues & Solutions checks against the Z axis.
* Generate probing G-code with proper axis letter, probing limit according to soft-limit(s), and feed-rate …

Feature / Automatic Machine Calibration using Issues & Solutions - Round 8

---

src/main/java/org/openpnp/gui/components/SimpleGraphView.java
src/main/java/org/openpnp/machine/reference/axis/ReferenceControllerAxis.java
src/main/java/org/openpnp/machine/reference/axis/wizards/BacklashCompensationConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/axis/wizards/ReferenceControllerAxisConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/spi/base/AbstractDriver.java

Another round in the [Automatic Machine Calibration using Issues & Solutions series](https://github.com/openpnp/openpnp/issues?q=label%3Aautomatic-calibration+is%3Aclosed).
* Separated the Backlash Compensation Calibration into a separate Wizard.
* Improved the logarithmic view of SimpleGraphView.
* Improved the backlash over distance and time over distance graph recording in I&S backlash calibration.
* Better TinyG `HOME_COMMAND`.
* Refactored getting a driver's axes.
* Added speed-factor test and graph to backlash calibration. 
* Handle Acceptable Tolerance better, i.e. store effective tolerance back to axis.
* Indicate backlash envelope on graph.
Ongoing testing and feedback from the discussion:
https://groups.google.com/g/openpnp/c/dBg7txMB0R0/m/czPqQVSNCAAJ
The interpreted backlash …

Feature / Automatic Machine Calibration using Issues & Solutions - Round 9

---

src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

Another round in the [Automatic Machine Calibration using Issues & Solutions series](https://github.com/openpnp/openpnp/issues?q=label%3Aautomatic-calibration+is%3Aclosed).
* Only re-home in backlash calibration, if the **ResetToFiducialLocation** homing method is set. For **ResetToHomeCoordinates** a full homing cycle would be needed, and this is not generally do-able.
* Fixed bug in secondary fiducial offsets calibration: Undoing/Re-opening the solution would mistakenly restore the secondary fiducial Z to the primary fiducial Z.
* Limit the calibration displacement to the soft limits (by @tonyluken). 
* Make the zero nozzle offsets exception for the simulated machine more explicit, so it won't be applied to real machines.
Ongoing testing and feedback from the discussion: …

Feature / Automatic Machine Calibration using Issues & Solutions - Round 10

---

src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/ImageCameraConfigurationWizard.java

Allows simulation of Lens Distortion and Mounting Yaw for the ImageCamera. 
Note: this is a simple implementation, not performing any sub-pixel sampling. The resulting images are rather crude. 
Intended for testing #1297 by @tonyluken.
Use the new **Distortion [%]** field for setting the [lens distortion](https://en.wikipedia.org/wiki/Distortion_(optics)). 
Positive **Distortion [%]** for Barrel:
Negative **Distortion [%]** for Pincushion:
Use the **Mounting Yaw** field to configure an imperfect mounting yaw angle (i.e. around the Y axis):
Combinations are allowed.
Then use the classical or the new #1297 by @tonyluken.
1. Tested in simulation (obviously).
3. No changes in the …

Feature/Simulated Lens Distortion and Mounting Yaw

---

src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java

This fix accounts for a simulated camera yaw (see #1299) when rendering the fiducial 2. As the fiducial Z is elevated in Z, it is seen displaced by a camera with yaw.
Better testing of #1297 
None
1. Testing in simulation

Fix/Simulated Camera Yaw

---

src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/ImageCameraConfigurationWizard.java

* Add pixel interpolation / anti-aliasing to simulated ImageCamera lens distortion.
* Change terminology "Yaw" to "YRotation" to avoid misunderstandings. 
* Adjusted the UI to show camera mounting rotations around Z and Y axis in a similar way:
* Fixed fiducial rendering with Z rotation and scaling and mirroring.
See discussion in #1297.
See description.
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)
3. Successful `mvn test` before submitting the Pull Request.

Feature/Better Simulated Lens Distortion

---

src/main/java/org/openpnp/gui/components/reticle/RulerReticle.java

* The grid reticle is made to appear finer by applying transparency.
* The cross-hairs therefore also stand out.
Before:
After:
The grid almost makes the underlying image unreadable. The cross-hairs are no longer visible.
No chnage.

Feature / Finer Grid Reticle

---

src/main/java/org/openpnp/machine/reference/solutions/HeadSolutions.java

Issues & Solutions should not report shared C (Rotation) axes as an Error. Instead, only an Information is displayed, and the user is asked to confirm it is intentional by pressing **Dismiss**. 
The issue was previously reported as an Error:
Which is wrong for machines with intentionally shared C axes.
See the use case:
https://groups.google.com/g/openpnp/c/taXWhONJ6zY/m/LzV6rwKyAAAJ
Press **Dismiss**, if you intentionally assigned shared C axes.
1. Tested in simulation with the users `machine.xml`.

Fix/Issues & Solutions Should Allow Shared C Axes

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverSettings.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/util/GcodeServer.java

Fix to remove a potential threading race condition when detecting the firmware from the driver (button) or from Issues & Solutions. When the machine is enabled, this must be properly done inside a machine task.
When I tested this using a fresh `machine.xml`, I also noticed a chicken-egg situation in the early Issues & Solutions setup. The GcodeServer would throw if an axis letter is missing. But when using the GcodeServer to detect the firmware, we are in a simulated environment, i.e. a reasonable axis letters assignment can be assumed. This has been added for single and dual nozzle configurations.
The race might (or might not) be the reason for unexplained connection issues. See here:
https://groups.google.com/g/openpnp/c/taXWhONJ6zY/m/oHLn00cWAQAJ
No change.
2. …

Fix / Remove Threading Race when Detecting Firmware

---

src/test/java/ReferenceBottomVisionOffsetTest.java

As an attempt to get rid of deployment errors, try increasing `ReferenceBottomVisionOffsetTest` angular tolerances.
These tolerances are subject to pixel artifacts (from anti-aliasing), it is well possible that these are platform/GPU accelerator dependent. 
As suggested by @vonnieda 
No change.
1. Local tests (which are **not** conclusive i.e. they worked before)

Fix/ReferenceBottomVisionOffsetTest increased Angular Tolerance

---

src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/SimulatedUpCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

The SimulatedUpCamera has been improved to simulate a more "3D" view. 
* Simulate perspective (focal length).
* Added shading, i.e. colors get darker as objects move away. 
* Optimized blur (limitation to reasonable radii and [viewing frustrum](https://en.wikipedia.org/wiki/Viewing_frustum) for speed).
* Unblock Issues & Solutions SimulatedUpCamera calibration when the nozzle offsets are zero (as usual on a simulated machine).
Needed for testing #1297 (bottom camera advanced calibration).
The SimulatedUpCamera now has **Focal Length** and **Sensor Diagonal** to simulate the perspective of its view:
1. Tested in simulation and with #1297.
3. No changes in the `org.openpnp.spi` or …

Feature/SimulatedUpCamera 3D Emulation

---

src/main/java/org/openpnp/model/Configuration.java

Changes `Configuration.createResourceFile(Class, String, String)` to create files numbered by the [epoch time](https://en.wikipedia.org/wiki/Unix_time) in nanosecond, instead of random numbers. The nanosecond timer used is guaranteed to generate unique numbers (per Java VM). This makes sure files can be ordered chronologically by name, regardless of file system timestamps and their limited resolution (and whether they are preserved). 
These file names are typically generated when debug images are written in the `ImageWriteDebug` pipeline stage and from other places.
At least Windows has limited timestamp resolution (1s), so rapidly written files will not be ordered chronologically. 
Furthermore, some tools require files ordered by name, as an example I used an online animated gif maker. …

Feature / Chronological Ressource File Naming

---

src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java
src/main/java/org/openpnp/spi/Locatable.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java

Bug: When using the advanced camera calibration of #1297, the cameras would show a wrong location. Example: the visual homing performed at the end of advanced camera calibration would fail, as the fiducial is too far off. This is because the new calibration head offsets - used to compensate for camera tilt - were applied in the camera "physical" location calculation (i.e. they actually cancelled-out the applied tilt offsets). 
Fix: Added `LocationOption.SuppressCameraCalibration` to suppress the new advanced camera calibration head offsets, when obtaining HeadMountable locations. This new option is now used in the simulated cameras to get correct "physical" camera locations.
The simulated cameras need to render the raw camera view, _before_ advanced camera calibration applies. 
No change …

Fix / Advanced Camera Calibration Tilt Head Offsets in Simulation

---

src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java
src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/processes/CalibrateCameraProcess.java
src/main/java/org/openpnp/gui/wizards/CameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/camera/calibration/AdvancedCalibration.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraCalibrationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraTransformsConfigurationWizard.java

This PR integrates the Advanced Camera Calibration by @tonyluken (#1297) into the Issues & Solutions machine setup process.
- Advanced Camera Calibrations is available as regular Issues & Solutions calibration steps.
- The invoked calibration is automatic, i.e. it does not interactively ask the user for fiducial location/diameters etc. Instead it reuses the already setup locations/diameters etc. from the preliminary calibration rig. 
- Camera feedback does no longer lag behind, camera image and cross-hairs do match. Furthermore, markers are drawn with anti-aliasing and sub-pixel accuracy:
- The classical Transforms and Units per Pixel wizard settings are grayed out when the Advanced Camera Calibration is active.
- The preliminary calibration is locked, when the Advanced Camera Calibration …

Feature/Issues & Solutions: Integrate Advanced Camera Calibration

---

src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OpenPnpCaptureCameraConfigurationWizard.java

`OpenPnpCaptureCamera`: Due to an instability in the `CaptureFormat.equals()` method, we use the `toString()` representation (Name) for video format selection in the GUI. A `formatName` getter/setter does the translation.
As an aside, this will also log a warning if two cameras have the same unique ID.
Video format selection in the GUI was sometimes lost. Debugging has revealed that the `CaptureDevices` returned by `getCaptureDevices()` sometimes change between calls (different Java Objects). When this happens, the `CaptureFormat` Objects are also different. The `CaptureFormat.equals()` method then makes the formats _falsely_ differ, due to a changed `auto-allocated@` property. The ComboBox will then just select the first entry. 
No changes.
1. Tested on the machine.
2. Did follow the …

Fix/OpenPnpCaptureCamera Video Format Identity Instability

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java

Fixes a bug from #1334 where the `AbstractMotionPlanner ` throws a `NullPointerException` on startup.
As the `AbstractMotionPlanner.wrapUpCoordinates()` method now can be called before any motion actually took place, the `machine` member may not yet be initialized.
Bugfix.
No change.
1. Tested on the machine.

Fix / AbstractMotionPlanner Startup Null Exception

---

src/main/java/org/openpnp/machine/reference/camera/calibration/AdvancedCalibration.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraCalibrationConfigurationWizard.java

- Fixes a race condition in #1335 where the virtual camera matrix is on-demand calculated along with the undistort map, but also used for 3D Units per Pixel. So if Units per Pixel are required too early, calculation would fail. Immediate recalculation of the undistort map and virtual camera matrix is now enforced after calibration.
- Disables the classic Lens Calibration Wizard when the Advanced Camera Calibration is active.
Running the calibration from Issues & Solutions would sometimes result in corrupt units per pixel. 
No change.
1. Tested on the machine.
4. Successful `mvn test` before submitting the Pull …

Fix / Issues and Solutions Advanced Camera Calibration Problems

---

src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java

Advanced Camera Calibration configuration needs to be properly loaded and committed before the first frame is captured, as  undistort maps need to be created. 
On startup, Issues & Solutions is finding issues, and displaying the first one. Some issues query the camera for dimension, prompting a camera capture to get the frame size. This was done before the camera was properly started. By delaying the Issues & Solutions startup, we can circumvent that. 
The delay also somewhat makes startup of OpenPnP faster. 
OpenPnP would throw this:
```java
2021-11-27 17:09:21.332 ReferenceCamera ERROR: org.opencv.core.CvException: cv::Exception: OpenCV(4.5.1) /home/runner/work/opencv/opencv/opencv-4.5.1/modules/imgproc/src/imgwarp.cpp:1703: error: (-215:Assertion failed) !_map1.empty() in function …
```

Fix: Advanced Camera Calibration startup race.

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

The dynamic `HOME_COMMAND` introduced in #1319 did not properly guard against legacy configured machines, where axes are still addressed by axis type (X, Y, Z, Rotation) rather than by proper controller axis letters. Machines with multiple axes of the same types (typically two Z or Rotation axes etc.) would therefore fail in the home command, where all the axes are addressed at once, and duplicate types are therefore present: 
This fixes the bug by excluding such machines from the dynamic `HOME_COMMAND` feature. 
See here:
https://groups.google.com/g/openpnp/c/CIj9T9TjFBY/m/2jGBfZVHAwAJ
No change.
1. Tested in simulation, provoking the situation before and after the fix.
3. No changes …

Fix/Need Axis Letter Variables Enabled for Dynamic Home

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

This is a backport (cherry-pick) of #1340.
See #1340.
See #1340.
See #1340.

Fix (Cherry Pick) / Need Axis Letter Variables Enabled for Dynamic Home

---

pom.xml
src/main/java/org/openpnp/machine/reference/feeder/ReferenceHeapFeeder.java

Remove unused private logger in ReferenceHeapFeeder class and associated dependency from pom.xml.
ReferenceHeapFeeder class creates a private logger instance using sfl4j which in turn depends on log4j
but pulls in an old, old version of it. Since version 1.x series of log4j is described as having "multiple security issues"
it's better to remove the unneeded dependency.
N/A
Static code analysis only.
N/A (removal only)
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require …

Remove unused logger and slf4j/log4j dependency

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/test/java/GcodeDriverTest.java

When a driver had no axes, it would not wait for completion, even unconditional waits. This is fixed here.
As a "stowaway", this also fixes an unnecessary exception in Issues & Solutions if no vacuum actuator is assigned to a nozzle.
See user case:
https://groups.google.com/g/openpnp/c/2jx2SCEEQtk/m/GXkBhtYVEAAJ
Applies to `GcodeAsyncDrivers` without any axes, but implementing the (historically named) `MOVE_TO_COMPLETE_COMMAND`, typically implementing `M400`, i.e., a command to wait for pending controller actions to complete. 
Typical use case: When using Actuator **After Actuate** machine coordination, the actuator driver should unconditionally wait for completion, even if it has no axes assigned to it. The user's case was a Feeder _feed_ actuator that the machine should wait for to …

Fix / Unconditional Wait For Completion On Drivers Without Axes

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceMachineConfigurationWizard.java
src/main/java/org/openpnp/spi/Machine.java

Adds an option to move all HeadMountables on the same Head to Safe Z when Park Z is pressed.
See discussion here (second item):
https://groups.google.com/g/openpnp/c/_BqWBSMAdt8/m/adpLhMQxEAAJ
Enabled the **Park all at Safe Z?** option on the Machine:
Use the Z Park button 
3. New `Machine.isSafeZPark()` in  `org.openpnp.spi` package.

Feature / Move all HeadMountables on Head to Safe Z when Park Z is pressed

---

src/main/java/org/openpnp/machine/reference/ReferenceHead.java
src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java
src/main/java/org/openpnp/machine/reference/driver/ReferenceDriverCommunications.java
src/main/java/org/openpnp/machine/reference/driver/SimulatedCommunications.java
src/main/java/org/openpnp/machine/reference/driver/TcpCommunications.java

Visual Homing with the legacy **ResetToHomeLocation** option did not properly account for the Advanced Camera Calibration. 
The camera should be at nominal homing coordinates when above the homing fiducial, i.e. after visual homing. This was not the case, when the camera had non-zero head offsets, as these are "traditionally" not accounted for in calculating the homing coordinates, when legacy **ResetToHomeLocation** is used. By introducing the Advanced Camera Calibration, we now have dynamic head offsets on the camera that _should_ be accounted for.
For best legacy support, this fix does not alter the existing behavior, i.e. static head offsets are still not accounted for. 
This PR also contains a fix for the `ImageCamera` not showing `G92` adjusted physical locations accurately, e.g. …

Fix / Visual Homing with Advanced Camera Calibration

---

src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java
src/main/java/org/openpnp/gui/components/IssuePanel.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/HeadSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/KinematicSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/util/MovableUtils.java

According to feedback from the testing, improves Issues & Solutions to validate more preconditions, automatically re-open solutions and add Z and Rotation axes solutions.
1. Reject any calibration fiducial Z above Safe Z.
2. Reject secondary calibration fiducial, if Z is less that 2mm different from primary (min offset can be set in `machine.xml`).
3. For all solutions using fiducials, also check that the fiducial diameter is set (it was only looking at X, Y coordinates before). A user might have tried to capture fiducials manually, and forgot the diameter. Solutions will not be offered in this case.
4. For all solutions using the primary fiducial, also check that camera UPP are set. A user might have tried to capture fiducials manually, but not set the UPP. Solutions will not be offered …

Fix/Issues & Solutions Advanced Camera Calibration, Axis Handling

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/processes/CalibrateCameraProcess.java
src/main/java/org/openpnp/machine/reference/driver/wizards/AbstractReferenceDriverConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java
src/main/java/org/openpnp/spi/base/AbstractNozzle.java
src/main/java/org/openpnp/util/MovableUtils.java

This is a round-up of bug-fixes and improvements out of testing.
* Error when no nozzle tip loaded in _preliminary_ bottom camera
calibration.
* Disable Advanced Camera Calibration after it fails in the middle.
* Advanced Camera Calibration tool selection in Machine Controls from I&S: bug-fix.
* Limited articulation Rotation Mode support for Advanced Camera
Calibration.
* Log new rotation mode offset being set.
* Communications type visibility initially not established in Driver Wizard: bug-fix.
* Better serial flow control vs. confirmation flow control solutions.
* Optimize Safe Z moving: always move HeadMountables to the _nearer_ limit of the Safe Z Zone:
* Feeder no part assigned caught in GUI actions.
See these discussions:
https://groups.google.com/g/openpnp/c/MnKQK_Keww8/m/k9q2R3n7AQ …

Fix / Issues & Solutions more Watertight - Round 2

---

src/main/java/org/openpnp/machine/reference/camera/calibration/LensCalibrationParams.java

Explicitly initialize the cameraMatrix and distortionCoefficients matrices to prevent unnecessary warning messages during Maven tests..
Eliminates unnecessary warning messages during Maven test so there are fewer things to sort through.
No special instructions for the user.
1. How did you test the change? **Ran Maven tests several times and observed no warnings due to uninitialized memory.**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **Yes.**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. **No changes.**
4. Be sure to run `mvn test` before submitting the Pull …

Initialized camera and distortion matrices

---

src/main/java/org/openpnp/gui/ActuatorControlDialog.java
src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java
src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/machine/reference/ActuatorInterlockMonitor.java
src/main/java/org/openpnp/machine/reference/ReferenceActuator.java
src/main/java/org/openpnp/machine/reference/ReferenceActuatorProfiles.java
src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java
src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java
src/main/java/org/openpnp/machine/reference/solutions/ActuatorSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/spi/Actuator.java
src/main/java/org/openpnp/spi/base/AbstractActuator.java
src/main/java/org/openpnp/spi/base/AbstractCamera.java
src/test/java/GcodeDriverTest.java

When an Actuator has a non-Boolean value type, and it is actuated using Boolean semantics, it should use the ON and OFF values, as configured. This did not always work. Due to special handling, it worked with light Actuators, Auto Feeder Actuators, and the On/Off Actuator Dialog, that's probably why it was not found earlier.
In testing it occurred to me that Issues & Solutions should also propose G-code for `ACTUATE_STRING_COMMAND`, and for Actuators that are nested in a Profile Actuator. This is now covered too.
This also fixes extra bugs found in testing: 
- Simulating light OFF (shading) in the simulated `ImageCamera` did not cover the whole area if the camera transform is rotated. 
- If Issues & Solutions is started too early, i.e. when the Tabs are not yet materialized, it would …

Fix / Handle Actuator Value Types ON/OFF Values, Cover in Issues & Solutions

---

src/main/java/org/openpnp/machine/reference/driver/GcodeAsyncDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/solutions/AxisSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

Another round-up of bugs and issues that popped up during the testing round.
1. For CHMT machines: the Smoothieware STM32 port (legacy) `PAXIS` build option is now implied and properly handled.
2. Regular Smoothieboard detection improved. Now looking for the "best-for-pnp" tag in the `M115` `X-SOURCE_CODE_URL` property, instead of just relying on the `X-PAXES` property.
3. If `PAXIS` is not reported via `M115` `X-PAXES` property, or if it is reported smaller than `X-AXES`, then Issues & Solutions will remind the user to get or build a better firmware.
3. Issues & Solutions now takes `M114` reported axes as the valid axis letters on the controller. If the reported axes are not (yet) available, it falls back to offer all the standard letters.  
4. Only the valid axis letters are then …

Fix/Issues & Solutions Axes Handling, Firmware Detection

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/spi/base/AbstractNozzle.java

Rotation axes default limits -180° .. 180° were not properly calculated when a Rotation Mode offset was applied. Instead of taking raw axis coordinates, it took nozzle coordinates, i.e. potentially shifted by the Rotation Mode offset.
This PR fixes it.
A small logging error was also fixed.
See user report:
https://groups.google.com/g/openpnp/c/bXTsbYdW4dU/m/0aw54eugAgAJ
See 
https://github.com/openpnp/openpnp/wiki/Nozzle-Rotation-Mode
Note: when using transformed rotation axis, i.e. with raw coordinates that are not degrees, the default limits of -180° .. 180° might now be non-sensical:
https://github.com/openpnp/openpnp/wiki/Nozzle-Rotation-Mode#rotational-axis-transformations
This case might "accidentally" have worked before, as defaults were (mistakenly) taken from _transformed_ nozzle …

Fix / Rotation Axis Default Limits -180° .. 180°, and Rotation Mode

---

src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/neoden4/wizards/NeoDen4FeederActuatorConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java

Enable driver support and GUI element to allow changing the Neoden4 Feeder ID. Each feeder internally stores an ID for the machine to address it (typically 1-50, new feeders ship default to 50). We will allow range from 0-99. Feature request #1344 
Updates the Neoden4 machine specific class
In a Neoden4 Feeder Actuator, select the old and new ID numbers from the dropdowns, and click 'Change'
2. I think this follows similar style
3. Changes local to only Neoden4 machine classes
4. Ran mvn test

[Neoden4][FeederActuator] Add support to change Feeder IDs

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/SerialPortCommunications.java

Avoid loss of characters due to serial port read timeouts causing a partially read line to be discarded.
As discussed in #1235 and rebased onto test branch as mentioned in #1377.
N/A
Only tested with maven built in tests. I've no serial comms to check this.
Yes
N/A …

 Remove serial port read timeout. Close port before reader thread join. (resubmit)

---

src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java

There was a race/bug drawing/layouting the Issues & Solutions tab in a corrupted way. This is related to the initial automatic execution of **Find Issues & Solutions** when OpenPnP starts up.   
(Screenshot by Duncan)
This PR further decouples the initial automatic execution of **Find Issues & Solutions**, and subsequent solutions change and selection change notifications. This is after reading that a `TimerTask`, contrary to my expectations, does not run on the GUI event dispatching thread (as `SwingUtilities.invokeLater()` would). 
Everything is now done asynchronously. Only one notification is followed up, even if several have been registered. Note, I already attempted to implement that idea before, but there was a bug, setting the `dirty` flag asynchronously, instead of synchronously, …

Fix / Trying to get rid of the Issues & Solutions Tab Race

---

src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceMachineConfigurationWizard.java
src/main/java/org/openpnp/spi/Machine.java

Adds to minor goodies to machine control.
- Option to park heads after the machine was homed.
- Configurable unsafe Z roaming distance for head-mountables (typically cameras) with Virtual Z axes.
The option to park heads after the machine was homed was a user suggestion.
Virtual Z axes (typically on cameras) are invisible, therefore it can easily be overlooked by users that they might be at unsafe Z. When they later press the **Move tool to camera location** button, an unexpected Z down-move will result, potentially crashing the tool. 
The maximum allowable roaming distance at unsafe Z therefore limits the jogging area within which an unsafe virtual Z is kept. It should be enough to fine-adjust a captured location, but jogging further away will automatically move the virtual axis to Safe …

Feature / Configurable parkAfterHomed and unsafeZRoamingDistance Options

---

src/main/java/org/openpnp/gui/components/HsvIndicator.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/BottomVisionSettingsConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipConfigurationWizard.java
src/main/java/org/openpnp/util/VisionUtils.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java
src/main/java/org/openpnp/vision/pipeline/stages/BlurGaussian.java
src/main/java/org/openpnp/vision/pipeline/stages/CreateFootprintTemplateImage.java
src/main/java/org/openpnp/vision/pipeline/stages/FilterContours.java
src/main/java/org/openpnp/vision/pipeline/stages/ImageCapture.java
src/main/java/org/openpnp/vision/pipeline/stages/ImageRead.java
src/main/java/org/openpnp/vision/pipeline/stages/MaskCircle.java
src/main/java/org/openpnp/vision/pipeline/stages/MaskHsv.java

The Bottom Vision pipeline almost never works out of the box, users need to tweak the properties of select stages to make them work with their camera and their machine. Firstly, it is difficult to understand why a part detection does not work, and where in the pipeline the problem happens. Root causes may often be obscured and happen many stages before the visibly bad result is exposed. Secondly, once the proper stage is identified, it is often difficult to adjust its properties. Stages and individual properties are completely generic, and (often very academically) abstracted from their actual tasks, which is a good thing from a math and software design perspective, but a bad thing for them to be understood by OpenPnP users, in the context of the actual pipeline use case. 
One of the more …

Feature/Bottom Vision Nozzle Tip Background Knockout Calibration

---

src/main/java/org/openpnp/gui/components/LocationButtonsPanel.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullMotionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/AxisSolutions.java

- Use the Rotation axis on a `ReferencePushPullFeeder` actuator motion locations, to be used for _coordinated_ peeling.
- Support additive rotation for continuous peeling spool wind-up.
- Change Issues & Solutions to only suggest wrap-around and +/-180° limiting on nozzle rotation axes (it would be wrong for peeler rotation axes).
- Actuators are now always referenced by Object from the `ReferencePushPullFeeder`, reference by name only for XML persistence.
See the conversation here:
https://groups.google.com/g/openpnp/c/pd2hQ1cq2dw/m/FOcm83PLAgAJ
Cover tape peeling can be done using motion that is coordinated with the push-pull articulation, as needed for drag feeders etc. This allows for an elaborate and coordinated motion pattern. Furthermore, it performs the peeling motion _in …

Feature/ReferencePushPullFeeder uses Actuator Rotation Axis for Peeling

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullMotionConfigurationWizard.java

- Allow switching off the application of vision calibration to the  X/Y coordinates of the push-pull motion locations.
- Reset the peeler/rotation axis coordinate instead of just using additive math.
- Handle resetting properly, even if there is multi-actuation needed. 
- Bugfix: Avoid an exception in the GUI if no actuator is assigned to the feeder yet.
Testing round of #1390. 
See the discussion here:
https://groups.google.com/g/openpnp/c/wpHLTbWaZI0/m/39Lx57wCAwAJ
Use the new **Vision Calibrate?** checkboxes under the **X** and **Y** columns:
Some feeders need multi-actuation, for instance if the part pitch in the tape is larger than the maximum tape feed that can be done by the mechanical motion. To enable multi-actuation _together_ with additive rotation, see the screenshot above, …

Feature / ReferencePushPullFeeder Better Motion Coordinate Handling

---

src/main/java/org/openpnp/machine/reference/solutions/HeadSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/KinematicSolutions.java
src/main/java/org/openpnp/spi/NozzleTip.java

With **Dynamic Safe Z** enabled, nozzles need a head-room, the so-called Safe Z Zone to lift the nozzles higher with taller parts. Furthermore, on nozzles with shared Z axes the part heights compete for the same head-room. The maximum expected part height is specified on the nozzle tip **Max. Part Height**.
These Issues & Solutions detect when the (combined) **Max. Part Height**(s) on single or shared Z axis nozzles violate the Safe Z Zone head-room.
See discussion group:
https://groups.google.com/g/openpnp/c/kQZzXxshQog/m/1kGQF2XYBwAJ
Are provided in the Solutions, and in the [Wiki](https://github.com/openpnp/openpnp/wiki/Kinematic-Solutions), that was already written to accompany the Solutions with links:
New, more specific Wiki sections and links were also added for existing Dynamic …

Feature / Issues & Solutions Dynamic Safe Z and Max. Part Heights

---

src/main/java/org/openpnp/machine/reference/driver/ReferenceAdvancedMotionPlanner.java
src/main/java/org/openpnp/machine/reference/solutions/KinematicSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectCircularSymmetry.java

Some small bug-fixes in the running testing version.
- Bugs in [Issues & Solutions](https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions) when establishing Visual Homing, see #1248, broken by #1318.
- Register the `DetectCircularSymmetry` `minDiameter`/`maxDiameter` property override, see #1387.
- Preventing a caught but unnecessary exception and fixing typos in #1395.
Various feed-back and own testing.
Bugfix demonstrated in Visual Homing calibration:

Fix/Bugfixes Testing Round

---

src/main/resources/org/openpnp/machine/reference/feeder/BlindsFeeder-Library.scad

The fiducials on the BlindsFeeder OpenSCAD model are not correctly positioned if the wall_width parameter is changed.
This is a simple fix to allow for a different wall_width so you can space out the strip lanes to account for things like passive spool hangers.  By default, the model is completely unchanged, this only corrects the calculation of the fiducial position to account for the wall_width if it does change.  Currently, any wall_width value other than 1 results in an incorrect position of the fiducials, such as this:
Create an instance of a BlindsFeeder object and pass in a wall_width value of anything other than the default of 1.  The walls between lanes will be increased and the fiducials will remain in their proper positions.
This is a simple 2-line change to include the …

Fix BlindsFeeder fiducials with increased wall_width

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java

This just improves the error message, when the Max. Pick Tolerance is violated in bottom vision. It now points to the **Max. Pick Tolerance** setting on the nozzle tip.
See user feedback:
https://groups.google.com/g/openpnp/c/lGikHtY5lh8/m/eADrPxEhDAAJ
No change.
Background, see Wiki:
https://github.com/openpnp/openpnp/wiki/DetectRectlinearSymmetry#nozzle-tip-configuration

Fix / Better Error Message When Max. Pick Tolerance Violated.

---

src/main/java/org/openpnp/machine/reference/camera/calibration/AdvancedCalibration.java

This is a follow on to PR #1401 - this change disables tangential distortion correction by default
Testing has shown that camera calibration performs better with tangential distortion correction disabled. 
For new camera calibrations, no special action is required as this will be applied by default.
For cameras that had previously been calibrated, they can either be fully recalibrated, or the collection step can be skipped and the change applied by navigating to each camera in the Machine setup tree, selecting the Advanced Calibration tab, enabling the "Skip New Collection and Reprocess Prior Collection" check box, and then clicking the "Start Calibration" button.
Note - in the off chance that someone wants to re-enable tangential distortion correction, they can manually do so by editing …

Disable tangential distortion correction by default

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/spi/base/AbstractNozzle.java

Some feeders (e.g. `ReferenceStripFeeder`) use vision to determine the precise pick location **and angle**. Under [limited articulation Rotation Mode](https://github.com/openpnp/openpnp/wiki/Nozzle-Rotation-Mode) we need to _predict_ not only the needed pick-to-place articulation but also the added tolerance on both the pick and the alignment/placement side. This PR adds the tolerance  on the pick side to allow for feeder vision pick angle adjustment. Such a tolerance was previously already present on the alignment (bottom vision) side.
In the unlikely event that this is required, the expected maximum tolerances can now be configured in the `machine.xml` file. If the machine articulation is sufficient, the pick-to-place articulation plus the tolerances on both sides are centered. If the …

Fix / Allow For Pick Angle Tolerance Under Limited Articulation.

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/spi/JobProcessor.java

This PR introduces Job-interrupting Exceptions. These are propagated even if the placement has **Defer** error handling. 
Some exceptions, such as those prompting for manual nozzle tip changing must not be deferred. 
See also the user case:
https://groups.google.com/g/openpnp/c/uvRoayOn3fo/m/Kmwgio7LAQAJ
To reproduce the problem 
- create a Job
- set placements to **Defer**
- disable automatic nozzle tip changing
- make sure wrong/no nozzle tips are loaded
- start the job
In the previous version, this would silently skip the exception prompting for manual nozzle tip change, continuing the job with the (physically) wrong nozzle tip.
Now it should interrupt the Job and prompt for manual nozzle tip change with the usual message box. …

Feature / Introduce Job-Interrupting Exceptions - Manual Nozzle Tip Changing

---

src/main/java/org/openpnp/vision/pipeline/stages/AffineWarp.java

In the computer vision pipeline stage `AffineWarp`, record individual stage properties as overridden, when a Region Of Interest (ROI) is given by the pipeline caller, such as with feeder vision with OCR.
This PR also fixes a missing length unit conversion.
See user report:
https://groups.google.com/g/openpnp/c/wpHLTbWaZI0/m/_hCGZKusAgAJ
The stage properties will now show as controlled:

Fix / AffineWarp Stage Property Overrides by Region of Interest

---

src/main/java/org/openpnp/gui/tablemodel/PartsTableModel.java
src/main/java/org/openpnp/model/Part.java
src/main/java/org/openpnp/model/Placement.java
src/main/java/org/openpnp/spi/base/AbstractFeeder.java

This adds **Placements** and **Feeders** counts to the **Parts** table.
Users can quickly see how many parts are going to be required for one Job. The table can also be cleverly sorted by these columns to help provisioning feeders.
The **Placements** count is automatically computed and updated whenever placements are added/changed. Note, the full count is used, regardless of enabled/disabled boards, and regardless of enabled/disabled or already placed placements.
The **Feeders** count is automatically computed and updated whenever parts are assigned/unassigned on feeders. Note, the full count is used, regardless of enabled/disabled feeders. 
For feeder provisioning, first click twice on the **Placements** column header to sort descending and then click on the  **Feeders** column header to …

Feature/Parts Table Placement and Feeder Counts

---

src/main/java/org/openpnp/machine/rapidplacer/RapidFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java

- ReferencePushPullFeeder: More robustness against OCR failure during Auto-Setup.
- RapidFeeder: Remove a numerical instability in the QR scanning loop (old bug).
User feed-back:
- https://github.com/openpnp/openpnp/pull/1409#issuecomment-1121579824
- https://groups.google.com/g/openpnp/c/14Eoeqr2pvM/m/ak__R_OQBQAJ
No changes.
1. Can only be tested on user side. 

Fix/Feeder Bugs in Testing Round

---

src/main/java/org/openpnp/machine/reference/camera/calibration/AdvancedCalibration.java

Correction to [PR#1402](https://github.com/openpnp/openpnp/pull/1402/files).  It accidentally by disabled all distortion correction instead of only tangential distortion correction.
Fixes a known bug for all users.
Anyone that has been using the test branch and has previously ran Advanced Camera Calibration should go to the Advanced Calibration tab of each of their cameras, select "Skip New Collection and Reprocess Prior Collection" and click on the "Start Calibration" button. 
1. How did you test the change? **Prior to this change examined the machine.xml file and observed the following settings:
disable-distortion-correction="true"
disable-tangential-distortion-correction="false"
version="1.2"
After running OpenPnP with this change, the settings changed to: …

Fixed default settings to only disable tangential distortion correction

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java

Fixes an _incredibly so far undiscovered_ bug in the `BlindsFeeder` blinds cover opening/closing edge distance computation. The half pocket pitch **actuation distance** was missing! In the past, this only worked by virtue of an extra 2mm air gap that was added (but logically only on up to 4mm pitch tape). 
Bug-fix. Thanks to Matt for pointing it out:
https://groups.google.com/g/openpnp/c/hKAkBR8l3X8/m/u4MyVRsjAAAJ
No change in usage. See the Wiki:
https://github.com/openpnp/openpnp/wiki/BlindsFeeder#allowing-the-nozzle-tip-to-push-the-cover
1. I have not tested the chnage, hope the reporting user Matt can test quickly in th etesting version.
3. No changes in the `org.openpnp.spi` or …

Fix / Add Half Pocket Pitch to Opening/Closing Blinds Cover Edge

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java

Background calibration must not be done when calibrating the camera (rather than the nozzle tip). It could result in a null pointer exception.
This also removes an erroneous `MovableUtils.fireTargetedUserAction(nozzle)` call that flickered the camera.
User report (in PM):
No change in usage. See the Wiki:
https://github.com/openpnp/openpnp/wiki/Nozzle-Tip-Background-Calibration

Fix / No Background Calibration when Calibrating Camera

---

src/main/java/org/openpnp/gui/processes/CalibrateCameraProcess.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/ReferenceDriverCommunications.java
src/main/java/org/openpnp/machine/reference/driver/SerialPortCommunications.java
src/main/java/org/openpnp/machine/reference/driver/SimulatedCommunications.java
src/main/java/org/openpnp/machine/reference/driver/TcpCommunications.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraCalibrationWizard.java
src/main/java/org/openpnp/util/UiUtils.java
src/test/java/SampleJobTest.java
src/test/resources/config/SampleJobTest/machine.xml

This PR tries to tackle a race condition that happens _intermittently_ on GitHub Actions and never in local `mvn test`.
It was first exposed by through GitHub Actions that [seemed to hang for hours, seemingly waiting for someone to dismiss a message box](https://github.com/openpnp/openpnp/runs/6722724850?check_suite_focus=true). 
Although the head-less state was detected by a missing X11 `DISPLAY` variable, the unit would still hang on the message-box.
```Java
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:165)
at java.desktop/java.awt.Window.<init>(Window.java:545)
at java.desktop/java.awt.Frame.<init>(Frame.java:423)
at …
```

Fix / Races in GitHubActions - UiUtils.showError() - SimulatedCommunications

---

src/main/java/org/openpnp/gui/processes/CalibrateCameraProcess.java
src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java

This PR brings back one detail of #1420 where the line walker goes to the corner of the camera view. Turns out this is needed to get convergence with that few lines. 
As an asside, this PR improves the distortion simulation to exhibit a more complex distortion that challenges the calibration. The actual function was refactored to make the code more understandable:
https://github.com/markmaker/openpnp/blob/8302de47f49264c09380a5df747c10455fc719b1/src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java#L354
It has now the r² + r⁴ + r⁶ order, and exhibits the more typical distortion where the middle is quite linear, but the edges are worse.
Otherwise you get this:
No changes. …

Fix/Advanced Camera Calibration Low Line Count

---

src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectCircularSymmetry.java

This just swaps the unnatural `max` before `min` diameter order in `findCircularSymmetry()` function signatures.
Makes it more understandable.
No chnage.

Fix / Swap the unnatural max, min diameter order in function signatures.

---

src/main/java/org/openpnp/machine/reference/ReferenceMachine.java

This reverts one #1425 fix that executed the "Home after Enabled" synchronously inside the enabled setter. This is not right, it must be queued as a separate machine task.
This fix keeps the check for `isTask()` so if `setEnabled()` is called from unit tests etc. that do not use machine tasks, homing is still prevented. 
When the homing fails, it fails the enabling of the machine. This is not wanted, the homing should still be a separate task, even if triggered automatically after the machine is enabled.
No change.

Fix / Home after Enabled

---

src/main/java/org/openpnp/gui/importer/EagleBoardImporter.java

Add SMD pad definitions to packages on EAGLE board import
Currently, the Eagle Board Importer does not import pad outline definitions for packages, even though the information exists inside of the board file, and OpenPnP has the data structures in place for storing those definitions.  There is room for improvement here, such as possibly filtering out only pads that are located on the top layer of the board, or handling of mirrored parts to bring them onto the top layer.  Also, this makes no attempt to import through-hole pads, as it seems like OpenPnp's package model doesn't really have a way to define those.
Click File>Import Board>CadSoft EAGLE Board
Click Browse and select an EAGLE .brd file
Check the box labeled "Create Missing Parts"
Click Import
Navigate to the Packages tab in the …

Eagle import pads

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/PackagesPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/spi/NozzleTip.java

This is about nozzle tips compatible with the selected nozzle and with the package to be picked. It is primarily used in the various **Pick** actions:
If the nozzle tip on the currently selected nozzle is not compatible, the function tries to load a compatible nozzle tip, if automatic loading is enabled. Conversely, if automatic nozzle tip loading is disabled, the user is told to consider switching it on.
This fix handles some complications:
- The automatic nozzle tip loading option was suggested, even though it was already on (but another condition prevented it from happening).
- A compatible nozzle tip could be already loaded on another nozzle, so the user is instead told to select the other nozzle instead.
- A part could already be loaded on the selected nozzle, preventing nozzle tip …

Fix / Improve Pick Part Action Error Messages 

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/vision/pipeline/stages/MinAreaRect.java

The `MinAreaRect` stage is extended to allow detection of less that four edges of the Rectangle.
This PR contains the following parts:
- Adds the new selective edge detection. See **Instructions for Use**.
- Optimize the pixels that are taken into consideration. Only threshold-selected pixels that are at the first or last of **both** a vertical **and** horizontal scan-line are considered. These are enough to define the convex hull of the subject. A small pixel list greatly reduces the amount of computation in the new (and old) `MinAreaRect` algorithm. 
- This also allows to optionally use (grayscale) subject images directly, regardless of how large the threshold-selected areas are. Contour detection and redrawing is no longer required. 
- In order to determine the sense of what is "left", …

Feature / MinAreaRect partial Edges

---

src/main/java/org/openpnp/gui/PackageVisionPanel.java
src/main/java/org/openpnp/gui/support/Icons.java
src/main/java/org/openpnp/model/Footprint.java
src/main/resources/icons/footprint-bga.svg
src/main/resources/icons/footprint-bga_dark.svg
src/main/resources/icons/footprint-dual.svg
src/main/resources/icons/footprint-dual_dark.svg
src/main/resources/icons/footprint-quad.svg
src/main/resources/icons/footprint-quad_dark.svg

Adding a simple footprint generator: 
- Dual form factor packages.
- Quad form factor packages.
- BGA packages.
Given a few inputs, it can generate the pads for the most common ICs. 
- Can only generate Dual form factor packages with pins left-right, as is the [Part Zero Orientation](https://ohm.bu.edu/~pbohn/__Engineering_Reference/pcb_layout/pcbmatrix/Component%20Zero%20Orientations%20for%20CAD%20Libraries.pdf) industry standard. 
- Can only generate quadratic Quad form factor packages.
- Can only generate quadratic BGA packages.
Footprints will be required in the upcoming multi-shot bottom vision. 
The footprint generator can currently create three types of footprints:
- **Dual** form factor packages.
- **Quad** form factor packages.
- **BGA** packages.
The generators are parametrized …

Feature / Footprint Generator

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceFiducialLocator.java

Tiny fix to #1438 to log the _inverse_ AffineTransform too.
You actually need the inverse for the `ReferenceLinearTransformAxis`.
See (updated) Wiki:
https://github.com/openpnp/openpnp/wiki/Transition-Machine-Coordinate-System-through-Planned-Modification

Fix / Also log the inverse AffineTransform.

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/machine/reference/wizards/ReferencePnpJobProcessorConfigurationWizard.java
src/main/java/org/openpnp/spi/JobProcessor.java
src/main/java/org/openpnp/spi/MotionPlanner.java
src/main/resources/org/openpnp/translations.properties

When stepping through a Job, the JobPanel would pause after each steps of the JobProcessor, including some steps that result in no machine motion, either because they are purely logical (like planning the Job), or because a step action is conditional (like loading a compatible nozzle tip when one is already loaded). 
From an operator's perspective, these "empty" steps are confusing, the processor should only pause after the next visible machine motion happened. 
However, from a debugging perspective, when looking at the log, the single steps might still be important. 
The new **Step Next Motion** option on the JobProcessor can switch between the two behaviors. After testing, I concluded the new experience is much more likely what users expect, the new option was _enabled_ by default. 
See …

Feature / Jobs: Step to Next Machine Motion

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java

If not yet set up, show the detected sprocket holes in Show Features.
User request:
https://groups.google.com/g/openpnp/c/-nQ09SWl_nk/m/kRap3zEhBgAJ
Just press the **Preview Vision Features** button when the sprocket holes are not yet initialized. 
See the Wiki:
https://github.com/openpnp/openpnp/wiki/ReferencePushPullFeeder#locations
1. No tests. Code change deemed trivial. Testing branch.
4. No sense for `mvn test` before submitting the Pull Request.

Fix / ReferencePushPullFeeder: Preview Vision Features detects uninitialized sprocket holes

---

src/test/java/VisionCompositingTest.java
src/test/resources/config/VisionCompositingTest/packages.xml
src/test/resources/config/VisionCompositingTest/parts.xml

Implements the `VisionCompositingTest` to test multi-shot bottom vision. It comes with parts and packages, mostly the same large and difficult parts as shown in the [demo video](https://youtu.be/P-ZudS7QQeE). 
Note, these tests run only with pre-rotate bottom vision, where we have multiple passes. This is needed for some of the difficult parts and the large errors used in testing, i.e. corner detection might not yet be very good when the corner is way off the expected location. 
Unit test.
Included in `mvn test`.
1. Self testing.
4. Obviously successful `mvn test` before submitting the Pull Request.

Feature / VisionCompositingTest 

---

src/main/java/org/openpnp/gui/FeedersPanel.java

Remove the nozzle move to pick location from the `FeedersPanel`'s `feedFeederAction`.
User broke nozzle tip, because he rightly did not expect the move to pick location when he pressed the **feed** button on a drag feeder:
https://groups.google.com/g/openpnp/c/qOlRCwZeIWw/m/HlDPTYjqAAAJ
Use the **feed** button just for the feed:
If you want to position the nozzle as well, use the **position nozzle** button _explicitly_:

Fix / Remove Nozzle Move from `feedFeederAction`

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceDragFeeder.java

Remove the redundant `pickLocation` variable on the `ReferenceDragFeeder`, using the `location` directly. 
The unnecessary copy may lead to a stale pick location, as described in the #1016 discussion.
No change.
1. It will hopefully be tested in the testing version (ongoing discussion).

Fix / ReferenceDragFeeder: Remove redundant `pickLocation` variable.

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/resources/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder-CircularSymmetryPipeline.xml

With help from **Jan** and **vespaman** from the discussion list, the `ReferencePushPullFeeder` pipeline handling and **Auto-Setup** was improved. 
1. There are now two stock pipelines shipped, the classic one for color-keyed feeders ("green-screening") and a new one that tries to detect the sprocket holes using the circular symmetry stage.
2. The pipeline type is automatically selected in **Auto-Setup** (tries types until successful).
3. The user can also manually select and reset to the pipeline type in the Wizard.
4. The pipeline type is cloned along with the pipeline.
5. Auto-Setup now suppresses detected hole lines that are too close to the pick location. If the stage mistakenly detects the pockets as sprocket holes (which can happen with 0402 pockets, which have an unfortunate …

Feature / ReferencePushPullFeeder smarter Auto-Setup

---

src/main/java/org/openpnp/gui/wizards/CameraVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/camera/AbstractSettlingCamera.java
src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java
src/main/java/org/openpnp/machine/reference/camera/calibration/AdvancedCalibration.java
src/main/java/org/openpnp/spi/Camera.java
src/main/java/org/openpnp/util/NanosecondTime.java
src/main/java/org/openpnp/vision/pipeline/stages/ImageCapture.java
src/test/java/VisionUtilsTest.java

[Camera Settling](https://github.com/openpnp/openpnp/wiki/Camera-Settling) already contains various methods to detect whether a camera image has settled down, i.e. whether all motion and vibration has ceased in the potentially lagging video stream. 
There is a passive **FixedTime** wait method, as well as advanced methods based on frame comparison. The latter have the advantage of being _adaptive_, i.e. only after aggressive machine motion will the camera settling take longer, whereas for little adjustment motion (like in typical vision iteration) it will be much faster. Unlike with **FixedTime** we don't have to settle (literally) for the worst case. 
Frame comparison is done pixel-by-pixel, i.e. moving edges are detected _indirectly_ because their displacement changes a pixel value from …

Feature / Motion Detect Settle Method

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/util/OpenCvUtils.java
src/main/java/org/openpnp/vision/FluentCv.java
src/main/java/org/openpnp/vision/pipeline/stages/DrawCircles.java
src/main/java/org/openpnp/vision/pipeline/stages/DrawEllipses.java
src/main/java/org/openpnp/vision/pipeline/stages/DrawRotatedRects.java

Use anti-aliased OpenCV drawing on circles and lines, where appropriate.
Before:
After:
Note: anti-aliasing was not used on mask drawing where a binary pixel mask is required. 
Better looking results.
No change.

Feature / Anti-Aliased OpenCV Drawing.

---

src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/vision/pipeline/stages/DetectCircularSymmetry.java

The [DetectCircularSymmetry stage and method](https://github.com/openpnp/openpnp/wiki/DetectCircularSymmetry) has become very successful as a tuning-free and robust way to detect circular features such as fiducials and nozzle tips in computer vision. 
However, it has shown some limits when it has to compete with other nearby features that happen to have an (interrupted) tangential match with the wanted circular diameters. As a typical example: on paper carrier tapes 0402 pockets are confused with sprocket holes. Another example are texture patterns that happen to have a circular weight either randomly or from LED reflection highlights etc. (for both examples see the animation below).
The new **SymmetryScore** method selection provides alternative score functions to reject …

Feature / More Robust CIrcular Symmetry Detection

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/util/UiUtils.java
src/main/java/org/openpnp/vision/Ransac.java
src/main/resources/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder-CircularSymmetryPipeline.xml

- Make `ReferencePushPullFeeder` Auto-Setup more robust by allowing interrupted sprocket hole lines.
- Option for `Ransac` to search for interrupted lines.
- Improve the stock `ReferencePushPullFeeder` circular symmetry pipeline to use #1456.
- Bonus: Fixed a bug in the fiducial test pipeline editing handler (Asking _"Do you want to null?"_ and pressing _Yes_ would throw).
See discussion:
https://groups.google.com/g/openpnp/c/N6IVhO_xbrw/m/PSOT0qaaAQAJ
See #1450 for usage. See also #1456 for _inside_ details.
1. Tested with user images.

Feature / ReferencePushPullFeeder Auto-Setup More Robust.

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceHeadConfigurationWizard.java
src/main/java/org/openpnp/spi/Head.java
src/main/java/org/openpnp/spi/base/AbstractHead.java

Introducing a selection of simple vacuum pump control methods. Provides alternatives to the rapid on/off when parts are picked and placed. The new methods allow keeping the pump going longer, perhaps establishing a more constant vacuum level and [shorter dwell times/faster established level](https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration%3A-Vacuum-Sensing#dwell-times--establish-level) on picks. 
Furthermore, these methods allow for seamless "[sniffle probing](https://github.com/openpnp/openpnp/wiki/Contact-Probing-Nozzle#method-selection)" ([watch video](https://youtu.be/9uFxV1-vnXw?t=50)).
Switching control to **None** allows the pump actuator to be configured as such (assigned to the head) without also getting the control forced on you. This is useful for those machines …

Feature / Vacuum Pump Control

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java

`SimpleOcr` stage pipeline properties are now all qualified. See [73602633b0](rev:73602633b0). But one check in `BlindsFeeder` was missed.
User report: see  #1459.
No change.
1. User test.

Fix / BlindsFeeder: Qualified Pipeline Property "SimpleOcr.alphabet"

---

src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java

Fixes using the XML serializer to convert nozzles to contact probe nozzles after the persisting of actuators was changed in 4c537b5bb2385c2a99787af7ae8e5e19e6346c9a.
The `loaded()` handler should check for `head != null` and it must be called again _after_ assigning the head. 
The `loaded()` handler was consolidated with the already existing `AbstractHeadMountable.applyConfiguration(Configuration)`.
User error report.
https://groups.google.com/g/openpnp/c/9yuV0pyEnks/m/RQtMQB2VAgAJ
No change.
1. Tested with reported user `machine.xml`

Fix / ContactProbeNozzle.convertToContactProbe(ReferenceNozzle)

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java

In Auto-Setup, if there are other `ReferencePushPullFeeder`s, it will try to clone settings over from just a very generic template (there is nothing yet known about the part or tape, so "smart" template selection is not possible). Once vision is successful, it might have identified a part using OCR, so it performs a secondary clone, as the template selection might now be (more) accurate. 
However, since #1450 the Auto-Setup performs an automatic pipeline _type_ selection (ColorKeyed or CircularSymmetry). So the secondary clone might just _undo_ that selection, by cloning the _wrong type_ pipeline from another, likely not yet or wrongly configured `ReferencePushPullFeeder`. 
Therefore, this fix _excludes_ the pipeline from the secondary clone, _if_ the pipeline was _typed_. 
Also adds …

Fix / ReferencePushPullFeeder: Exclude Typed Pipeline In Secondary Clone

---

src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java
src/main/java/org/openpnp/machine/reference/solutions/NozzleTipSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipConfigurationWizard.java
src/main/java/org/openpnp/model/VisionCompositing.java

The **Max. Part Diameter** property on the nozzle tip has become an important setting for multiple interconnected functions. It determines how large a part can be, when it is loaded on said nozzle tip. More specifically it determines the camera view diameter that is considered active in bottom vision. Some computer vision pipeline stages are parametrized to limit their detection to that area (for speed). The same diameter is used by [Background Calibration](https://github.com/openpnp/openpnp/wiki/Nozzle-Tip-Background-Calibration) to limit the background area considered active. Anything outside that area is assumed to be masked. Ultimately, a MaskCircle stage in the pipeline is parametrized to apply this mask.
The mask is effectively used to eliminate peripheral camera view elements that …

Fix / Respect Max. Part Diameter in Vision Compositing

---

src/main/java/org/openpnp/util/ImageUtils.java

The `ImageUtils.emulateCameraCapture()` function adapts a source image to the native camera resolution and dimension, i.e. the image is presented as if captured. This optionally uses an `upp.txt` file stored side-by-side to the source image, to adjust for true scale. The function is used in the `ImageRead` pipeline stage, so one can test camera images from other users with true scale, while having one's own camera setup. 
Because of integer math (rounding), this failed if the dimensions of the camera frame vs. source image differed by an odd (not divisible by two) pixel number. This PR fixes that, by making the left/right, upper/lower border different by one pixel.
Bug.
No change.
1. Tested with an actual user image (where this was discovered) …

Fix / ImageUtils.emulateCameraCapture() Odd Pixel Adjustment

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

Feature  in NamedCsvImporter for parsing new field (additional comments) for add to column `comments` in `Placements` section.
Useful feature for insert comments to board from own cad design:
https://groups.google.com/g/openpnp/c/0ARswEbQ1m8
In csv file add field named: "Addcomment" (additional comment)
so when import to openpnp, column comments will be populated
1. Tested in real environment
4. Successfull `mvn test` before submitting the Pull Request.

parsing new additional comment (optional) field when import csv (NamedCsvImporter)

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleVacuumWizard.java

Some machines can perform a blow-off air pulse when parts are placed. This PR improves the handling of this:
- So far one had to define a blow-off level on each package, which is too much work. This PR adds a default blow-off level on the nozzle tip for a more central configuration:
- For some machines it is assumed that the blow-off command happens to implicitly close the vacuum valve too, i.e. the valve has a sort of _three-state operation_. For this behavior one can enable the **Closes Vacuum Actuator?** option on the nozzle (default is _enabled_, to get the same behavior as before):
- Otherwise, the place operation now closes the vacuum valve, even if a blow-off value is set. This also allows for actuators on different drivers/controllers (previously impossible).  
- The Issues & …

Feature / Better Blow-Off Control

---

.github/workflows/build_and_deploy.yml
src/main/java/org/openpnp/gui/support/NozzleItem.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java

This PR fixes these issues and bugs:
1. Indicates the part on the nozzle in Machine Controls (explains the state of the vacuum pump/need for a "discard" action).
1. Remove race conditions in the machine task finishing phase, in case of exception. Cleanup handlers must still be able to execute driver actions, no `Thread.interrupt()` must yet be pending.
1. Issues & Solutions: Prevent a null pointer exception when there is no `oldNozzleOffset`, because the solution was reopened.
User reports.
Regarding 1. and 2.: See https://groups.google.com/g/openpnp/c/eUylM0_tFns/m/1GCbFgo-AwAJ
Regarding 3: See https://groups.google.com/g/openpnp/c/2KL7a3vKqyQ/m/0ch23yA4AwAJ
No change in use.
1. Tested by provoking exceptions in queued tasks. Final test must be reproduced on user machine.
5. Did follow …

Fix/Machine Tasks Cleanup On Exceptions

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java

Improvements in Issues & Solutions for the SwitcherCamera:
- Add switcher actuator Issues & Solutions (reports missing actuator, helps with missing G-code).
- Make it an Issues & Solutions Error when a SwitcherCamera has **Preview FPS** other than zero.
- Make it an Issues & Solutions Error when a SwitcherCamera has **Suspend during tasks?** disabled.
As an aside:
-  Bugfix: camera view snapshots (double-clicking on Camera View) must be captured in a machine task. Otherwise we get a deadlock via SwitcherCamera.
User report:
https://groups.google.com/g/openpnp/c/4xLCCosrOFQ/m/W5kSewh-AwAJ
See the Wiki that was improved with this PR and is also linked from the Issues & Solutions:
https://github.com/openpnp/openpnp/wiki/SwitcherCamera#configuration
1. Tested with real camera and …

Feature/SwitcherCamera Issuess & Solutions

---

src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceFiducialLocator.java
src/main/java/org/openpnp/util/UiUtils.java
src/main/java/org/openpnp/util/VisionUtils.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java

The fiducial locator needs a package, or more specifically its footprint, to parametrize the pipeline for the right shape and size. Pipeline parameters are now handled more strictly, therefore a missing package will result in an exception. 
_Image by DG_
When a user is on the **Parts** or **Packages** tab, the associated package can be determined. But this is not the case when you are on the **Vision** or **Machine Setup** tab.
This PR fixes this by defaulting to the homing fiducial as the test case for editing the pipeline. 
- Defaults the fiducial locator to the `FIDUCIAL-HOME` package for pipeline editing.
- Readying the `FIDUCIAL-HOME` part was refactored to `VisionUtils` (formerly a part of `VisionSolutions`).
- `FIDUCIAL-HOME` vision-settings are now _inherited_ when the pipeline …

Fix/Fiducial Locator Default Package for Pipeline Editing

---

src/main/java/org/openpnp/machine/reference/camera/SwitcherCamera.java
src/main/java/org/openpnp/spi/Machine.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java

Fixes deadlocks in the SwitcherCamera. 
For some time now, it is no longer admissible to actuate actuators on the UI thread, therefore a `machine.execute()` future is needed in the `SwitcherCamera`'s `internalCapture()` method . In some circumstances this can create a deadlock through the static `switcher` map shared by all switcher cameras. 
The `notifyCapture()` method normally wakes up the camera thread to broadcast a frame, either one already captured before, or a fresh one. On a `SwitcherCamera` that is currently not switched-to, this will provoke an actuator switch, which again must execute on the machine thread. If we notify the camera from a machine thread, the camera thread will likely create a busy timeout on the `machine.execute()`, as the original machine thread is still …

Fix / SwitcherCamera deadlocks

---

src/main/java/org/openpnp/machine/reference/camera/AbstractBroadcastingCamera.java
src/main/java/org/openpnp/machine/reference/camera/SwitcherCamera.java
src/main/java/org/openpnp/machine/reference/driver/wizards/AbstractReferenceDriverConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

This is a roundup of small fixes/adjustments in the testing round.
In case a primary/secondary fiducial location X, Y was set _manually_, but the diameter was not (still null), it resulted in a NullPointerException (see user report in the Justification). 
Note, this never happens when these are setup through **Issues & Solutions** (as is recommended). 
Adds missing (high) baud-rates for serial connections (drivers). The missing baud-rates were taken from the jSerial "posix" implementation. 
Note: some baud-rates were already in there that are not in the "posix" list, i.e. those will (still) not work on *ix OSes, but may work on Windows, these are:
- 14400
- 56000
- 128000
- 250000
- 256000
Due to problems still reported after #1500 and #1503, a new approach to the SwitcherCamera was …

Fix/Roundup Testing

---

src/main/java/org/openpnp/machine/reference/driver/ReferenceDriverCommunications.java
src/main/java/org/openpnp/util/Collect.java

The OpenPnP driver's `ReferenceDriverCommunications.writeLine()` should work as _one_ underlying call to `writeBytes()` to prevent any breaking up of USB packets etc. 
Added needed `byte[]` implementation of `Collect.concat()`, as Java [does not seem](https://stackoverflow.com/questions/41060384/java-template-with-primitivedata-types-as-c-templates) to support primitive data types for `T` in templates.
Breaking up of packets was reported here:
https://groups.google.com/g/openpnp/c/eM8ISf0dbqc/m/2WBtaRQkBQAJ
No change for the user.
1. Tested in simulation with the GcodeServer (socket vs. serial is irrelevant, because `writeLine()` is case class code).
3. No changes in the …

Fix / Atomic ReferenceDriverCommunications.writeLine()

---

src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OpenPnpCaptureCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

Fixes/improvements contained in this PR:
- New option to freeze OpenPnpCaptureCamera properties, so they will be reapplied to the camera after reopening the device. Properties not persisted correctly, or changed in other OpenPnP configurations, or other web cam applications will be restored. Connecting the wrong cameras will no longer overwrite configured property settings.
- Fixes some layout inconsistencies on the camera Device Properties form. 
- Improves the stepping through static exposure probing by Issues & Solutions. A maximum of 64 probes will be done, probes are properly stretched over the full range (no need to be a integer step size multiple).
- Fix a threading issue where the Issues & Solutions apply method would compete for the camera lighting/switching actuator, which will …

Fix/Camera Properties

---

src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java

Based on #1510, reapply frozen camera properties when the machine is homing.
User reports that immediate reapplication on camera open does not take.
https://groups.google.com/g/openpnp/c/SpkC2XxB_jk/m/v7DsejnEBQAJ
See Wiki (additional instruction added):
https://github.com/openpnp/openpnp/wiki/OpenPnpCaptureCamera#freezing-camera-properties
1. Cannot test, reporting user must test.

Reapply frozen camera properties when the machine is homing.

---

src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

In Issues & Solutions, change the suggested `Acceleration` setting G-code so that a missing `Acceleration` variable would suppress the whole line.
Affects `HOMING_COMMAND` and `MOVE_TO_COMMAND`.
Marlin does not "ok" lines that do not contain any G-code (comments-only). This in turn disrupts confirmation flow control.
See the user reports:
https://groups.google.com/g/openpnp/c/ZKTx8tGYr4E/m/fWnjPyYFBgAJ
Just use Issues & Solutions to suggest a `HOMING_COMMAND` or `MOVE_TO_COMMAND`.
1. Tested in simulation using GcodeServer. Confirmed acceleration setting commands are suppressed. Marlin users must ultimately test it. …

Fix / Issues & Solutions: missing accleration suppresses whole G-code line

---

src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java

Fixes FPS Test button causing OpenPnP to hang
if camera is lost/unplugged or stops receiving frames.
estimateCameraFps function has a while loop which only exits when the camera indicates it has a new frame.
Assuming hasNewFrame returns false when the camera is unplugged then exiting the while loop when the timeout expires will prevent OpenPnP from hanging endlessly.
Hopefully fixes bug reported [on the Google group](https://groups.google.com/g/openpnp/c/mtA_lAcj6GY).
N/A. Problem was seen on loss of camera during an FPS test.
1. How did you test the change? Compile tested only - I don't use OpenPnPCaptureCamera and this FPS test is specific to that.
2. Coding style followed.
3. No spi or model changes.
4. Maven tests passed, but don't cover the changed code.

Return from estimateCaptureFps after timeout even if no frames are actually captured.

---

CHANGES.md
src/main/java/org/openpnp/gui/BoardPlacementsPanel.java

Fixes context menu selections for Set Enabled and Set Error Handling on the Boards tab so that they properly propagate to all instances of the Placement.
Bug fix for all users.
No special instructions - this just makes it work as expected.
1. How did you test the change? **Setup a job with multiple instances of a board, changed the Enabled status and the Error Handling for some placements on one of the boards, and then used the context menu on the Boards tab to set them to their default state. Verified that all instances of the placements in the job were now back at their default settings.**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **Yes.**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages …

Fixed propagation of Set Enabled and Set Error Handling context menus

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java

Based on #1429 this fixes a case where a user sets up a `ReferenceStripFeeder` manually, i.e. not using the **Auto-Setup**, and also never positions to the pick location. or otherwise tests or uses it before saving Configuration. 
Upon reloading, the feeder will then receive a faulty -90° **Rotation in Tape** adjustment, per #1429.
See the case:
https://groups.google.com/g/openpnp/c/y06sdptgGjc/m/5PL9ji-vAgAJ
No change.
1. To be tested by reporting user.

Fix / ReferenceStripFeeder: Ensure the EIA-481 flag before persisting

---

src/main/java/org/openpnp/gui/panelization/ChildFiducialSelectorDialog.java
src/main/java/org/openpnp/gui/processes/MultiPlacementBoardLocationProcess.java
src/main/java/org/openpnp/gui/support/Helpers.java
src/main/java/org/openpnp/gui/support/TableUtils.java
src/main/java/org/openpnp/gui/viewers/PlacementsHolderLocationViewer.java
src/main/java/org/openpnp/model/Panel.java
src/main/java/org/openpnp/model/PseudoPlacement.java

Fixes the rotation angles for pseudo-placements and pseudo-fiducials on the bottom of panels. Also changes the Multi-Placement Alignment Process to individually select each placement in the Job Placements table as it runs so that the correct footprint will be overlayed on the top camera view.
Will help anyone who uses the Multi-Placement Alignment Process to align their boards and panels. Note, the incorrect pseudo-placement and pseudo-fiducial rotation angles only affected how the footprints were overlayed on the top camera view - they had no affect on the actual alignment results since their rotations are not used in computing the placement affine transforms.
No changes to usage instructions.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **Added all …

Fix pseudo-placement rotations and display correct footprint during multi-placement alignment process

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/machine/reference/driver/AbstractReferenceDriver.java
src/main/java/org/openpnp/machine/reference/driver/wizards/AbstractReferenceDriverConfigurationWizard.java
src/main/java/org/openpnp/spi/Driver.java
src/main/java/org/openpnp/spi/MotionPlanner.java
src/main/resources/org/openpnp/translations.properties
src/test/java/BasicJobTest.java
src/test/java/HttpActuatorTest.java
src/test/java/ReferenceBottomVisionOffsetTest.java
src/test/java/ReferenceBottomVisionTest.java
src/test/java/SampleJobTest.java
src/test/java/SamplePanelizedJobTest.java
src/test/java/VisionCompositingTest.java

On unhomed machines the current position is not known by the controller, they often power-up/reset to zero coordinates at the position the machine randomly happens to be. Positioning the machine to a prerecorded location can therefore lead to a crash. Only few actions in OpenPnP check if the machine is homed and prevent that. Most notably the generic **Position to Location** buttons do not.
This PR makes this safer. In doing so, it distinguishes two types of motion:
- Jog motion is allowed, when the current controller machine position is positively known to OpenPnP. It is assumed that the user observes the true machine position and will avoid jogging into obstacles. 
- Non-jog motion is generally disallowed on unhomed machines. 
The machine homing safety checks are centrally administered …

Feature/Ensure Machine Homing Before Motion

---

pom.xml

This was authored by @vonnieda, doing the last step (I hope).
> Pull in openpnp-capture v0.0.27, which fixes a double release.
See 
https://github.com/openpnp/openpnp/issues/1538#issuecomment-1508986172
1. Tested in https://github.com/openpnp/openpnp-capture/pull/65. 
Ultimate test only practical after merge.
3. [Coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style) does not apply.
4. No changes in the `org.openpnp.spi` or `org.openpnp.model` packages.
5. Successful `mvn test` in https://github.com/openpnp/openpnp/actions/runs/4702235136 before submitting the Pull Request.

Features/Upgrade OpenPnpCapture

---

src/main/java/org/openpnp/machine/reference/wizards/ReferenceMachineConfigurationWizard.java
src/main/java/org/openpnp/model/BoardLocation.java
src/main/java/org/openpnp/spi/Machine.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java
src/main/resources/org/openpnp/translations.properties

This PR add a default board location property to the ReferenceMachine Locations section. This location will be used as default when a board is added to a job. 
On machines with a dedicated board registration system like CHM-T36 or 48, the location of boards on the machine is always the same. With this preconfigured location there is almost no board position setup required for new boards anymore.
The default default board location is the same as the hardware coded location currently in place. So without specifying a default board location nothing will change. Once the default board location is specified boards added to jobs will automatically have this location as reference. 
1. How did you test the change? Be descriptive. Untested code will not be accepted. _I've set the default board …

Default board location

---

src/main/java/org/openpnp/gui/PackageVisionPanel.java
src/main/java/org/openpnp/gui/importer/KicadModImporter.java
src/main/java/org/openpnp/gui/support/Icons.java
src/main/java/org/openpnp/gui/support/KiCadImporter.java
src/main/java/org/openpnp/model/Footprint.java
src/main/resources/icons/kicad-logo.svg

This commit implements a simple parser for KiCad footprint files (*.kicad_mod). Rectangular, rounded rectangular, circular and oval pad shapes are supported. Trapezoid and custom pad shapes are ignored. A FileDialog is openened to select a file. Imported pads are stored in a list inside the KiCadImporter class and transfered to the Footprint instance once parsing is completed.
This feature is useful to ease importing of footprints, as manual generation isn't handy and the generator templates don't fit to complex footprints. Even people not using KiCad at all can benefit from just using the very extensive KiCad footprint library, which is just a directory structure with footprints. KiCad is a very mature open-source electronics design suite and in my opinion open-source projects should …

Feature: Import pads from KiCad footprint file

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/SchultzFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/SlotSchultzFeederConfigurationWizard.java

User reported malfunction of "SchultzGetPitch" actuator. It is likely the following fixes will resolve that:
1. Make sure all `SchultzFeederConfigurationWizard` and `SlotSchultzFeederConfigurationWizard` actuator actions are done in machine tasks.
2. Remove unnecessary `machine.isEnabled(()` tests inside these machine task.
3. Perform all UI changes from actuator reading in deferred way to prevent race conditions.
See user report:
https://groups.google.com/g/openpnp/c/SFUnSoJpUig/m/FjN4IjZlCAAJ
Some actuators were still read in `UiUtils.messageBoxOnException()` handlers instead of `UiUtils.submitUiMachineTask()`.
1. User has to do the ultimate test with hardware.
4. …

Fix/Schultz Feeder Actions in Machine Tasks

---

pom.xml
src/main/java/org/openpnp/Main.java
src/main/java/org/openpnp/gui/IssuesAndSolutionsPanel.java
src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/SubmitDiagnosticsDialog.java
src/main/java/org/openpnp/gui/components/MarkupTextPane.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleCameraOffsetWizard.java
src/main/java/org/openpnp/model/Solutions.java
src/main/java/org/openpnp/util/UiUtils.java

OpenPnP **Issues & Solutions** has introduced routine linking to the OpenPnP Wiki. The documentation is often very important to understand the issues and solutions at hand. Sometimes it is the only thing available, i.e., users are asked to follow the instruction in the Wiki in order to resolve the issue, no automatic action is available.
Unfortunately, on some systems the Java Desktop support for browsing is _very strangely_ not implemented. On my Kubuntu for instance, pressing any of the info buttons only shows this: 
The PR  now unifies the URI browsing through `UiUtils.browseUri()`. This could also prove useful to automatically map to a different base-URL and/or documentation system in the future. See also #1543.
The new  `UiUtils.browseUri()` first tries the …

Feature / Better URI Browsing

---

CHANGES.md
src/main/java/org/openpnp/machine/reference/signaler/ActuatorSignaler.java

This PR changes the way ActuatorSignaler works be filtering out duplicated calls to the actuator if the job state did not change.
When using an ActuatorSignaler to signal a finished job, the actuator is called for each step of the job. This slows the job down dramatically even if no GCode is omitted. (Unfortunately with the NullDriver and the pnp-test.job I was not able to measure a difference in CPH.) One can see this behavior by filtering the log (at Trace level) for "Signaler". Without this PR there a many calls to the actuator with state false. With this PR applied, there are two calls with state false and one with state true.
In addition, this PR allows to use machine coordination with the actuator without a significant performance penalty. 
There is no change in usage. Its just that …

Actuator signaler remove duplicate calls

---

src/main/resources/org/openpnp/sort-properties.sh

WindowBuilder seems to shuffle the `./src/main/resources/org/openpnp/translations.properties` file whenever the slightest text change is made in the interactive editor. Despite intensive search I have not found a way to stop that.
This PR adds a simple bash script to sort the `translations.properties` file (more or less) the same way the normal externalization seems to do. By using a canonical sort order, the changes to the file become minimal in terms of versioning.
The diff in the  `translations.properties` file should be kept minimal.
After each change that affects the  `translations.properties` file, execute the `./src/main/resources/org/openpnp/sort-properties.sh` script in a bash class shell. The script creates backups for safety.
1. Tested in several past PRs. Now published.
2. The …

Feature/Script to sort Translation Properties

---

pom.xml

Revert-revert the Maven `openpnp-capture-java` dependency back to 0.0.27.
This undoes #1558.
The version of `openpnp-capture-java` turned out _not_ to be the culprit. Instead it the Install4j packaged Java 17 has a bug/incompatibility, caused in turn by Microsoft's inherently bad design of COM.
See
https://bugs.openjdk.org/browse/JDK-8270269
To get it, upgrade to the latest `test` version of OpenPnP.
For Windows users, to workaround the installer's Java 17 problem for now, proceed as follows:
Download Microsoft's Java 11 .msi
https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-11
and install it
https://learn.microsoft.com/en-us/java/openjdk/install#install-via-msi
and then start openpnp using this command:
```sh
java --add-opens=java.base/java.lang=ALL-UNNAMED …
```

Fix/Revert-revert the Maven openpnp-capture-java dependency

---

pom.xml

Upgrade to openpnp-capture-java 0.0.28-0.
See 
- https://github.com/openpnp/openpnp-capture/pull/68
- https://github.com/openpnp/openpnp-capture-java/commit/52374b9730a8d3d78163bbad8c4b8761469743ab
Upgrade `test` version.
1. Tested local develop on Windows, using Java 11. Real test will be after deploy, using the installer-packaged JVM. 
2. The [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style) does not apply.
4. Used `mvn -DskipTests clean package` to build and then test the faulty functions under Windows.

Fix / Upgrade to openpnp-capture-java 0.0.28-0.

---

pom.xml

This bumps the `org.openjdk.nashorn` Java Script engine to 15.4 for support of Java 17 and later.
Users reported that Java Script scripting was disabled:
https://github.com/openpnp/openpnp/pull/1562#issuecomment-1563996722
See also:
- https://github.com/openpnp/openpnp/pull/1475#issuecomment-1236712135
- https://github.com/szegedi/nashorn/wiki/Using-Nashorn-with-different-Java-versions#using-nashorn-on-java-11-to-14
Upgrade to the newest `test` version.
1. After updating the POM I confirmed the java script engine works under Java 11. Support of Java 17 will only be confirmed once deployed.
2. The [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style) does not apply.
3. No changes  the `org.openpnp.spi` or `org.openpnp.model` packages.
4. Successful `mvn …

Fix / Bump Nashorn Java Script Support for Java 17+

---

src/main/java/org/openpnp/scripting/Scripting.java

This makes sure the `NashornScriptEngineFactory` class is always loaded and registered in OpenPnP, even if the classpath is not given.
See #1563 and before that https://github.com/openpnp/openpnp/pull/1562#issuecomment-1563996722
Upgrade to newest OpenPnP `test` version.
1. Tested by using Java 17 explicitly.
4. Successful `mvn package` before submitting the Pull Request.

Make sure the NashornScriptEngineFactory is always loaded with OpenPnP.

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/resources/org/openpnp/translations.properties

This PR fixes and enhances the Board Protection, where Jogging motion is safety-checked against collisions with boards.
- The Machine Controls Safety Tab switch is now just named **Board Protection** and default-enabled, i.e. straight positive logic (formerly "Override" = inverted logic).
- Renamed the translation property key so translations will be lost, but not falsely left in inverted logic.
- Refactored `MachineControlsPanel.checkJogMotionSafety()` for central unified checking.
- In addition to "arrow" jogging, also check "Move tool to camera location" and (less likely relevant) "Move camera to tool location" for safety against boards.
- When the selected tool is jogged, _all_ the HeadMountables attached to the same Head will now be checked for safe motion.
- A dual nozzle machine …

Fix / Board Protection

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java

Fixes a user interface problem first described [here](https://groups.google.com/g/openpnp/c/N2sTPcGlPgI) in the user forum. Basically, the context menus for setting the Enabled, Side, Type, and Error Handling states of placements in the Job tab's Placements Table were not correctly handling the case where the board's definition should have been being updated versus just the board instance in the job.  This only occurs when a single instance of any particular board design is at the top level of the job, i.e., there are not multiple copies of the board in the job nor is it a member of a panel in the job.
Fixes a user interface bug that impacts all users.
No real instructions for use - the context menus now work as they should.
1. How did you test the change? **Was able to duplicate the …

Fix UI bug in Job Placements Table

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/SerialPortCommunications.java

Users suddenly reported UI hangs with TinyG. After extensive debugging, revisions retracing and half a day of hair pulling, it turned out that reinstating a serial port read timeout solved the issue. Strangely the that abolished the timeout is over a year old. I can only speculate that the recent change from Java 8 to Java 11/17/19 somehow exposed the issue.
See PR #1378 and specifically, [this line-change](https://github.com/openpnp/openpnp/pull/1378/files#diff-dec1db26d6c2776bbec8768f001ed16c73d22f02ef6a455149992cdb83d227edL113), where the timeout of 500ms was removed:
```java
SerialPort.TIMEOUT_READ_SEMI_BLOCKING | SerialPort.TIMEOUT_WRITE_BLOCKING, 500, 0);
```
When the hang happens, I see no obvious OpenPnP threads being blocked in deadlock or similar. Strangely the AWT thread is …

Fix / Serial read hang

---

pom.xml
src/main/java/org/openpnp/machine/reference/driver/GcodeAsyncDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/ReferenceDriverCommunications.java

This provides a temporary workaround for the current issue with `jSerialComm`.
* Block jSerialComm at 2.9.3 until https://github.com/Fazecast/jSerialComm/issues/505 is resolved.
* Keep serial read timeout as introduced by https://github.com/openpnp/openpnp/pull/1569.
* Fix the bug in https://github.com/openpnp/openpnp/issues/1235, resume reading on timeout.
* Keep https://github.com/openpnp/openpnp/pull/1508 (which was found to cause problems too), it is equally solved by the read timeout.
* Add a debug log when a read timeout happens during a write, which would indicate that the writer was blocked until the reader timed out, which may or may not point to an internal read/write/full-duplex deadlock. Which might cause the problems through https://github.com/openpnp/openpnp/pull/1508.
* As …

Fix / jSerialComm temporary workaround

---

src/main/java/org/openpnp/gui/importer/CsvImporter.java

This PR fixes the import of comment columns if they are the last column in the file. It also fixes the behavior of an unchecked _Create Missing Parts_ checkbox. Previously no part was assigned to any placement in that case. Now an existing part is assigned and the placement is skipped if the part does not exists. A warning is logged in the later case.
In addition this PR changes placements whose ID starts with "FID" or "REF" followed by a digit to type fiducial.
Both problems where reported at https://groups.google.com/g/openpnp/c/JjAjSdWhUkA/m/BLhpk9dyAwAJ.
There is no change in usage.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **The code was tested using the supplied .csv file.** …

- Fixed line lenght check if a comment column is present

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/model/BoardLocation.java

This change moves the initialization of board and panel locations from the BoardLocation default constructor to the addBoard and addPanel methods of JobPanel.
Initialization of board locations in the BoardLocation default constructor can fail due to accessing of the machine configuration (to obtain the default board location) before the machine configuration is completely loaded. The consequence of this is that the Panels tab is always empty after a restart of OpenPnP and there will be erroneous errors reported in the log implying the *.panel.xml files are corrupted when in fact they are fine. This change moves the initialization to its proper place, namely where a new board or panel is being added to the job.
No special instructions for operators.
1. How did you test the change? Be …

Fix bug introduced by PR1547

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java

This PR enhances the Job Placements table by immediately updating the Status if a placement is enabled or disabled using the mouse.
It's inconvenient to change the row after a placement has been enabled or disabled until the status is updated. By studding the code I learned, that the space bar could be used for that purpose as well and that there the Status is immediately updated.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using the debugger and test job**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require …

Job Placements UI enhancement

---

src/main/java/org/openpnp/gui/JobPanel.java

This PR enhances the job panel by selecting the board/placement/feeder/part that has thrown the exception.
Its more convenient if the part/feeder/placement/board that cased an exception is already selected when acknowledging the error message.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **I've used the test job and let it run into all sorts of errors**
4. Be sure to run `mvn test` before submitting the Pull Request. If the …

job exception handling enhancement

---

src/main/java/org/openpnp/gui/processes/CalibrateCameraProcess.java
src/main/java/org/openpnp/machine/reference/camera/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/camera/calibration/AdvancedCalibration.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraCalibrationWizard.java
src/main/java/org/openpnp/spi/base/AbstractCamera.java

This change adds two new attributes to AdvancedCameraCalibration to save the image width and height that were in effect when calibration was run. This allows the Calibration Results/Diagnostics to display correctly even if the camera is no longer connected to OpenPnP.
Also moved setting of the camera's defaultZ out of applyCalibrationToMachine to CalibrationSolutions just ahead of the call to applyCalibrationToMachine. This still sets defaultZ automatically when calibration is run via Issues&Solutions but allows it to be changed by the operator when running calibration manually.
Additionally, added calls to firePropertyChange in all AbstractCamera setters so that any GUI fields bound to those will properly update.
Aids in off-line debugging.
No special instructions for the operator.
1. …

Save raw cropped image size and use it for diagnostics display instead of checking the image size

---

src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/BottomVisionSettingsConfigurationWizard.java
src/main/java/org/openpnp/spi/Nozzle.java
src/main/java/org/openpnp/spi/PartAlignment.java
src/main/java/org/openpnp/spi/base/AbstractNozzle.java

In **Test Alignment** we have the option **Center after the test**, which centers the part in the camera view in its final aligned position.
This PR improves this a bit by taking another picture after the part has been centered, making sure the lights are switched on and the camera image settled. Plus it also displays the final (overall) offsets result (including any adjusted rotation mode offset). This image is then frozen for two seconds, immediately overriding the one displayed from the last alignment pass, which was still not centered: 
This now also works, if the camera has FPS 0, i.e., where it would not have worked before. 
This popped up in the course of supporting a user problem. 
https://groups.google.com/g/openpnp/c/ln98xGXjzsY/m/gVm0FTTRBAAJ
IMPORTANT NOTE: although this …

Feature/Better Test Alignment, Centering

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java
src/main/java/org/openpnp/machine/reference/camera/AbstractSettlingCamera.java
src/main/java/org/openpnp/machine/reference/camera/SwitcherCamera.java
src/main/java/org/openpnp/machine/reference/driver/GcodeAsyncDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/spi/base/AbstractHead.java

In an effort to optimize OpenPnP for speed, there are some inexplicable pauses observed in the user's log. This PR adds some additional logging wherever `Thread.sleep()` is called in the regular code, so deliberate dwelling can be eliminated.
The `Neoden4` and `Photon` classes were not changed, these seem to do `Thread.sleep()` as part of their "protocol timing".
This PR also declares the command queue draining inter-thread signalling `boolean` `confirmationComplete` as `volatile`, and logs if it took longer than 1ms. However, the user in question does not actually use confirmation flow control, so this is merely for other users.
See the discussion:
https://groups.google.com/g/openpnp/c/JUCRTa6pKbQ/m/q0zz8RFbAwAJ
To get timing related logging, set the logging level to TRACE.
1. Tested …

Fix / Add logging to all regular Thread.sleep() calls

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

This is just a minor extension of #1593 to also log any blocking on the read queue.
See  #1593.
See  #1593.
See  #1593.

Fix / Log the time it takes to get a response from the read queue

---

src/main/java/org/openpnp/machine/reference/SimulationModeMachine.java

The `SimulationModeMachine` simulates an actuation delay by sleeping for 50ms (now 5ms). Unfortunately, the sleep was not nested into the proper `if`-block that checks if the `SimulationModeMachine` is present and in simulation mode.
This is the culmination of #1593 and #1595.
Obvious.
The actuation sleep is logged with TRACE messages of this kind:
`2023-11-02 13:16:25.007 SimulationModeMachine TRACE: BLOW-OFF simulate actuation, sleep 5ms`
1. Tested `mvn test`, and by user based on #1595.

Fix / SimulationModeMachine simulated actuator delay

---

src/main/java/org/openpnp/gui/support/LengthCellValue.java
src/main/java/org/openpnp/gui/support/MonospacedFontWithAffineStatusTableCellRenderer.java
src/main/java/org/openpnp/gui/support/RotationCellValue.java
src/main/java/org/openpnp/gui/tablemodel/PlacementsHolderLocationsTableModel.java

This change fixes a bug where the placement affine transform was erroneously being cleared when the operator selected cells in the Job table for editing but did not actually change anything. It also makes the shading of the location cells visible (which indicates the status of the affine transform) even when the row in the Job table is selected.
Fixes a bug and makes the affine transform status visible even when the row is selected.
No special instructions for the operator.
1. How did you test the change? **Duplicated the issue and after the code changes observed that the affine transform no longer gets reset when one of the location cells is selected for editing, but nothing is changed. Also checked that the affine status shading is now visible even when the row is selected.**
2. Did you …

Fix erroneous reset of placement transform when cells are selected for editing but are not changed

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

This PR extends the text status messages the Job Processor generates by the effected nozzles name.
On multi-nozzle machines and placement optimization enabled, the nozzle name is valuable information that better indicates the current state of the machine, especially while stepping.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **operation is not effected, so there is nothing to test**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and …

JobProcessor: include nozzle name in text status messages

---

pom.xml
src/main/java/org/openpnp/machine/neoden4/Neoden4CameraDriver.java
src/main/java/org/openpnp/machine/neoden4/Neoden4CameraHandler.java

This PR adds Linux support for the Neoden 4 cameras using [libneodencam](https://github.com/jsphpl/libneodencam).
Always good to support Linux, right?
In order to use OpenPNP with the Neoden 4 camera driver on Linux, you need to build and install [libneodencam](https://github.com/jsphpl/libneodencam) as described in the linked repository. Everything else works the same as on Windows. I will update the Wiki with Linux instructions for Neoden 4 when this PR is merged. Until then, instructions can be found in the libneodencam repo.
The Neoden4CamDll interface is renamed to Neoden4CameraDriver because libneodencam.so exposes the same interface as the Windows dll.
Neoden4CameraHandler now has a `driver` property that is populated with the respective native library on initialization. If the OS …

Linux support for Neoden 4 cameras

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java

After computer vision has detected sprocket holes purely by vision criteria, the `ReferencePushPullFeeder` applies various criteria to further filter sprockets holes for setup and calibration. This PR adds logging diagnostics when sprocket holes (or sprocket hole lines) are dismissed due to geometric constraints. Constraints are derived from EIA-481 standards.
The vision-detected holes are filtered after the pipeline:
1. The exact size of the detected hole must match the EIA standard (1.5mm), within a certain tolerance.
2. The holes must appear in a straight line.
3. The holes in the line must appear with a pitch of 4mm (at least two of them, can be multiple of 4mm).
4. The line must have a certain distance, not too close to the pick location (avoid mixing up part pockets with sprocket …

Feature / ReferencePushPullFeeder: Diagnostics for Sprocket Hole Detection

---

src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

When `adjustHeadOffsetsDependencies()` was refactored to be used universally inside `setHeadOffsets()`, I forgot to remove it in `VisionSolutions`.
User report:
https://groups.google.com/g/openpnp/c/FZiiQQ_NGXs/m/eTsJ1kMIAQAJ
1. Just used `mvn test`, hope the reporting user will test with the actual issue on his machine.

Fix /  adjustHeadOffsetsDependencies() applied twice

---

src/main/java/org/openpnp/gui/components/LocationButtonsPanel.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleToolChangerWizard.java

This PR slightly enhances the UI for Manual Change Location on the Tool Changer page of the nozzle by forcing the relevant nozzle as the tool when capturing locations.
The Manual Change Location is only of relevant for the nozzle that is to be currently configured. Therefore it makes no sense to capture the location of any other nozzle.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using the debugger**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require …

Manual Change Location Enhancement

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceTrayFeeder.java

This PR fixes the getPickLocation method of the ReferenceTrayFeeder by always calculating it based on current UI values. In the previous implementation the location was static and only updated on feed operations. This is not ideal as there is no direct relation to the UI and its not obvious to the user.
I tried to use a ReferenceTrayFeeder and failed because I was not able to verify its configuration prior use. Changing feedCount or offsets did not help to check the locations a part would be picked up from.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **I used a simulation machine and verified that UI changes are immediately reflected as well as feed and pick operations work as before.**
2. Did …

Fix getPickLocation of ReferenceTrayFeeder

---

src/main/java/org/openpnp/machine/reference/feeder/ReferenceRotatedTrayFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceRotatedTrayFeederConfigurationWizard.java

This PR fixes the getPickLocation method of the ReferenceRotatedTrayFeeder by always calculating it based on current UI values. In the previous implementation the location was static and only updated on feed operations. This is not ideal as there is no direct relation to the UI and its not obvious to the user.
I tried to use a ReferenceRotatedTrayFeeder and failed because I was not able to verify its configuration prior use. Changing feedCount or offsets did not help to check the locations a part would be picked up from.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **I've used a simulation machine and tried manual validation and feed/pick operations to work. Unfortunately the value entered in the …

Fix getPickLocation of ReferenceRotatedTrayFeeder

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/support/MessageBoxes.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/spi/JobProcessor.java
src/main/java/org/openpnp/spi/Nozzle.java
src/main/java/org/openpnp/util/UiUtils.java

This PR enhances the usability for machines with manual nozzle tip changing enabled by skipping the interruption to load the nozzle tip if a load will immediately follow.
At present the job processor generates two interrupts to change one nozzle tip, one for the unload and a second for the load. The unload is useless and a waste of time if a load is known to immediately follow.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using a simulation machine**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for …

Skip interrupting to unload a nozzle tip while loading a new tip

---

src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceMachineConfigurationWizard.java
src/main/java/org/openpnp/spi/Machine.java

This PR provides auto-loading of the most recent job on startup on request.
If the new configuration option "Auto-load most recent job?" on the Configuration tab of the machine is enabled and there are known recent jobs, the most recent one will be loaded automatically. Per default this option is disabled.
At least with debugging is tedious to always load the same job to test with. And if OpenPnP starts with the "Untitled.job.xml" anyhow, why not load the most recent one, which is known to have some meaning for the user anyhow.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **I used it while developing other code** …

add an option to automatically load the most recent job

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/spi/PnpJobPlanner.java

This PR is a rewrite of PR #1574 by transforming the optimization into steps which are inserted into the workflow of the JobProcessor. sortLocation is removed from PnpJobPlanner and [pick|align|place]location added. This locations are precalculated in the plan() step and then used for the individual optimizations via a getter and an enum for selection.
The old implementation was not clean and did not provide the option to extend the optimization by taking the next location into account.
There is no change compared to PR #1574 exception that the optimization is a little better now because the next location is taken into account. Therefore jobs shall process a little faster now.
1. How did you test the change? Be descriptive. Untested …

Sort placements rewrite

---

OpenPnP.install4j

Attempt to fix camera entitlement on macOS Monterey - Sonoma.
The Test build does not request access to Camera devices at least on macOS Monterey and Sonoma and the app crashes with the message `This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an com.apple.security.device.camera key with a string value explaining to the user how the app uses this data.`
However, the `NSCameraUsageDescription` key is present and while testing I noticed a difference between having whitespaces vs not in Info.plist. There is also a difference about these carriage returns between the Test build and the Develop build, where Develop doesn't have them and works as expected.
The whitespace was introduced in …

Fix broken Camera permissions on macOS

---

src/main/java/org/openpnp/gui/components/VisionCompositingPreview.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/model/VisionCompositing.java
src/main/resources/org/openpnp/machine/reference/vision/ReferenceBottomVision-BodyPipeline.xml
src/main/resources/org/openpnp/machine/reference/vision/ReferenceBottomVision-DefaultPipeline.xml
src/test/java/VisionCompositingTest.java

In [Vision Compositing](https://github.com/openpnp/openpnp/wiki/Vision-Compositing) a.k.a. multi-shot bottom vision, the corner shots are done with the nozzle holding the part off-center of the camera, so the corner is above the camera center. This means that another nozzle (with part) might come into the view of the camera and disrupt the detection, as illustrated in this user shot: 
Credits: Krzysztof Kozłowski
Similarly, some machines might have a limited backdrop shade, so unwanted bright reflections etc. might enter the view from the side.
Making corner shots almost always means that only half the camera view is actually used for detection. This PR exploits this and adds a "part mask" to the pipeline to mask off the unwanted side of the camera view. The new mask is applied _in …

Feature  / Vision Compositing Part Mask

---

src/main/resources/org/openpnp/translations.properties

Changes some labels in simulated camera Wizards for clarity.
See #1636.
No change.
1. No separate tests for translations only.

Feature / Change labels in simulated cameras

---

src/main/java/org/openpnp/util/FeederVisionHelper.java

This is a minor enhancement for debugging the search for ransac lines between sprocket holes
When something is off about the lines found, only a generic debug error of "No line of sprocket holes can be recognized". This adds some additional details before that error.
* Ran all tests with mvn
* Yes
* No changes
4. Be sure to run `mvn test` before submitting the Pull Request. …

FeederVisionHelper - Add Ransac lines debug message

---

src/main/java/org/openpnp/machine/pandaplacer/AbstractPandaplacerVisionFeeder.java

In this feeder type, some code inherited from ReferencePushPullFeeder, specific to feeder cloning, was resetting the CV pipeline for each Auto Setup action.
This change removes the automatic reset so a custom vision pipeline can be used when needed for Auto Setup, since BambooFeeders do not implement cloning.
Without the cloning functionality, it is not correct to reset the CV pipeline automatically when there is a dedicated button on the UI for it. The reset action should be intentional as the user requires.
In the BambooFeeder objects, the Auto Setup button will no longer automatically reset the vision pipeline, therefore a customized pipeline can be used for both auto calibration and in-job calibration. …

AbstractPandaplacerVisionFeeder - Remove automatic cv pipeline reset

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java

This PR addresses several issues:
A move to safe Z is usually performed by the head, for all its attached nozzles (theoretically, all kinds of `HeadMountable`, e.g. Actuators too). In the order they are defined in the Machine Setup, each is moved to the Safe Z Zone. For nozzles with shared Z axes (cam and negated axis), the Safe Z Zone is two-sided, i.e., it has a lower and a upper limit. If a nozzle was _above_ the safe Z zone, it was previously _also_ brought down into the Safe Z zone. This happened when the _other_ nozzle sharing its Z axis was currently positioned below Safe Z. This second nozzle therefore gets no say in that effective move to Safe Z. With Dynamic Safe Z (where the part height is added to the safe Z coordinate), this resulted in an insufficient move to Safe Z. A …

Fix / Safe Z and Bottom Vision Issues

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java

Fixes the fix of #1656, I took the wrong end of the Safe Z Zone (some old code mistakenly left over).  :sweat_smile:
Also made the Z axis `P` button jog to the _effective_ Safe Z (i.e. Dynamic Safe Z with part height accounted for) instead of the Safe Z.
See #1656.
See #1656.
See #1656.
Quickly tested with `P` button.

Fix / Wrong end of the Safe Z Zone.

---

src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

The user may choose to use a generic G-code setup instead of using `M115` to try and auto-discover [known controller firmwares](https://github.com/openpnp/openpnp/wiki/Motion-Controller-Firmwares):
https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions#connect-milestone
As a side effect, there is also no `M114` (report position) pattern detection taking place. Therefore the valid axis letters of the controller are not available to Issues & Solutions. As a consequence it cannot suggest the `POSITION_REPORT_REGEX` correctly. Instead it proposes an invalid empty regex with no axes.
This bug will be fixed by the PR. 
To still get a decent `POSITION_REPORT_REGEX` proposition, all the usually available axis letters conformant with [NIST …

Fix/Issues & Solutions: Axis letter fallback for generic drivers

---

src/main/java/org/openpnp/gui/BoardPlacementsPanel.java
src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/PackageVisionPanel.java
src/main/java/org/openpnp/gui/PackagesPanel.java
src/main/java/org/openpnp/gui/PanelDefinitionPanel.java
src/main/java/org/openpnp/gui/PartsPanel.java

This patch removes leading and trailing whitespace in part IDs etc which are created using the gui. It is easy to get extra whitespace when text is copy/paste from a source such as a datasheet, and undesirable to create an ID with leading and trailing whitespace.
This patch affects all uses of `JOptionPane.showInputDialog` where the input is used as an ID.
All existing uses already check for null input, which occurs when the cancel button is pressed.
This change uses `String.trim` to remove leading and trailing whitespace, after that null check.
Additionally, if that results in an empty string, it behaves the same as if `showInputDialog` returned null.
1. How did you test the change? - Tested manually, with entering empty strings, strings with some unwanted whitespace, and strings with no …

Avoid accidental leading or trailing whitespace in Part IDs etc

---

src/main/java/org/openpnp/vision/pipeline/stages/MinAreaRect.java

This is a bug fix
Openpnp has two implementations inside the minAreaRect vision stage. The first implementation hands over to opencv. The second implementation, in java, supports extra parameters leftEdge, rightEdge, topEdge, bottomEdge, and searchAngle.
The switch between the two implementations only checks the first four parameters. If a non-default `searchAngle` is specified (and the other four parameters have the default true value) then it uses the opencv implementation, and ignores the users specified searchAngle.
This fix checks for a non-default searchAngle as a reason to use the full-featured implementation.
Is it useful for a vision pipeline to specify a non-default searchAngle?
I occasionally see misdetection of sot23 components.... sot23 are approximately triangular, and there …

bug fix: Search angle in minAreaRect

---

src/main/java/org/openpnp/gui/components/VisionCompositingPreview.java

fixes #1669
This makes the problem go away. The visual appearance of the preview is now correct.
I have not confirmed that real vision still works - I am away from the machine at the moment. But the only changes are to xxxx*Preview*.java so this should be ok.
I dont have great confidence that I have found exactly the right places to add/remove the -1, and maintained the comments correctly. Feedback would be appreciated.
1. How did you test the change? - manual test, using the problem packages in issue 1669
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? - yes
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. - all tests pass

Fix for mirrored vision compositing preview

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/model/VisionCompositing.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java
src/test/java/VisionCompositingTest.java

**This is a provisional pull request** shared for review. So far this has only been tested in simulation and I want to test it on the machine.
This patch contains some bug fixes for vision compositing and part size checking, some defensive changes to prevent such bugs hiding in future, and some unit test extensions.
The part size check logic was not previously validating the measured sizes. While there was not much scope for this to go wrong when its data was provided by minAreaRect,  some other bugs described below in composite vision were causing the measured size to be NaN. NaN size values lead to contradictory error messages from the part size check logic. This patch adds some validation.
The final stages of vision compositing has various floating point divisions, without checking for …

Various size check and vision compositing fixes

---

src/main/resources/org/openpnp/machine/reference/vision/ReferenceBottomVision-BodyPipeline.xml
src/main/resources/org/openpnp/machine/reference/vision/ReferenceBottomVision-DefaultPipeline.xml

The default bottom vision pipeline operates by
* using thresholds to find  some interesting shapes
* finding contours for those shapes
* eliminating some contours where the area is too small to be interesting
* drawing the outline of those contours to recreate the shapes
The current pipeline redraws the contours using a line thickness of 2 pixels, which artificially inflates the shapes. This leads to a (small) inaccuracy in component size and position.
It is better to redraw the contours with a line thickness of 1 pixel, to accurately reproduce the original shapes and eliminate this unexpected inaccuracy.
Note this affects the line thickness used during the vision pipeline processing. A different line thickness is used for user feedback.
Openpnp aims for sub-pixel accuracy elsewhere.
1. …

Default bottom vision pipeline inaccuracy due to contour thickness

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java
src/main/resources/org/openpnp/machine/reference/vision/ReferenceBottomVision-DefaultPipeline.xml

In [Nozzle Tip Background Calibration](https://github.com/openpnp/openpnp/wiki/Nozzle-Tip-Background-Calibration), the **Brightness** method worked with a grayscale image, but then used the **HSV Value** channel for masking. The **Value** channel is not the same as grayscale brightness, i.e., it boosts colorful elements, fully saturated colors even reach the maximum value (255). Therefore, in case of background elements being rather colorful,  the pipeline failed to mask them properly.
This PR fixes this bug by also using the **HSV Value** channel for calibration, so the two always match.
Note: arguably, the **HSV Value** channel is not ideal for masking the background in the **Brightness** mode, i.e. it does not truly indicate "brightness". Vivid colors will show as too bright and …

Fix / Background Calibration: Greyscale vs. HSV value

---

pom.xml
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/camera/GstreamerCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/GstreamerCameraConfigurationWizard.java

This is a rebased and updated version of PR #1023 which was merged but later reverted.
It was reverted because at the time gstreamer dependencies broke the population of a dropdown selection option in OpenPnPCaptureCamera. Specifically the resolution dropdown for UVC cameras under Device Settings would set the value and it would be stored to machine.xml, but on restart of OpenPnP the dropdown would show the initial entry again.
Since some interest was shown in GStreamerCamera on the discord server, I retested and discovered that this is no longer the case. The dropdrown populates correctly with the stored value. I'm resubmitting a rebased version of the camera.
Original PR text follows, slightly tweaked...
---
This camera uses a textbox to specify an arbitrary gstreamer launch pipeline. …

Add updated GStreamerCamera based on AbstractBroadcastingCamera

---

src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

In **Issues & Solutions**, preliminary nozzle offsets are captured by looking from the side at a nozzle tip manually centered on a fiducial. 
- Watch a (somewhat outdated) [video of that step](https://youtu.be/md68n_J7uto?feature=shared&t=109).
We can only get a very rough X, Y (gu)estimate from that, which is later refined by precision nozzle offset calibration (a.k.a. ["confetti calibration"](https://github.com/openpnp/openpnp/wiki/Calibration-Solutions#calibrating-precision-camera-to-nozzle-offsets)). 
Side note: the manually captured preliminary nozzle offsets are required to perform the confetti calibration in the first place, i.e. it would otherwise not know at what offsets to pick the confetti that was centered in the camera.
Sometimes it becomes necessary to reopen/redo the …

Issues & Solutions: Still use the Z from captured nozzle offsets 

---

src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/KinematicSolutions.java

I have recently been redoing my machine setup and calibration using Issues&Solutions, where previously I had followed the opulo-recommended manual method. The end result is very much better with I&S.
However the I&S process was not exactly smooth. I had a few false starts which I was able to correct myself, and a few major misunderstandings which where corrected by the helpful participants on the mailing list. I have made a few changes to the wiki to help the next user following my footsteps; for example noting that there is a maximum diameter for the nozzle-offset-calibration confetti. This patch contains a couple of messages which I think are best delivered through the software.
Mark pointed me to [the convention that working Z is …

Issues solutions guidance

---

src/main/java/org/openpnp/machine/pandaplacer/AbstractPandaplacerVisionFeeder.java

Update to Pandaplacer feeder in sync with this: https://github.com/openpnp/openpnp/pull/1673
Like PR1673, the Pandaplacer feeders will work for more use cases.
no change
1. How did you test the change? 
- Same as PR1673
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? 
- Yes
- no changes
- done

Pandaplacer Feeder - use full camera image for auto setup

---

src/main/java/org/openpnp/machine/reference/ReferenceMachine.java

This adds an extra scripting event related to homing. Openpn already has `Machine.AfterHoming` which gets called when homing is entirely complete. This adds `Machine.AfterDriverHoming`, which gets called between the two phases of the homing process: after homing all the drivers, and before calibration using the homing fiducial.
I hope this new scripting event is generally useful, even if my specific use for it is niche.
I have described my requirement on google groups. My gcode homing has not been 100% reliable. I'm working on a fix for that, but until then I would like my openpnp to be able to validate the gcode homing before running its calibration cycle. I can implement that in a script! This PR means I can run the script at the right time.
It is used like any other scripting event.
I …

an extra script event

---

src/main/java/org/openpnp/gui/BoardPlacementsPanel.java
src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/spi/JobProcessor.java

This is a preliminary Pull Request. I have tested on simulated machine, but would like to test on a real machine before merging.
This is based on a discussion at https://groups.google.com/g/openpnp/c/7bxPtQ3MpdA/m/jW3iQIgVBQAJ
> There is one aspect of my placement workflow that feels more complicated than it should be.
> Openpnp alerts if a mis-pick is detected by bottom vision. If I see there is genuinely no part on the nozzle then I want to redo the pick. Is there an easy way to do that? My best solution at the moment involves manually finding the right feeder, checking that the right nozzle is selected, pressing the "feed and pick" button, and restarting the job. But that feels all very manual, and error-prone. Is there an easier way?
This patch automatically selects the UI features …

Automatically selecting nozzles and linked tables after a job interruption

---

src/main/java/org/openpnp/Main.java

Tooltip timeout 4s is too short to read long texts
General GUI usability improvement.
Mouse over a control with tooltip
Timeout is prolonged to 1min. The text are rather long and require focus on info so long dismiss timeout (or move mouse away to disappear immediately)

prolong tooltip delay from 4s to 60sec.

---

src/main/java/org/openpnp/gui/components/IssuePanel.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/model/Solutions.java

This PR provides the option to skip auto-focus calibration of the up looking camera via issues & solutions.
At present there is no convenient option for force bottom vision to take place at a certain Z level because issues & solutions always uses auto-focus to set the camera Z.
A checkbox has been added to the solution allowing to disable auto-focus. There is no other impact.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **on my physical machine**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive …

Skip auto-focus on up-looking camera calibration

---

src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

This PR changes the POSITION_REPORT_REGEX Issues & Solutions suggests by allowing any number of whitespaces between axes.
If controllers send compressed position reports without whitespaces between the axes, the default regex does not match. With this modified version compressed reports are matched as well.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using my physical machine**
4. Be sure to run `mvn test` before …

Support compressed position report

---

src/main/java/org/openpnp/gui/BoardPlacementsPanel.java
src/main/java/org/openpnp/gui/JobPanel.java
src/main/java/org/openpnp/gui/PanelDefinitionPanel.java
src/main/java/org/openpnp/gui/panelization/PanelArrayBuilderDialog.java
src/main/java/org/openpnp/gui/viewers/PlacementsHolderLocationViewer.java
src/main/java/org/openpnp/gui/viewers/PlacementsHolderLocationViewerDialog.java
src/main/resources/org/openpnp/translations.properties

Board placement preview did show all placement for all boards in jobs. But when e.g. PnP boards depanelized from panel in one job then all placement are generated in the same area because boards are placed in machine origin position. So selection what placement should be displayed is welcome
General GUI usability improvement. 
Job panel grid row selection is passed to job viewer. So user can precisely select what to inspect.
Note: the board rectangles are displayed at original panel (KiCAD) location as there is no way how to get what is origin of particular subboard. I suggest add new parameter in list ... board origin. In this case the viewer can display correct board borders. Also PnP command "go to board origin" could move head to correct position.
JobViewer is extended to support …

Jobviewer board selection support to visualize particular boards

---

src/main/java/org/openpnp/gui/components/CameraView.java

This corrects the image scaling when the highest quality rendering option is selected so that the un-zoomed image always fits within the camera view pane regardless of how the camera view pane is sized by the operator. This change only effects what is visible to the operator on the GUI and has no effect on the machine vision performed internally by OpenPnP. 
Prior to this change, depending on how the camera view pane was sized, it was possible for portions of the camera image to extend beyond the border of the camera view pane and thus be hidden from the operator even when the image is zoomed all the way out. 
Right click in the camera view and select Rendering Quality -> Highest Quality (best scale), the camera images will now be scaled so that they always fit within the camera view pane …

Fix the camera view Highest Quality Rendering option so that the image always fits in the view

---

src/main/java/org/openpnp/machine/reference/solutions/KinematicSolutions.java

This fixes issue #1735. A bug where the "unconventional Z axis" I&S warning could not be dismissed.
The bug was introduced in my PR #1682. In that PR markmaker suggested I make this warning message its own Solution, and pointed out some code to copy. But I copied too much of the surrounding code.
The fix mostly involves deleting code. Changing the class to `PlainIssue` makes this a warning that can be dismissed, rather than an issue with code that implements its own status changes.
I propose including this bug fix in the imminent release. Issue #1735 turns this warning into a hard error, which is problematic for users affected by this situation. We want to warn them that their approach is unconventional, but not block them from continuing.
It would be good for the user who found this bug …

this warning should be a PlainIssue

---

src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java

When Issues & Solutions replaces the default ImageCamera with the OpenPnpCaptureCamera, the new replacement does not have a vision provider assigned.  This change corrects that by copying the image provider from the old camera to the replacement camera.
If an operator starts with a clean configuration (no machine.xml) and follows the I&S steps, the cameras end up without any vision provider assigned to them. This problem is not obvious until the vision provider is requested when certain feeders (ReferenceLeverFeeder for one) are used.
No special instructions, just use I&S as usual.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **Started OpenPnP without a machine.xml file and proceeded through the I&S steps until images from the real machine cameras …

Copy vision provider when I&S replaces cameras

---

src/main/java/org/openpnp/gui/components/ComponentDecorators.java
src/main/java/org/openpnp/gui/support/LengthConverter.java
src/main/java/org/openpnp/gui/tablemodel/FootprintTableModel.java
src/main/java/org/openpnp/gui/tablemodel/PartsTableModel.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/model/Length.java

There is lots of code which is written as if the `Length` class is immutable. But, to my great surprise, it is not! This patch removes the Length methods which change its value. It changes a small amount of code which uses those methods to use alternatives which return a new `Length` object.
For example, class `ReferenceNozzleTip` has `public Length getMaxPartHeight()` to allow other code to access an attribute.
It also has `public void setMaxPartHeight(Length maxPartHeight)` to allow other code to change that attribute.
It is somewhat surprising that this property could also be changed by code such as `tip.getMaxPartHeight().setValue()`. Thats not how we want this API to be used, and it is not how we want future APIs (exposing a `Length` attribute) to be written. The presence of methods …

change Length class to be immutable

---

src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/resources/org/openpnp/translations.properties

The main window status bar shows the DRO machine position: `X:0.000     Y:0.000     Z:0.000     C:0.000    `
This patch adds this right-click popup menu, with a single "Copy" menu item to copy that text on to the clipboard.
It is sometimes useful to share machine positions outside of Openpnp.
A right-click menu should be discovered by anyone needing this feature.
Previously a mouse click with any button would toggle the DRO "tare" feature. This changes the right-click button behavior.
* The function for updating the DRO on screen has been refactored, with a new function for calculating the DRO string. This display feature has been manually tested
* The left-click (and middle-click!) tare feature work
* The …

A menu to copy the machine position to the clipboard

---

src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraCalibrationWizard.java
src/main/resources/org/openpnp/translations.properties

Removed probable Russian text that accidently was entered in the English translation file and fixed GUI formatting to correctly display verbiage associated with the Crop All Invalid Pixels/Show All Valid Pixels slider.
Bug fix to remove confusing Russian language tool tip being displayed to English operators. 
No special instructions needed.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **Observed the camera Advanced Calibration tab and verified that the verbiage is now displayed in English and in the correct location.**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **Yes.**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional …

Fix Advanced Camera Calibration GUI problems

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/scripting/ScriptFileWatcher.java
src/main/java/org/openpnp/scripting/Scripting.java

In PR #1688, Jan noted that in more than 99% of all events, no script will run. This patch introduces 2 optimisations for this common case.
Openpnp has to do quite a bit of work to establish that no script will be run. It has to open the `~/.openpnp2/scripts/Events/` directory, iterate over *all* the file entries in the directory, and process the file names.
In this patch, the event name is added to a HashSet if that iteration completes without finding any matching script files. When the same event is triggered a subsequent time, the HashSet allows it to skip the (relatively) expensive filesystem IO work.
Timing with java `System.nanoTime()` shows that this saves approximately 40µs on a system with no event scripts, on each call to `Scripting.on()`. Each saving is tiny, but it adds up. …

Most script events do nothing

---

src/main/java/org/openpnp/gui/components/AutoSelectTextTable.java

When selecting row/cell in a JTable object, Parts, Packages, Jobs, .... then first click on any cell beyond current column opens cell editor or makes checkbox action. It is potentially dangerous because majority of clicks are for row selection. Especially at Job tab to select particular part where unless clicked on a "safe" cell then typically opens combobox list where can be made unintended change. Now the editor opens when cell is selected.
General usability improvement
Open e.g. Parts tab, click on a Package cell. Only row/cell is selected. Next click will open combobox list
1. How did you test the change? manually in GUI
2. Did you follow the ? yes
3. no
4. yes

Do not show table cell editor immediately when click on unselected cell

---

src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/HttpActuator.java
src/main/java/org/openpnp/machine/reference/ReferenceActuator.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/AbstractActuatorConfigurationWizard.java
src/main/java/org/openpnp/spi/Actuator.java
src/main/java/org/openpnp/spi/base/AbstractActuator.java

This PR changed the "Before Actuation?" coordination to CommandStillstand as WaitForStillstand is not required.
As discussed on the mailing list, CommandStillstand is sufficient for actuator SET operations and provides a better machine utilization and hence a better performance.
this optimization will work immediately. However, in case of miss configurations where an actuator is actuated and read, the addition "Before Read?" coordination is required where before the "Before Acutation?" was sufficient.
This PR will cause merge conflicts with PR #1699 because both change the implementation of ReferenceNozzle for static dwell time handling.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **This code was used for the tests and demonstration discussed on the …

Actuator coordination

---

src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/gui/tablemodel/PartsTableModel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/model/Part.java
src/main/resources/org/openpnp/translations.properties

Dynamic Safe Z lifts a part just enough to clear the obstacles. This height to which it is lifted is based on part height.
But this goes wrong for parts with through-hole features. For example, mechanical alignment pips, through-hole electrical pins, lenses on down-firing leds, and connectors with features that overhang the side of the board.
This was discussed [on google groups](https://groups.google.com/d/msgid/openpnp/8b21ded0-d044-4cc0-a117-31ff3e6a0498n%40googlegroups.com?utm_medium=email&utm_source=footer)
This PR adds a "Through-Hole Depth" property to Parts. Default zero for backwards compatibility.
There is an extra column on the Parts tab for this new property. There are tooltip messages for the two height fields.
Parts have a new method `getHeightForSafeZ` which is now used in …

Through-Hole Parts and Dynamic Safe Z

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java

This PR fixes sub-ordinate motion merging in situations where a head mountable has a Z offset and the safe z zone is thin. The code does not correctly respect the head mountables offset which makes it look as if its outside the safe z zone. With this PR the missing toHeadLocation() transformation is added.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using simulation machine tuned to reproduce the reported issue, applied the fix and the issue is solved**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification …

fix sub-ordinate motion merging

---

src/main/resources/org/openpnp/machine/reference/vision/ReferenceFiducialLocator-DefaultPipeline.xml

Previously the fiducial vision pipeline would draw circles to highlight the fiducial that had been detected. Several changes were introduced in PR #1719, with the overall result that highlight circles were removed.
This was reported by Tao Qu on [google groups](https://groups.google.com/d/msgid/openpnp/a7aaef82-df39-46bb-b2fb-8aa2221cf8c5n%40googlegroups.com?utm_medium=email&utm_source=footer) -- thank you for the feedback.
1. How did you test the change? Be descriptive. Untested code will not be accepted. 
1. tested in simulated machine
2. code review - this changes one attribute in an xml file.
3. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? -- yes
4. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages …

Fiducial pipeline Hug feedback

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/util/UiUtils.java

This change blocks manual jogging actions when the gui has a modal dialog box open.
If manual jogging hits a soft limit then openpnp shows an error message. However in this condition the jog keys are still active, and it is possible to get many nested error message windows stacked up.
This patch prevents this scenario. On jogging into a soft limit, all further jogging is prevented until the first error message is acknowledged.
This patch also prevents manual jogging when any other error message is open. This is probably a good thing.
This patch also prevents manual jogging in another modal dialog box is open, like a File/Save box. I hope this is harmless.
Java swing experts - can you suggest a better implementation of `isModalDialogBoxOpen`?
n/a
1. How did you test the change? on …

Jogging into soft limits

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/gui/components/CameraViewPopupMenu.java

This pull request changes how the zoom level is calculated, when a `MouseWheelEvent` is received. The calculation is now multiplicative instead of additive as before. The increments are adapted and reduced from 5 to 3 in number. Additionally, the numbers in the the context menu are replaced with text and a tooltip explanation because without any indication of the current zoom level, these numbers are meaningless.
During testing two issues emerged:
- The new increments need to be larger than 1, while previous increments could also be 1 or smaller. Because these settings are stored using the Preferences API, they prevail and cannot easily be reset. If the previous increment was 1, zooming is effectively disabled. If the previous increment was smaller than 1, zooming is inverted. This is …

Change camera view zoom behaviour from linear to log

---

src/main/java/org/openpnp/gui/components/PipelineControls.java
src/main/java/org/openpnp/machine/reference/vision/wizards/BottomVisionSettingsConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/FiducialVisionSettingsConfigurationWizard.java

A bug was reported [on google groups](https://groups.google.com/d/msgid/openpnp/68004a08-08f1-45b4-b57b-3bc42599c357n%40googlegroups.com?utm_medium=email&utm_source=footer).
This is a consequence of #1717, merged as part of #1719.
Pipeline `ParameterNumeric` stages hold their properties in engineering units, for example the 'Minimum Detail Size' property uses mm². `ParameterNumeric` then needs to perform a units conversion when updating other vision stages which might not use engineering units, for example the `FilterContours` `minArea` property uses pixel count. On my system the default 0.01mm² minimum detail size corresponds to 55 pixels.
#1717 fixed a bug where this conversion did not occur in some cases, and `FilterContours` was incorrectly using a size limit of 0.01 pixels.
This bug …

CvPipeline always needs a "camera" property

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

PR #1699 added driver-side-delaying. This includes a new configurable gcode command, and fallback logic for the upgrade scenario when that gcode has not been configured.
This PR extends the fallback logic if the DELAY_COMMAND an empty string. Previously the fallback logic was only enabled if DELAY_COMMAND was null.
I&S guides the user to set some appropriate gcode DELAY_COMMAND. The I&S solution shows that the gcode is initially blank, and shows the new recommended gcode.
After performing this upgrade, a curious user might want to revert back to java-side-delaying. Maybe to perform a comparison, or maybe because the effect was not quite what he expected. However this does not work. This fallback logic is triggered only if the gcode variable is null, but the gui gcode editor can only set …

An empty delay command should be treated the same as a missing delay command

---

src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

This is a draft PR. Not for action yet.
This PR adds some Marlin-specific logic to I&S
I&S normally recommends that *Location Confirmation* is enabled and *Confirmation Flow Control* is disabled. Openpnp needs at least one of these options enabled for isWaitingForDrivers completion with async gcode processing. This PR changes I&S to recommend the opposite combination for Marlin.
Confirmation Flow Control needs to be enabled because Marlin needs application-level flow control. RtsCts flow control is insufficient. This seems unlikely, but:
a. With Confirmation Flow Control disabled I have observed Marlin reporting that commands were corrupt towards the end of a long block of gcode commands, as might be expected from an input buffer overrun.
b. Marlin has optional …

Marlin-specific I&S logic.

---

.git-blame-ignore-revs

This PR adds the .git-blame-ignore-revs file.
This file lists revisions which should be excluded from "git blame". This is useful for revisions like 14d3f5675e6da7c40e7dcc20cc0e125f9d1e3059 which was a mass update to correct line endings in lots of files. This revision is not semantically interesting, so it is useful to exclude it from "git blame" when investigating the code history.
Github supports this automatically, and the git client can be configured to do so.
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- no code changes
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Gui …

"git blame" ignore some commits

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

This is a proposed fix for issue #1804. The exception stack trace recorded in that issue occurs when `updateFeederIndex` returns its finishing location, using the location of the last feeder visited by the TSM, but that list is empty. This patch detects this case, skips the TSM operation, and simply returns the `startLocation`.
This change conclusively avoids the exception recorded in issue #1804. It has been tested for 2 days of production usage with no further problems observed.
An outstanding task before merging is to prove that this wont leave some other problems. Previously the return value from `updateFeederIndex` could never have been `null`, because it returns a feeder location and feeders always have a location. However sometimes the provided `startLocation` is `null`. I have not …

a possible fix for issue #1804. feeders empty list

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/resources/org/openpnp/translations.properties

It is a bad outcome for a multi-nozzle machine to get stuck using only a single nozzle, while another nozzle is left idle. This occurs if the job reaches a point where the idle nozzle can not find a tip which can handle any of the outstanding parts.
This PR changes the "Nozzle Tips" Job Ordering method with a heuristic to reduce the likelihood of this occuring.
The "Nozzle Tips" method operates by grouping parts according to the nozzle tip, then optimising the order of feeders then placements within each group.
The description in [the wiki](https://github.com/openpnp/openpnp/wiki/Job-Processing#configuration) is that it uses "most efficient order of nozzle tips". A code comment says "keeping all possible tips sorted by amount of placements they can handle will likely provide a good …

Job Optimisation nozzle order

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/util/TravelCost.java
src/main/java/org/openpnp/util/TravellingSalesman.java
src/test/java/TavellingSalesmanTest.java

This PR adds a new metric for travel cost estimation based on axes acceleration and feed rate parameters named TravelCost. This new metric is then used by the traveling salesman and in the job processor for n+1 placement selection. For efficient use, the traveling salesman class has got a new constructor that allows to specify the effected head mountable. This head mountable is then used for travel cost estimation by the traveling salesman algorithm. The implementation defaults to the default camera on the default head and is therefore automatically available everywhere where the traveling salesman is used. The new TravelCost class is also available separately for use eg. within sorting loops.
At present travel cost is not actually taken into account. All optimization is based on …

Better metric for motion optimization

---

src/main/java/org/openpnp/machine/photon/PhotonFeeder.java
src/test/java/org/openpnp/machine/photon/PhotonFeederTest.java
src/test/java/org/openpnp/machine/photon/protocol/helpers/TestBus.java

Avoid a bug if polling the feeder while DST hits.
Using untyped time feels wrong, in Go `Instant`'s equivalent (`time.Time`) is
an hybrid monotonic clock & wall clock and the previous code would just-work™,
but after searching for 5 minutes typesafety in this 2 line case is not worth solving.
I didn't tried running both pieces of code through DST or TZ config change to see what would happen but this feels better.
This PR is stacked on top of #1844

photonfeeder: poll using a monotonic clock

---

src/main/java/org/openpnp/machine/photon/PhotonFeeder.java
src/test/java/org/openpnp/machine/photon/PhotonFeederTest.java
src/test/java/org/openpnp/machine/photon/protocol/helpers/TestBus.java

Poll the feeder at 20hz while we are waiting for it to finish feeding.
The feeder's firmware seems to be very conservative about it's timing estimates and there is marginal costs to polling instead.
This increase CPH by ~15 more %.
None, just profit.
I've tested it, and it works.

photonfeeder: poll the feeder at 20hz rather than waiting the expected feed time

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

NB this PR is intended for the next release.
Lets compare the operator-led recovery scenarios for two common job problems. Assume we are using the "Alert" error handling policy.
If a pick problem is detected by **bottom vision** then an error message is shown and the job is paused. Immediately resuming the job will cause the alignment step to be repeated and it will fail again for the same reason. This cycle can be repeated many times. An operator can fix this problem by correcting the feeder, performing a manual pick operation which loads a part onto the nozze, and resuming the job. The job resumes at the bottom vision step again, and this time it will succeed and the job continues.
If a pick problem is detected by **pick vacuum test** then an error message is shown and the job is …

Check that the nozzle is empty before the job processor does a pick

---

src/main/java/org/openpnp/spi/base/AbstractNozzle.java

This PR fixes the nozzle rotation mode "Minimal Rotation" setting by calculating a rotationModeOffset that results in no rotation when moving to the next pick location. The issue was reported at https://groups.google.com/g/openpnp/c/lZgjIsqylVc.
1. How did you test the change? **using a specially tuned job and dedicated logfile filter tools to monitor nozzle rotation only**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **NA/yes**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. **yes: rotation mode calculation is in …

Fix rotation mode Minimal Rotation

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

#1885 added some extra log messages to investigate #1884. This removes one spurious log message.
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- `mvn test` no longer has spurious error messages; this condition is not an error
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. -- tests pass

#1885 added some extra log messages, but this one is spurious

---

src/main/java/org/openpnp/scripting/Scripting.java
src/test/java/org/openpnp/scripting/ScriptingTest.java
src/test/resources/config/ScriptingTest/Events/testFilename.OtherTextCanBeHere.java
src/test/resources/config/ScriptingTest/Events/testFilename.XYZ.java
src/test/resources/config/ScriptingTest/Events/testFilenameButNotThis.java

Currently event scripts are run if the filename matches `EventName.ext`. With this change openpnp also runs `EventName.YourTextInHere.ext`.
I currently run a `Vision.PartAlignment.After.py` script which does two things:
1. It has extra monitoring on part size. I have product certification reasons for extra scrutiny on part sizes.
2. It observes the part/nozzle offset error, performs the calculations to inverts the feeder-to-vision transform, determines the misalignment at the pick location, and applies a correction to the feeder pick location. This is useful on PushPull feeders which have very reliable position on tape advancement, but the tape can wander left and right a little.
The second feature would be useful on other feeders (some Photon feeder users have expressed an interest) and …

Multiple scripts

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

This change adds waitForCompletion after the final machine activities in a job, and before doing all the other processes that do not involve moving the machine.
I sometimes see what appears to be an extra-long dwell time on the final placement of the job, or a delay before homing the machine at the end of a job. The async driver has received those movements but there is a delay somewhere. It makes sense to ensure make sure that all machine processes are complete at this point.
no changes
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- tested on a real machine
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` …

fix the longer-than-typical dwell time on the last placement of a job

---

src/main/java/org/openpnp/gui/PackagesPanel.java
src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/model/Configuration.java

ConfigurationLister will call listener methods when the configuration loading is complete. Those methods are called immediately if the loading is already complete. The intended purpose of that mechanism is that it allows the callback to use the full complete configuration. But that doesnt always work; the rest of the configuration might be fully loaded, but the object receiving this notification might not be. This adds the lock/unlockListeners methods to the configuration, which allows these callback methods to be deferred until the batch of changes are all complete.
The lock and unlock methods are called in a pair during clipboard paste operations.
This fixes a bug reported on [google groups](https://groups.google.com/d/msgid/openpnp/3417b8d1-36c4-4aad-94a8-ad2a3769dfafn%40googlegroups.co …

Copy/Paste of a Part leaves a null Package reference
