openpnp/openpnp

src/main/java/org/firepick/MarlinDriver.java
src/main/java/org/firepick/MarlinDriverWizard.java
src/main/java/org/openpnp/machine/reference/driver/wizards/AbstractSerialPortDriverConfigurationWizard.java

Change rotation axis from relative E steps to absolute.
Add ConfigurationWizard and move connect() from constructor to setEnabled().
Add support for ATX power supply on/off.
Add code to shut off vacuum pump on setEnabled()... it's loud, you know?

Updates to MarlinDriver.java, add configuration wizard, add baud rate '250000' to abstract configuration wizard

---

.gitignore

Signed-off-by: Paul Jones <paul@pauljones.id.au>

Modify .gitignore to ignore IntelliJ IDEA IDE files

---

src/main/java/org/firepick/driver/FireStepDriver.java
src/main/java/org/firepick/driver/MarlinDriver.java
src/main/java/org/firepick/driver/wizards/FireStepDriverWizard.java
src/main/java/org/firepick/driver/wizards/MarlinDriverWizard.java
src/main/java/org/firepick/kinematics/RotatableDeltaKinematicsCalculator.java
src/main/java/org/firepick/model/AngleTriplet.java
src/main/java/org/firepick/model/Emc02.java
src/main/java/org/firepick/model/RawStepTriplet.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceMachineConfigurationWizard.java
src/main/java/org/openpnp/model/Location.java

Other minor changes: 
* ReferenceMachineConfigurationWizard.java - Added FireStepDriver to combo box.  Modified the MarlinDriver to reflect new package name.
* Location.java - Added method for returning 3d distance between 2 locations
* Renamed / re-organized packages (renamed org.firepick to org.firepick.driver, and added other packages to keep everything organized.

Adding support for FireStep with rotational delta kinematics

---

src/main/java/org/firepick/driver/SmoothieDriver.java
src/main/java/org/firepick/driver/wizards/SmoothieDriverWizard.java

This adds support for Smoothie firmware and the MotionBoard to OpenPnP.
Please refer to my Smoothie Repo https://github.com/DouglasPearless/Smoothieware for information on configuring Smoothie.
It also fixes a small bug in the Marlin Driver too.

Smoothie support

---

src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/importer/EagleBoardImporter.java
src/main/java/org/openpnp/model/eagle/EagleLoader.java

new file:   src/main/java/org/openpnp/gui/importer/EagleBoardImporter.java
modified:   src/main/java/org/openpnp/model/eagle/EagleLoader.java

	modified:   src/main/java/org/openpnp/gui/MainFrame.java

---

src/main/java/org/openpnp/model/eagle/EagleLoader.java

	modified:   src/main/java/org/openpnp/model/eagle/EagleLoader.java

---

src/main/java/org/openpnp/gui/importer/EagleBoardImporter.java

Fixed minor bug where the solder pads were only rotated relative to the package definition and did not take into account the package rotation itself

Fixed minor bug where the solder pads were only rotated relative to the package definition and did not take into account the package rotation itself

---

src/main/java/org/openpnp/machine/reference/ReferenceCamera.java

Crash in Linux related to OpenCV (#230)

---

pom.xml
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/camera/Webcams.java
src/main/java/org/openpnp/machine/reference/camera/wizards/WebcamConfigurationWizard.java

All operating systems with possibility to select camera by name.

Add webcam support

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

- Add an IntegerValue variable to GcodeDriver's actuate(boolean) command, requested by alex: https://groups.google.com/d/msg/openpnp/n0B_xnzGFYA/81GCgnbaIgAJ
- Add a Name variable to GcodeDriver's pick and place commands, to allow the nozzle to be identified.

Added some variables to GcodeDriver

---

src/main/java/org/openpnp/gui/JobPanel.java

Fixed bug in job panel  where the glue dispenser / pnpJobProcessor did not always follow one after another.

Fixed bug in job panel 

---

src/main/java/org/openpnp/gui/LogPanel.java

Saving log panel settings to preferences, related to #288 
Maybe the Hashmap solution for the line limit is not ideal, but adding an extra enum class maybe too much overhead.

Saving UI Settings to preferences

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/NullDriver.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceFiducialLocator.java

Fixing the issues reported - note, i've only managed to simulate this code as my pnp hardware is currently in bits.

Bugfix fid home

---

src/main/java/org/openpnp/machine/reference/signaler/ActuatorSignaler.java
src/main/resources/config/machine.xml

As earlier promised i created an Actuator Signaler
Uses a machine actuator to signal machine or job states like error or run
As is do not have a machine yet i was not able to test it.
Also for some Machine Actuators (like a horn) a Timeout would be nice, but i wonder how to implement that.
Thoughts on this?

Actuator Signaler Class

---

src/main/java/org/openpnp/Main.java

Read and executed the "Your first Pull Request" tutorial by Jason. Hence this request.

executing "first pull" tutorial

---

src/main/java/org/openpnp/gui/tablemodel/BoardLocationsTableModel.java
src/main/java/org/openpnp/gui/tablemodel/FootprintTableModel.java

Making it clearer what "height" and "length" refer to

Making it clearer what "height" and "length" refer to

---

src/main/java/org/openpnp/gui/MachineSetupPanel.java

Added Expand/Collapse checkbox to the Machine Setup tree.

---

CHANGES.md

please give it a native speaker review :)

changes documentation

---

src/main/java/org/openpnp/logging/SystemLogger.java

Just noticed that i did not get the line separator correctly, so i need to fix that because there were two lines for each log

Fixing line separator issue where there were multiple lines

---

src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java

It happens that angle result is found not only at 90 or 270 degreee but 180 too.
This correct the missplacing

corrected bug about rotation

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

I have added in a fix for importing Altium R14 files, currently only supports mm output from altium

#444 Fixed NamedCSV importer for Altium R14 

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/spi/PnpJobProcessor.java

Hello again!
I added in displaying of status on the job placements, something we found to be useful. Makes it easy to follow the progress on the placements. Question is if you consider this correctly implemented or not? 
Once the start button is pressed, it will mark all pending placements with a yellow color. When it's processing a placement it will display a blue color on the Id cell. Once it's done with all placements with the same id, it then marks that cell with a green color. If no placement is going to be done then the cell is left white.
How it looks in action:

Job placement status and progress on Id cell

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

code cleanup, removed trace logging entry.
The logging entry was necessary at time of writing and later, but was hard to follow.
Now, after it have proven it works, this logging could be removed.
This PR don't change anything for the user.
not tested, just diff checked in order it contains only Logging lines.

namedCsv importer change

---

src/main/java/org/openpnp/util/UiUtils.java

To submit a Pull Request for OpenPnP you must use this template or it will be deleted. 
Be sure to review the [[Developers Guide]] and the [Contributing Guidelines](https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md).
Fill out all the details below.
JavaFX has been removed previously but there was some left overs that meant you still need to install the FX dependancy on Debian boxes... http://stackoverflow.com/questions/38943958/how-do-i-make-javafx-work-on-debian-with-the-oracle-jdk8... 
Why should this change be included in …

Feature removejavafx

---

src/main/java/org/openpnp/vision/pipeline/CvPipeline.java
src/main/java/org/openpnp/vision/pipeline/ui/ResultsPanel.java

Added total processing time to CvPipeline and relevant display to CvPipelineEditor

Added total processing time to CvPipeline

---

src/main/java/org/openpnp/vision/pipeline/stages/MaskModel.java

Added ability to filter or mask a `contours` model. Corrected parameter description to make it clearer when the stage is in masking or filtering mode.

Added contours to MaskModel, corrected parameter description.

---

CHANGES.md

To submit a Pull Request for OpenPnP you must use this template or it will be deleted. 
Be sure to review the [[Developers Guide]] and the [Contributing Guidelines](https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md).
Fill out all the details below.
Why should this change be included in OpenPnP? Does it benefit a majority of users or is it specific to one type of user or machine?
How does someone use the …

rotarytrayfeeder added

---

src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/spi/Machine.java
src/main/java/org/openpnp/spi/PartAlignment.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java
src/main/java/org/openpnp/spi/base/AbstractPnpJobProcessor.java
src/main/resources/config/machine.xml

To submit a Pull Request for OpenPnP you must use this template or it will be deleted. 
Be sure to review the [[Developers Guide]] and the [Contributing Guidelines](https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md).
Fill out all the details below.
Mechanism for allowing multiple part alignment stages (i.e. bottom vision camera and mechanical centering jaws). Each alignment stage has a list of parts it can handle, which are editable via the gui. Each alignment stage has its own wizard page added to the parts settings.
Why …

Feature multiple part aligner

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java

followup of #588 
Description
It does prerote removing nozzle runout offset.
Justification
#401 was mentioned , but was not the origin of this PR:
Instructions for Use
Just set the checkbox and prerotation get enabled.
Implementation Details
SMdude have done the tests , a big thank to him.

prerotate fix

---

src/main/java/org/openpnp/machine/reference/ReferenceHead.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/spi/Head.java

ran from Eclipse with start parameter of -DoverrideUserConfig=true
open and ran pnp-test.job.xml ... all is good
created a second nozzle with a tip
change R0805-1K to speed of 1%
picked R0201-1K, jog and observe speed ... fast as expected
picked R0805-1k, jog and observed speed ... slow as expected
discarded R0805-1k, after discard joged and observed speed ... fast as expected
picked R0805-1K, jog and observed speed ... slow as expected
discarded R0201-1K, and observed speed ... slow as expected
discarded R0805-1K, joged and observed speed, ... fast as expected
did testing also on brach with dragfeeder with real parts.  All works.
Be sure to review the [Developers …

fix bug 576 by checking for parts on all nozzles and not just current

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java

code should be self explanatory
next I will look into showing a warning in the case that multiple entries with the same ID exist already in the board on import/loading

check wether ID is unique when adding new placements, throw error if not unique

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/tablemodel/PlacementsTableModel.java

-) rename "Id" -> "ID" in table header of job panel
-) allow settings side and placed status with right click menu also with a single selected line only

minor fixes

---

src/main/java/org/openpnp/gui/JobPanel.java

show warning pop up to reset "placed" status if starting job with all components marked placed already (fiducials and ignored placements are ignored)

show warning pop up to reset "placed" status if starting job with all placed

---

src/main/java/org/openpnp/gui/JobPanel.java

just found and corrected an obvious mistake I made in #688

fixed obvious error, not presenting the right options

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

I'd like to use the event before assembly to program ICs on a simple rig. 
others could use the event, too. an example script is already setup, will be fine tuned and then published in the wiki (until then it might remain here: https://docs.mgrl.de/maschine:pickandplace:ic_programming)
scripting is advanced, so it will be left over for people having knowledge in programming.
on my machine, live.
yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and …

Added preassembly event

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

Sorry for another bugfix-bugfix ;)
Fixes the unintended behaviour @netzmark describes in #688.
I was missing to set stepComplete for the error to be handled at the moment the user clicks a message box and additionally the FSM-states added were wrong.
This fix is tested on my 2 nozzle machine again, this time with a failing vacuum on nozzle 1 and afterwards with failing vac. on nozzle 2. in both cases the assembly went correctly on.

Correctly handle overridden errors

---

src/main/resources/scripts/Examples/Python/py-scripting-info.py

Port of JavaScript `Print_Scripting_Info.js` to Python.
Tested in OpenPnP

Add Python script example that prints scripting environment

---

pom.xml

Fixes #710 
All of the current Python example scripts were tested and they all function as before.

Upgrade to final release of Jython 2.7.1

---

src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java
src/main/java/org/openpnp/machine/reference/vision/ReferenceBottomVision.java
src/main/java/org/openpnp/spi/PartAlignment.java

This patch adds more debug output related to the ReferencePnpJobProcessor and part alignment.
The changes help to debug problems in the part alignment pipeline
Just take a look at the new debug messages.
1. The code has been tested with real-life placement operations.

Add better debug output for part alignment pipeline

---

CHANGES.md

Documented new status bar functionality in CHANGES.md

Documented new status bar functionality in CHANGES.md

---

src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java

Added HOME_COMPLETE_REGEX for machines that don't support M400.
Added HOME_COMPLETE_REGEX for machines that don't support …

Added HOME_COMPLETE_REGEX for machines that don't support M400.

---

src/main/resources/scripts/Utility/Place.js

Added a simple Place part utility script
Describe the change in detail. Explain how it works. The better you describe the …

Added a simple Place part utility script

---

src/main/java/org/openpnp/machine/reference/driver/wizards/GcodeDriverConsole.java

Signed-off-by: Paul Jones <paul@pauljones.id.au>

Check that machine is started before sending gcode commands from console

---

src/main/java/org/openpnp/Main.java

Added Bienvenido i.e welcome in spanish to the list of greetings the user sees on running the app.
Added Bienvenido i.e …

Added welcome in Spanish

---

src/main/java/org/openpnp/Main.java
src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/importer/LabcenterProteusImporter.java

Simply put this adds an importer for Labcenter Proteus PKP output file. This file can be created directly by anyone using …

Adding importer for Labcenter PKP files

---

src/main/resources/scripts/Examples/JavaScript/Pipeline.js

Added a very simple CvPipeline example to the included scripts.
CvPipeline seems a powerful tool for scripting, but no examples are included making starting out hard.
Execute the script, the camera view will show the changes made to the image briefly.
Tested by running the script and observing the log and output images.
Maven testing seems unnecessary for a single script being added :)

Add pipeline scripting example.

---

src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceAutoFeederConfigurationWizard.java

added 2 buttons for auto feeders actuators, to easy test, setup and debug feeders.

added test buttons for autofeeder actuators

---

CHANGES.md

As per suggestion edited CHANGES.md for #815.

Edited CHANGES.md

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java

Changed a message to something more accurate.
Bug
NAF
1. How did you test the change? 
used the test case on #826 
Yes
No
Not worse than before.... :D

Fix Cast exception when the "results" stage is disabled in a pipeline.

---

src/main/java/org/openpnp/vision/pipeline/ui/PipelinePanel.java

With only the icon, I was thinking that the first button was "rollback to original settings..."  :D

Added missing hint and removed UCase char in pipeline editor window.

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/tablemodel/PlacementsTableModel.java

Hi! I like openpnp2, but i think placements table appearance should be changed. 
Please take a look [screenshot](https://yadi.sk/i/GjbR0aZcC2bp6A)
I have moved "Enabled" column far away from "Placed" column.
And i have changed placement color to white.
In my opinion, reading this table now become much better.

Placements table appearance

---

src/main/java/org/openpnp/Main.java

hello in french is added

---

src/main/java/org/openpnp/spi/base/AbstractPnpJobProcessor.java

Adds new scripting event 'Job.AfterDiscard'.
Allows flexibility for ensuring parts are actually gone after a discard.
Add Job.AfterDiscard.js to the Events directory.
mvn test run was clean and without errors.

Added scripting event on discard

---

src/main/java/org/openpnp/vision/pipeline/stages/Add.java

The Add pipeline only does a simple add and does not support subtraction.
This PR adds scalar parameters so that each stage output may be scaled.
Subtraction lets me remove phantom edges from an image.
Default behaviour is not altered as the default scalar value is 1.
The first scalar scales the first stage and must be non-negative.
The second scalar scales the second stage can can be negative.
1. How did you test the change? I added my change to a pipeline and verified the expected result.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? Yes

Enhance Add pipeline with scaling on each stage

---

src/main/java/org/openpnp/spi/base/AbstractPnpJobProcessor.java

Adds new scripting event 'Job.BeforeDiscard'.
My specific use case is to discard different parts in different locations, eg 603 passives in one bin and QFN/QFP to another.
Add Job.BeforeDiscard.py to the Events directory.

Add BeforeDiscard event

---

src/main/java/org/openpnp/vision/pipeline/stages/MaskHsv.java

This PR adds a "binaryMask" option to MaskHsv to return a black and white stencil of the "green screened" image.
Juki nozzle tips are one application example of using a "green screen" effect to recognize objects in from of a green backdrop, in this case the broad green collar of the nozzle tip. As long as the object itself is not green, its presence can be detected simply by the pixel not being green. 
NOTE: The _real_ reason for this PR is my upcoming new feeder PR that uses the green screen effect extensively. When this description says "green" it effectively means any vivid color, the hue of which can be set in the MaskHsv stage. 
MaskHsv currently blackens the color areas in a given full color image. Consequently, black that was present in the source image cannot be distingiushed from …

Create binary MaskHsv for true "green screen" effect

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

Update NamedCSVImporter to make it case agnostic and add support for Allegro format placement report.
I got tired of editing the placement files, so I updated the importer.
No change to how it is used.
1. How did you test the change? I imported some different files and confirmed they imported correctly.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? Yes.
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. N/A
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. All tests passed

Update named csv importer

---

CHANGES.md

#Read This First
Describe the change in detail. Explain how it works. The better you describe the change the more likely it …

Welcome CHANGES.md into the new year

---

src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/neoden4/Neoden4Camera.java
src/main/java/org/openpnp/machine/neoden4/wizards/Neoden4CameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java

This version of the driver will allow you to move around, use nozzles, rails, lights etc,
It also honors the status flag from Neoden motion controller when moving around,
preventing damage to nozzles, and not skipping commands etc.
Still work in progress, tho.

Neoden4: First usable version of driver

---

src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java

This is just a simple code clean up, mostly removing dead code or code that was behind comments.

Neoden4: Simple code cleanup

---

src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java

Bugfix in neoden 4 driver. Corrects wrong command sequence for rails forward command.

Neoden4 bugfix: Fixes rails forward command

---

src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/neoden4/Neoden4Camera.java
src/main/java/org/openpnp/machine/neoden4/wizards/Neoden4CameraConfigurationWizard.java
src/main/java/org/openpnp/machine/neoden4/wizards/Neoden4DriverConfigurationWizard.java

Allows fo configuring the Neoden 4 components using UI:
* Machine settings
* Camera settings
Before, a lot of this was hard coded in code, either as constants or as magic 
numbers spread around.

Adds UI configuration for Neoden 4 components

---

src/main/java/org/openpnp/gui/tablemodel/PackagesTableModel.java
src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleVacuumWizard.java
src/main/java/org/openpnp/model/Package.java

If set on the part's package vacuum threshold and / or blow threshold
will be used in pick and place operations instead of just using on / off.
Changes Package and Nozzle.

Add support for vacuum & blow threshold

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java

The BlindsFeeder should only use a nozzle with no part loaded to actuate a cover. Otherwise the part is brushed off. This is also true for single nozzle machines, of course, but inside a job the bug will only happen in a multi-nozzle machines.
Background: The `Feeder.feed()` method does not provide the nozzle with which the pick will eventually be made, so we have to select a nozzle ourselves. The bugfix now does this properly, avoiding nozzles with a part loaded. 
For multi-nozzle machines with multiple free nozzles, in order to avoid extra head movements, it should try to guess the nozzle to be used for the pick. But we can only use the feeder's part to nozzle tip compatibility to guess which nozzle will likely be used. This is not 100% water-tight but still better than nothing. 
See …

Fix/BlindsFeeder: Use only nozzles with no part loaded to actuate cover

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java

Fixes my own #991 for Advanced Part-On/Part-Off Detection.
During Part-Off checks this re-establishes the possibility to read the vacuum level _before_ the valve closes again. The behavior was mistakenly changed when the Probing close-time was added to compensate for signal delays. 
For machines with slow connections and/or fast-changing vacuum signals, this breaks the previous behavior. 
(Screenshot by @doppelgrau)
On my machine this was invisible during testing due to fast connection/sluggish vacuum signal.
See also:
https://github.com/openpnp/openpnp/pull/991#issuecomment-627239863
Set the Probing close-time to 0 (see screenshot). Check if Last Reading corresponds to a curve point, where the level is not yet decaying again.
1. I hope @doppelgrau can test this. …

Fix/Part-Off detection: Read vacuum level before valve closes.

---

src/main/java/org/openpnp/gui/MainFrame.java
src/main/java/org/openpnp/gui/support/MessageBoxes.java

Hello Jason,
I was fed up of re-launching openpnp each time there was an error in configuration file
so I did this small update. It allows the user to choose whether he wants to retry or exit.
best regards
Julien

Retry on configuration loading failed

---

src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OpenPnpCaptureCameraConfigurationWizard.java

Adds an FPS test button to the Device Settings Wizard of OpenPnpCaptureCamera.
It is sometimes useful to know how a specific Camera performs in terms of FPS on OpenPnP. 
I made the Test button in order to evaluate [a new color camera with marvelous 720p@120 fps and global shutter](https://www.aliexpress.com/item/32916630999.html). I just wanted to make sure, the no-name camera actually delivers what the specs promised (it does). 
The button then revealed that FPS are highly exposure dependent. See the [report about the suspected reasons](https://makr.zone/camera-fps-cpu-load-and-lighting-exposure/519/).
This is one more thing, I learned through some added diagnostics (see #995, #991 for other examples). 
Just set the camera Device and Format then press the Test button. The Test button …

Feature/OpenPnpCaptureCamera Capture FPS Test

---

README.md
pom.xml
src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/camera/OpenPnpCaptureCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/OpenPnpCaptureCameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/driver/ReferenceDriverCommunications.java
src/main/java/org/openpnp/machine/reference/driver/SerialPortCommunications.java
src/main/java/org/openpnp/machine/reference/driver/SimulatedCommunications.java
src/main/java/org/openpnp/machine/reference/driver/TcpCommunications.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleToolChangerWizard.java

Merged develop into test. 
Keep it up to date.
1. Did run lab bench controller/stepper contraption test and `mvn test` before submitting the Pull Request.

Merge develop into test

---

CHANGES.md
src/main/java/org/openpnp/machine/reference/axis/ReferenceControllerAxis.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/driver/ReferenceAdvancedMotionPlanner.java
src/main/java/org/openpnp/model/Motion.java
src/main/java/org/openpnp/spi/ControllerAxis.java
src/main/java/org/openpnp/spi/MotionPlanner.java
src/main/java/org/openpnp/util/GcodeServer.java

* Fixed reported bugs, thanks everybody!
* Improved Issues & Solutions system.
* Added support for TinyG.
* Added some very preliminary support for [Marlin 2.0 (Bill's fork)](https://github.com/openpnp/openpnp/wiki/Motion-Controller-Firmwares#marlin-20).
This is just a small and mostly cosmetic update in OpenPnP, most of the work has gone into the TinyG firmware extension it pairs with:
- See the PR there: [Feature / New G-code commands](https://github.com/synthetos/TinyG/pull/258) 
- See the discussion there: [TinyG firmware improved](https://groups.google.com/d/msg/openpnp/veyVAwqS0do/Zsn73noGBQAJ)
- Watch the video: [OpenPnP and TinyG with improved Speed Control / Jerk limit](https://youtu.be/6SBDApObbz0)
This is a straightforward extension of the Issues & Solutions system. TinyG users …

Feature/Advanced Motion Control - Update 4

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/gui/PartsPanel.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/camera/MjpgCaptureCamera.java
src/main/java/org/openpnp/machine/reference/camera/wizards/MjpgCaptureCameraWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/AbstractReferenceFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

Merged `develop` into `test`.
Keep up.
1. Assuming tests were done in develop. No conflicts or even commonly changed files detected.
2. No need to follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. No changes in the `org.openpnp.spi` or `org.openpnp.model`.

Merge/Branch develop into test (2020-11-29)

---

src/main/java/org/openpnp/machine/reference/camera/MjpgCaptureCamera.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java

Merged `develop` into `test`.
Keep up.
1. Assuming tests were done in develop. No conflicts or even commonly changed files detected.
2. No need to follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. No changes in the `org.openpnp.spi` or `org.openpnp.model`.

Merge/Branch develop into test (2020-12-02)

---

CHANGES.md
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java

Merge latest develop into test, after #1083 and #1086.
Merge latest develop #1083. After cherry-picking #1086, make sure the branches are properly related again. 
1. Original PRs did the testing. The branch remains (almost) unchanged otherwise.
2. Original PRs did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. Original PRs made changes in the `org.openpnp.spi` or `org.openpnp.model` packages with testing.
4. Successfully ran `mvn test` before submitting the Pull Request.

Merge/Branch develop into test (2020-12-12)

---

src/main/java/org/openpnp/gui/components/CameraPanel.java
src/main/java/org/openpnp/gui/wizards/CameraConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/AbstractBroadcastingCamera.java
src/main/java/org/openpnp/machine/reference/camera/BufferedImageCamera.java
src/main/java/org/openpnp/machine/reference/driver/GcodeAsyncDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferenceStripFeederConfigurationWizard.java
src/main/java/org/openpnp/spi/Camera.java
src/main/java/org/openpnp/spi/PnpJobProcessor.java
src/main/java/org/openpnp/spi/base/AbstractCamera.java
src/test/java/VisionUtilsTest.java

This is a round-up of all the issues that popped up in the current [![testing-round](https://user-images.githubusercontent.com/9963310/106956782-64fb8700-6737-11eb-93bf-5214a2ca9130.png)](https://github.com/openpnp/openpnp/issues?q=label%3Atesting-round+is%3Aclosed). 
* New Feature: Cameras can be shown/not shown in multi camera view panels (Show All Horizontal/Show All Vertical). This is typically used to hide the capture card in a SwitcherCamera setup. The Camera will still be available as a single CameraView.
* Bug-fix: Camera threads are sometimes not stopped by the interrupt (race). By comparing the current thread to the camera thread we can still quit. This sometimes resulted in a doubling, tripling, quadrupling ... frame broadcasts, whenever the Camera thread was restarted (when …

Fix/Testing Round Update

---

src/main/java/org/openpnp/machine/neoden4/NeoDen4Driver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeAsyncDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/NullDriver.java
src/main/java/org/openpnp/spi/Driver.java
src/test/java/BasicJobTest.java
src/test/java/org/openpnp/machine/reference/driver/test/TestDriver.java

Simply remove Reference* class import in spi package. That kind break the abstraction pattern.

Use interfaces in spi instead of Reference implementations

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/gui/tablemodel/PartsTableModel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/model/Length.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/spi/Head.java
src/main/java/org/openpnp/spi/NozzleTip.java
src/main/java/org/openpnp/spi/base/AbstractHead.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java
src/main/java/org/openpnp/util/ImageUtils.java
src/main/java/org/openpnp/util/UiUtils.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java
src/main/java/org/openpnp/vision/pipeline/ui/PipelinePanel.java

Reverts openpnp/openpnp#1169
Reverting so I can merge them all in the correct order and avoid conflicts.

Revert "Fix/Round-up of Bug-Fixes and some Missing Utility Features"

---

src/main/java/org/openpnp/gui/JogControlsPanel.java
src/main/java/org/openpnp/gui/tablemodel/PartsTableModel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTip.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/model/Length.java
src/main/java/org/openpnp/model/Location.java
src/main/java/org/openpnp/spi/Head.java
src/main/java/org/openpnp/spi/NozzleTip.java
src/main/java/org/openpnp/spi/base/AbstractHead.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java
src/main/java/org/openpnp/spi/base/AbstractMachine.java
src/main/java/org/openpnp/util/ImageUtils.java
src/main/java/org/openpnp/util/UiUtils.java
src/main/java/org/openpnp/vision/pipeline/CvPipeline.java
src/main/java/org/openpnp/vision/pipeline/ui/PipelinePanel.java

This is a resubmit of https://github.com/openpnp/openpnp/pull/1169 which I reverted in order to avoid conflicts. See the chain of commits :)
So, this is the revert of the revert of the merge, which will essentially be the original PR.

Revert "Revert "Fix/Round-up of Bug-Fixes and some Missing Utility Features""

---

pom.xml
src/test/java/AdvancedMotionTest.java
src/test/java/BasicJobTest.java
src/test/java/CalculateBoardLocationTests.java
src/test/java/EagleLoaderTest.java
src/test/java/EagleMountsmdUlpImporterTest.java
src/test/java/GcodeDriverTest.java
src/test/java/HttpActuatorTest.java
src/test/java/OpenCvTest.java
src/test/java/ReferenceBottomVisionTest.java
src/test/java/ReferenceFiducialLocatorTest.java
src/test/java/ReferenceJobProcessorRetryTests.java
src/test/java/SampleJobTest.java
src/test/java/TavellingSalesmanTest.java
src/test/java/Utils2DTest.java
src/test/java/VisionUtilsTest.java

Update from JUnit 4 to JUnit 5
Because JUnit 5 is one better than JUnit 4. I was going to upgrade to JUnit 4.13 and then decided to upgrade to JUnit 5. There's some differences here and there between the two, but JUnit 5 has more useful functionality.
Dev only feature.
Unit Testing ++
Yes
No, only in tests.
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not …

Updating to JUnit 5

---

.github/workflows/build_and_deploy.yml

Reverts openpnp/openpnp#1233
See comments on original PR. New builds seem to have issues.

Revert "Update Install4J to 9.0.4 to make Fedora compatible"

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java

When the following is combined...
1. [Rotational axis wrap-around.](https://github.com/openpnp/openpnp/wiki/Machine-Axes#controller-settings-rotational-axis) 
2. [Rotational axis -180° .. 180° limiting.](https://github.com/openpnp/openpnp/wiki/Machine-Axes#controller-settings-rotational-axis)
3. Multiple drivers, with rotational axes on a second driver, [prompting axis interlock in Motion Planning](https://github.com/openpnp/openpnp/wiki/Motion-Planner#motion-path-planning).
...then the current driver and planned coordinates may change through the interlock, because the interlock performs a `waitForCompletion()` which in turn performs the rotational axis wrap-around back into the -180° .. 180° range, which can cause driver and planned coordinates to change. 
Therefore, the `moveTo()` old …

Fix / Rotational Axis Wrap-Around, -180° .. 180° Limiting, Multiple Driver Axis Interlock

---

src/main/java/org/openpnp/machine/reference/axis/ReferenceControllerAxis.java
src/main/java/org/openpnp/machine/reference/driver/AbstractReferenceDriver.java
src/main/java/org/openpnp/model/AbstractMotionPath.java
src/main/java/org/openpnp/model/MotionProfile.java
src/main/java/org/openpnp/spi/base/AbstractCoordinateAxis.java

This contains some improvements in Driver and Motion control classes. 
* Expose communication options from `AbstractReferenceDriver`, so Issues & Solutions will be able to reason about them.
* Favor cameras in `AbstractCoordinateAxis.getDefaultHeadMountable()`, will be used for axis calibration.
* Handle co-linear moves better, i.e. make sure they are not merged when kinetic limits vary.
* Handle a numerical instability in `MotionProfile` analytical solving.
* Fix a typo.
The last two points prepare OpenPnP to handle co-linear moves better. These moves will be generated in the upcoming **DirectionalSneakUp** backlash compensation method, where a move will still be broken up in a fast principal move, followed by a short piece at lower speed, to equalize tensions in belts etc. between …

Feature / Driver & Motion Preparations

---

src/main/java/org/openpnp/spi/base/AbstractCamera.java
src/main/java/org/openpnp/util/VisionUtils.java

* Added `VisionUtils.getLocationPixelCenterOffsets(Camera, HeadMountable, Location)` 
* Missed one themed color refactoring in #1245 (sorry about that).
All this will be used (or has popped up) in the upcoming Issues & Solutions Calibration PR. 
See also:
https://groups.google.com/g/openpnp/c/dBg7txMB0R0/m/OIUaQAS0BgAJ
No change in use (yet).
1. It was tested extensively in the testing of the upcoming PR. Tested using mvn test in the break-out. 
4. Successful run `mvn test` before submitting the Pull Request.

Feature/Vision Utils

---

src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java

If you would like to add a new feature to OpenPnP that changes core or reference functionality,
please create a topic on the [discussion group](http://groups.google.com/group/openpnp) to discuss
the feature first. Also consider if your feature can be implemented as a new subclass of
a Reference class, or an entirely new class, instead of changing or adding to the Reference
class.
Fill out all the details below. All sections …

Minor typos in ReferenceBottomVisionPartConfigurationWizard.java

---

src/main/java/org/openpnp/gui/FeedersPanel.java
src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/vision/wizards/ReferenceBottomVisionPartConfigurationWizard.java

Merge develop into test.
Keep up.
None.

Merge/Develop into Test

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceCameraTransformsConfigurationWizard.java

Merge / Develop into Test

---

src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java

* ImageCamera Y Rotation can now be combined with Z Rotation (i.e. the Y Rotation is effectively applied _after_ the Z Rotation).
* Optimized anti-aliasing (probe only the relevant 4 instead of all 9 surrounding source pixels).
See #1297 
No change.

Fix / Simulated Lens Distortion Y Rotation after Z Rotation

---

.github/workflows/build_and_deploy.yml

Just another try to get the deploy problem solved. Format the version number as documented on the `actions/setup-java@v1` page.
https://github.com/actions/setup-java

Just fishing.

---

CHANGES.md

Why should this change be included in OpenPnP? Does it benefit a majority of users or is it specific to one type of user or machine? Machine specific or highly individual code will not be accepted.
How does someone use the feature? Be descriptive. Include step by step instructions. If this is a new feature then these instructions will become the Wiki documentation for the feature, so explain here the same way you would explain to someone who had never used the feature. …

* Add news to CHANGES.md

---

OPENPNP_2_0.md
src/main/java/org/openpnp/Main.java
src/main/java/org/openpnp/gui/AboutDialog.java
src/main/java/org/openpnp/gui/Welcome2_0Dialog.java
src/main/java/org/openpnp/gui/components/MarkupTextPane.java
src/main/java/org/openpnp/util/XmlSerialize.java
src/main/resources/config/machine.xml

- Update the Welcome dialog text. It's been a while that OpenPnP 2.0 was introduced, and I wanted to put emphasis on [Issues & Solutions](https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions) right from the start.
- A new `MarkupTextPane` component implements a rudimentary Markup to HTML conversion. This also makes sure that text lines are wrapped correctly. 
- The  `MarkupTextPane` component is used in the Welcome and About dialogs. 
- When the text pane is clicked, it opens a browser to the online equivalent of the displayed text, e.g.  [OPENPNP_2_0.md](https://github.com/markmaker/openpnp/blob/feature/updated-welcome-dialog/OPENPNP_2_0.md). The simple HTML rendering done with a JLabel can't handle link clicking, so this is the next best thing we can offer 🤫. 
- To round off the …

Feature / Update the OpenPnP Welcome Package

---

src/main/java/org/openpnp/gui/MachineControlsPanel.java
src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java
src/main/java/org/openpnp/machine/reference/driver/AbstractReferenceDriver.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/driver/wizards/AbstractReferenceDriverConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

This PR primarily adds Issues & Solutions support for the upcoming special Grbl firmware extended for OpenPnP by @surabibio, and running on a plain Arduino. The PR also adds better support for unhomed machines, i.e. machines without end-switches. 
* Improve Issues & Solutions firmwares detection handling (enum for detected firmware instead of many booleans).
* Refactor Gcode suggestions into separate method.
* Add Grbl as supported firmware.
* Support synchronizing the initial location of the controller/machine into OpenPnP after enabling the machine.
* This allows for safe jogging of an unhomed machine.
* Add the **Sync Initial Location** option to the GUI.
* The GUI was changed to hide unneeded port settings when switching between **serial** and **tcp** (instead of graying out).
* This …

Feature/Grbl and Unhomed Machine Support

---

src/main/java/org/openpnp/machine/reference/driver/AbstractMotionPlanner.java

Fix / AbstractMotionPlanner Startup Null Exception (Cherry Pick)

---

src/main/java/org/openpnp/gui/components/IssuePanel.java
src/main/java/org/openpnp/machine/reference/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/axis/ReferenceControllerAxis.java
src/main/java/org/openpnp/machine/reference/solutions/ActuatorSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/AxisSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/HeadSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceHeadConfigurationWizard.java
src/main/java/org/openpnp/model/Solutions.java
src/main/java/org/openpnp/spi/Head.java
src/main/java/org/openpnp/spi/base/AbstractActuator.java
src/main/java/org/openpnp/spi/base/AbstractHead.java
src/main/java/org/openpnp/util/Cycles.java

This PR adds some extension to [Issues & Solutions](https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions):
1. Separate solutions into `AxisSolutions` and `ActuatorSolutions`. 
2. Add String property support to Issues & Solutions. Optionally with template-combo-box.
3. Add multi-line text property support to Issues & Solutions. Optionally with template-combo-box.
4. Missing, duplicate, invalid Axis letters can be directly chosen/edited on the solution. Likely defaults are proposed and letters already taken are dynamically removed from the drop-down:  
5. Duplicate Axis letters are now diagnosed. An exception formerly caused by duplicates is now caught in the `POSITION_REPORT_REGEX` issue.  
6. Interactive Actuator G-code command and regex support added to Issues & Solutions; with …

Feature / Extended Actuator and Axis Support in Issues & Solutions.

---

src/main/java/org/openpnp/gui/support/Icons.java
src/main/java/org/openpnp/machine/reference/axis/ReferenceCamCounterClockwiseAxis.java
src/main/java/org/openpnp/machine/reference/axis/wizards/ReferenceCamCounterClockwiseAxisConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/KinematicSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

This PR improves Issues & Solutions to be more watertight. 
1. Deprecates `ReferenceCamCounterClockwiseAxis` cam wheel radius and gap. These offsets are constant in the transform, not useful, they just need compensating in the nozzle Z head offset. 
2. The Wizard marks the fields as deprecated:
2. When these offsets are zero, the fields are hidden:
3. Issues & Solutions can remove the cam wheel radius and gap, and the compensation in the nozzle Z head offset:
4. Double-check: If the offsets are not removed, or any other Z head offset present on the Default Nozzle, the Issues & Solutions head offsets solution will warn the user strongly: 
5. Some recommendations, warnings and errors have been added, as suggested by users in testing. 
6. CHMT-Firmware (Smoothieware port to the CHMT STM32 …

Fix / Issues & Solutions more Watertight, Cam Transform, CHMT Firmware Detect, Serial Flow Control

---

src/main/java/org/openpnp/machine/reference/ReferenceCamera.java

Just cleans-up [PR#1364](https://github.com/openpnp/openpnp/pull/1364#:~:text=advanced%20calibration%20debug-,%231364,-Merged)
This is a better and standard way of doing things.
No special instructions required.
1. How did you test the change? **Verified the logs didn't contain any unexpected exceptions after forcing the undistortion mappings and virtual camera matrix to be recomputed many times.**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **Yes.**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.  **No changes were made to these packages.**
4. Be sure to run `mvn …

Changed to synchronized methods rather than using a semaphore

---

CHANGES.md

Added section for Advanced Camera Calibration
Notifies everyone about what has recently changed.
No special instructions needed.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **N/A**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **N/A**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. **N/A**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **N/A**

Updates to CHANGES.md

---

src/test/java/CvStageTest.java

Cherry pick CvStageTest fix from test.

Fix / Added explicit config loading to CvStageTest.

---

.gitignore
ISSUE_TEMPLATE.md

Fix minor typo in Issue Template and use markdown https link. Also ignore .vscode settings dir.

---

src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

Issues & Solutions uses the nozzle tip to perform the bottom camera preliminary calibration. To detect the nozzle tip, its **Vision Diameter** must be set. Like any solution, it must also support the **Undo/Reopen** operation, i.e. revert the **Vision Diameter** change. For this purpose, the old state must be saved.
Formerly, the nozzle tip and diameter were saved when users pressed **Find Issues & Solutions**. When they then pressed **Accept**, and no nozzle tip was loaded, an error was displayed, prompting to load a nozzle tip. 
After loading the tip, another **Accept** would still show the error, because the state of the loaded nozzle tip still reflected the state when pressing **Find Issues & Solutions**.
This PR fixes this, by storing the state only when pressing **Accept**.
See user …

Fix / Issues & Solutions: Re-evaluate Loaded Nozzle Tip

---

src/main/java/org/openpnp/machine/reference/solutions/AxisSolutions.java
src/main/java/org/openpnp/spi/Driver.java

This small change detects missing axis rate limits using Issues & Solutions. 
User testing.
Missing Axis rates are reported as Errors in Issues & Solutions:

Feature / Issues & Solutions: Detect Missing Axis Rate Limits

---

src/main/java/org/openpnp/machine/reference/camera/calibration/AdvancedCalibration.java
src/main/java/org/openpnp/machine/reference/camera/calibration/CameraCalibrationUtils.java

Add the capability to disable lens distortion correction and camera tilt correction.
May help in debugging an issue where the camera appears to have a tilt to it after calibration has been run. It is suspected that fitting of a camera model that includes both tangential lens distortion and camera tilt may not be robust in its ability to decern the difference between the two effects when they are both relatively small.  This change allows one or the other or both to be independently disabled to see what if any affect they have on the calibration.
Everything works just as it did previously unless the machine.xml file is manually edited outside of OpenPnP.  The advanced-calibration section for each camera now includes entries for the following three attributes: …

Add capability to disable distortion and tilt corrections

---

src/main/java/org/openpnp/gui/components/AutoSelectTextTable.java

Hooking into the `AutoSelectTextTable` (which is the commonly used `JTable` subclass in OpenPnP), this PR adds three state multi-column sorting to tables. Column headers can be clicked repeatedly to cycle through Ascending, Descending, Unsorted. 
The implementation supports multi-column sorting as before. 
When users clicks on a column header the table is sorted by that column. Users can then click again to descending sorting or click on other column headers to sort by these columns, but they cannot go back to the model/logical order of the table. They need to exit and restart OpenPnP to do so. 
Some tables such as the Issues & Solutions list have an important logical order. This PR makes it possible to go back to that order. 
Just click on column headers, as before, but it now cycles …

Feature/Three State Table Sorter

---

CHANGES.md

Adds the descriptions for the most prominent recent changes. 
Keep the documentation up.
None.
N/A.

Provide CHANGES.

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java

This is simply the cherry-pick from #1460.

Fix / BlindsFeeder: Qualified Pipeline Property "SimpleOcr.alphabet" (Cherry-Pick)

---

src/main/java/org/openpnp/gui/components/CameraView.java
src/main/java/org/openpnp/gui/wizards/CameraVisionConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/ContactProbeNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/camera/AbstractSettlingCamera.java
src/main/java/org/openpnp/machine/reference/camera/AutoFocusProvider.java
src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java
src/main/java/org/openpnp/machine/reference/camera/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/solutions/ActuatorSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/HeadSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/KinematicSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/NozzleTipSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/spi/Locatable.java
src/main/java/org/openpnp/spi/base/AbstractHead.java
src/main/java/org/openpnp/spi/base/AbstractHeadMountable.java
src/main/java/org/openpnp/util/GcodeServer.java
src/main/resources/config/machine.xml

This is a round-up of improvements, extensions and bug-fixes in Issues & Solutions and supporting algorithms.
Detail feature list:
1. When the nozzle solution is generating rotation axes, it should enable limit to ±180° by default, and set feed-rate, acceleration to the higher rotation axis defaults.
1. Improve Marlin `M115` controller firmware diagnostics: point at version and/or axis configuration.
1. Permanent G-code controller `M114` detection so it can always properly suggest controller specific axis letters.
1. The pump actuator is now in the default `machine.xml`, i.e. new machines have it from the start.
1. For existing machines, suggests creating the pump actuator, if missing.
1, Missing light actuator G-code now properly reported in the **Basic** milestone.
1. First thing in the …

Feature/Issues & Solutions Roundup

---

src/main/java/org/openpnp/machine/reference/feeder/BlindsFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java
src/main/java/org/openpnp/machine/reference/solutions/AxisSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java
src/main/java/org/openpnp/model/VisionCompositing.java

This is a round-up of fixes according to the testing round. The components are the individual commits.
1. [Better messages to justify missing feeder Z for 3D Units per Pixel.](https://github.com/openpnp/openpnp/commit/fde33dcb5fa92406bba43d4c79bca0bce621d056)
2. [Improve rotated rect points determination for non-square UPP.](https://github.com/openpnp/openpnp/commit/ddd0d6a897fed65d538c1bd1a9f46153df0f82a2)
3. [Issues & Solutions: Differentiate cases in messages about unsupported axis letters.](https://github.com/openpnp/openpnp/commit/b2451f62796c93b66a846bdec01c1f4606024785)
The Wiki info was improved:
https://github.com/openpnp/openpnp/wiki/Machine-Axes#controller-settings
5. [Issues & Solutions: Once you decided to use generic firmware support, stick to …

Fix / Various Improvements in Testing Round

---

src/main/java/org/openpnp/gui/JobPlacementsPanel.java
src/main/java/org/openpnp/machine/reference/camera/ReferenceCamera.java
src/main/java/org/openpnp/machine/reference/solutions/ActuatorSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/AxisSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/NozzleTipSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/util/VisionUtils.java

The following changes were made to Issues & Solutions:
- Better message and Wiki telling the users to [avoid axis letter "E" (extruder mode)](https://github.com/openpnp/openpnp/wiki/Machine-Axes#controller-settings) and to [upgrade/configure firmwares, if needed](https://github.com/openpnp/openpnp/wiki/Motion-Controller-Firmwares#upgrading-and-configuring-firmwares).
- Proposes [aligning the nozzle to the part rotation](https://github.com/openpnp/openpnp/wiki/Nozzle-Rotation-Mode#align-nozzle-rotation-with-part). Cross-hairs and DRO correspond to bottom-vision detected part rotation rather than the raw pick rotation. 
- Handle `OpenPnpCaptureCamera` [device properties](https://github.com/openpnp/openpnp/wiki/OpenPnpCaptureCamera#camera-properties) as follows. 
- Tell the user to avoid …

Feature / Extensions to Issues and Solution

---

src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

Issues & Solutions now proposes a `HOME_COMMAND`, even if one is already present. The proposed command is built and compared to the present one. If the present one does not _contain_ the proposed lines, the solution is presented. Users can still add custom lines before and after the command, without I&S wanting to undo them. 
As always, users can also Dismiss the proposed solution, if they know their present command is better.
As an aside, this PR also fixes a typo/text sequence in the `CameraSolutions`.
Support cases related to `HOME_COMMAND`, the latest of which is the following:
https://groups.google.com/g/openpnp/c/2DKOxhBc6pg/m/2HgSqTmCCQAJ
No change,
1. Tested with Issues & Solutions.
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-sty …

Fix/Issues and Solutions HOME_COMMAND

---

src/main/java/org/openpnp/machine/reference/solutions/CalibrationSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

Fixes two Issues & Solutions bugs:
1. [Fixes stale stored nozzle offset in precision calibration.](https://github.com/openpnp/openpnp/commit/4e9df253e33a5066d40c830975a95da5f29ba30f)
2. [Fixes trailing newline in suggested TinyG `HOME_COMMAND`.](https://github.com/openpnp/openpnp/commit/4f24d42ac537f6774b379b40cb5cf55ee71a792c)
User reports
1. https://groups.google.com/g/openpnp/c/74eGLiuNqRw/m/PWAQI6ShCQAJ
2. https://github.com/openpnp/openpnp/pull/1485#issuecomment-1244064674
No change.
1. Assuming prompt user tests in the testing version.
3. Didfollow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
4. No changes in the `org.openpnp.spi` or `org.openpnp.model` packages.
5. Successful `mvn test` before submitting the Pull Request.

Fix/Issues & Solution Roundup - 2

---

src/main/java/org/openpnp/gui/importer/NamedCSVImporter.java

Fix/Typo "Centeroid"

---

src/main/java/org/openpnp/gui/panelization/DlgAutoPanelize.java

Fixes Panelization Settings window height reported in #1325

Fix/Panelization Settings window height

---

CHANGES.md
TRANSLATIONS.md

Update CHANGES.md and TRANSLATIONS.md

Update CHANGES.md and TRANSLATIONS.md

---

src/main/java/org/openpnp/machine/reference/solutions/GcodeDriverSolutions.java

Issues & Solutions now detects `M115` specifying serial flow control. 
The firmware flavor no longer specifies recommended serial flow control alone. Users modify the hardware and may add proper flow-control where it was missing (example: Smoothieware CHMT port). The new `M115` response property `X-SERIAL_FLOW` was added to the corresponding firmware mods. 
Issues & Solutions now detects this universally, i.e., it can be used for any future firmware. Supported values are (case insensitive):
- `NONE` or `OFF`
- `RTS/CTS`
- `XON/XOFF`
If `X-SERIAL_FLOW`  is present (and known), these override the former heuristics based on firmwares and versions.
If  `X-SERIAL_FLOW`  is _not_ present, Issues & Solutions should behave as before.
Example M115 response (thanks, Micael): …

Feature / Issues & Solutions detects M115 specifying serial flow control

---

src/main/java/org/openpnp/gui/components/IssuePanel.java
src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java
src/main/java/org/openpnp/machine/reference/driver/GcodeDriver.java
src/main/java/org/openpnp/machine/reference/solutions/ActuatorSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/AxisSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/NozzleTipSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java
src/main/java/org/openpnp/machine/reference/wizards/ReferenceNozzleTipCalibrationWizard.java
src/main/java/org/openpnp/model/Solutions.java
src/main/java/org/openpnp/util/TextUtils.java

- Issues & Solutions: feature diameter **Auto-Detect Next** button now cycles through the peak [DetectCircularSymmetry](https://github.com/openpnp/openpnp/wiki/DetectCircularSymmetry) scores, allowing the user to select the right contour:
- This is especially useful in the nozzle tip calibration setup (image for illustration, not actually from new function):
- Issues & Solutions: nozzle tip calibration resets the pipeline to the default (makes sure the Circular Symmetry pipeline is actually used on old configs).
- Issues & Solutions: fix cryptic null pointer exception when empty axis letter selected. Proper error displayed instead.
- `TextUtils` variable substitution now supports curly brackets escaping. The `{` is escaped to `<((`, `}` to `))>`. This allows for nested variable …

Fix / Issues & Solutions Roundup  3

---

CHANGES.md

This is a supplement to PR #1549 which just adds an entry to the list of changes.

changes updated to note the renamed csv importer

---

src/main/java/org/openpnp/gui/importer/CsvImporter.java

This PR adds auto detection and handling for UTF-16 encoded .csv files to the CSVImporter.
According to https://groups.google.com/g/openpnp/c/JjAjSdWhUkA/m/Df1WH4mqAAAJ EasyEDA created .csv files are UTF-16 encoded. Luckily this files contain a Byte Order Mark (https://en.wikipedia.org/wiki/Byte_order_mark) which can be used to safely detect the character set required for correct decoding.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **I've used the supplied .csv files and old .csv files that worked previously to verify that the change will not break old behavior.**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` …

Csv UFT-16 support

---

src/main/java/org/openpnp/machine/reference/ReferenceMachine.java
src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java
src/main/java/org/openpnp/machine/reference/solutions/NozzleTipSolutions.java

This just fixes Wiki links fomr Issues & Solutions. 
See user report:
https://groups.google.com/g/openpnp/c/PFfm1vp2KGo/m/Vg44G0hVAwAJ
Wiki links now work again.

Fix / Issues & Solutions Wiki links with column

---

src/main/java/org/openpnp/machine/pandaplacer/AbstractPandaplacerVisionFeeder.java
src/main/java/org/openpnp/machine/pandaplacer/BambooFeederAutoVisionConfigurationWizard.java

Adding some improvements to the configuration UI for BambooFeederAutoVision.
Layout and alignments make things easier to work with.
Same functionality as before this change.
- Ran all the automated tests
- Tested the new feeder type on my personal hardware
- Yes
- No changes to `org.openpnp.spi` or `org.openpnp.model` packages
4. Be sure to run `mvn test` before submitting the Pull Request. If …

BambooFeederAutoVision UI Improvements

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java

Fixing a typo.
This is my first PR for OpenPnP, so just doing something small to get the feel of how things work.
It's a typo!
N/A.
N/A

ReferencePushPullFeeder: Fix a typo

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java

This PR just enhances the message generated on Nozzle tip calibration errors my naming the effected tip and nozzle.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **yes**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **yes**

Nozzle tip calibration error message enhanced

---

.github/workflows/build_and_deploy.yml
OpenPnP.install4j

Currently the MacOS builds are broken due to the notarization process not being implemented.
Install4J does support notarization and this change takes advantage of it.
This change requires additional input from @vonnieda  for 2 parameters, a secret app-password configured with the same apple-id that generated the signing certificate and the said Apple ID (also a secret if possible).
MacOS builds are broken as described here: https://github.com/openpnp/openpnp/pull/1628#issuecomment-2142761793
Nothing changes for the user
* Couldn't test without Jason's credentials. I tested using mine and it worked. …

Permanent fix for MacOS builds

---

src/main/java/org/openpnp/gui/MainFrame.java

Divider does not work correctly when changing window size. Eg. when switching to multiwindow and back. The divider is stuck at the right border. When changing window size then is pushed left but the limits are limited. Sometimes is stuck in middle because of calculated panel constraints around.
General GUI usability improvement.
Switch to multiwindow and back or play with the window size. Now the divider should be usable.
Left and right panel have forced getMinimumX in onresize now . The solution is not too sophisticated. The better solution should consist of constraining all panel hierarchy, e.g. minimum size of jog panel to see all controls. But this solution does not work as expected, still divider issues, so I used mentioned fix.

Mainframe divider had issue with limits when windows had changed.

---

src/main/java/org/openpnp/machine/reference/ReferenceNozzleTipCalibration.java

Fix the background calibration diagnostics in case there is not a single pixel inside the worst-case key-color box, i.e. all pixels are both too dark and not saturated enough.
Fixing this will of course not fix the underlying problem of the background being bad, but at least the user will know about it.
As a second fix, the background calibration will now also work with only three images (as does the nozzle tip calibration itself, where this is attached).
Background calibration will now write debug images if the logging level is at DEBUG or finer.
See user reports:
https://groups.google.com/g/openpnp/c/Zy0DUelv-ng/m/EPQ9BarCAAAJ
The usage does not change, only OpenPnP will now provide the right diagnostics:
You can also click on **Show Problems** to see where the saturation is not good …

Fix / Background Calibration Diagnostics

---

CHANGES.md

backfill CHANGES file #2

---

CHANGES.md

This updated CHANGES.md for the first two changes in version 2.3.
Lets aim to keep CHANGES.md updated as we merge features and fixes to test.
n/a
n/a
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- review only
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? -- no code changes
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. -- test pass

First CHANGES.md update for version 2.3

---

CHANGES.md

change log update for branches merged earlier today
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- no code changes. visual review only
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? -- no code changes
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. -- no code changes

change log update

---

src/main/java/org/openpnp/scripting/ScriptEngineKeyedPooledObjectFactory.java
src/main/java/org/openpnp/scripting/Scripting.java

Fix #1752 which records a spurious null pointer exception. This patch catches those null pointers and raises an error message that includes some clues about the possible root cause.
n/a
* manually tested jython and nashorn scripts
* tested non pooled, pooled on first run, and pooled on re-run
* injected some null pointers through code modification to check that the exception messages make sense
3. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? -- yes
4. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` …

better error handling for scripting engines. to investigate issue #1752

---

CHANGES.md

changelog update for todays merges
there are no code changes
1. How did you test the change? Be descriptive. Untested code will not be accepted. 
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? 

changelog for todays merges

---

src/main/java/org/openpnp/machine/reference/solutions/VisionSolutions.java

Fix that focus choices are shown by Issues and Solutions for downlooking cameras. This was introduced by PR #1700.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using physical machine**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **yes**

Fix focus option on downlooking camera

---

src/main/java/org/openpnp/machine/reference/ActuatorInterlockMonitor.java

This PR adds new interlock conditions to the axis interlock feature that mask interlock checking if the actuators state is unchanged.
For drag pins axis interlock is very good feature to verify that the drag pin is up if commanded to go up before motion continues. Unfortunately the current implementation only supports checking the drag pin state before every move even if the drag pins state is unchanged and hence the interlock can not fail. This causes unnecessary communication with the controller and hence slows the machine down.
The drop down list in the Interlock Conditions section has four new entries now containing "Just" which indicate, that the interlock condition is only checked if the actuators state has changed.
1. How did …

Add support to check axis interlock on actuator change only

---

src/main/java/org/openpnp/machine/reference/solutions/CameraSolutions.java

Fix Issues & Solutions show showing "Use an adaptive camera settling method." anymore. Introduced by PR #1737.
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using simulation**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **yes**

Fix vision solutions not shown

---

CHANGES.md

changelog updates for recent merges
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- no code changes
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. -- no code changes

more changes

---

CHANGES.md

1. How did you test the change? Be descriptive. Untested code will not be accepted. -- no code changes
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. -- tests pass

update changes file for recent merges

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java
src/main/java/org/openpnp/machine/reference/feeder/wizards/ReferencePushPullFeederConfigurationWizard.java

This is a minor refactoring in PushPullFeeder; moving some feeder business logic from the wizard into a new method in the feeder object
Code tidy up
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- tests pass. feature tested on a real machine.
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. -- tests pass.

move some feeder logic into a method

---

src/main/java/org/openpnp/machine/reference/feeder/ReferencePushPullFeeder.java

PR #1716 @tmandys  provided the FeedOptions mechanism to control a feeders feed process, and an implementation of that mechanism for several feeders. This PR adds support for PushPullFeeder.
Usage is the same as other feeders supported by #1716
1. How did you test the change? Be descriptive. Untested code will not be accepted. - production usage on real machine
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the …

implement FeedOptions for PushPullFeeder

---

src/test/java/LocalisationTest.java

Fixed the NormalisationTest (added in [PR#1772](https://github.com/openpnp/openpnp/pull/1772)) to convert different OS line endings to LFs before doing the comparison. Otherwise, the test would always fail if run on a machine that doesn't use LFs for line endings.
Also added output to show the lines where the first difference was detected in the event the test fails.
Bug fix
N/A
1. How did you test the change? Be descriptive. Untested code will not be accepted. **Ran the test on a Windows machine to verify that it now passes whereas previously it would fail. Also tested with a translations.properties file that was known to not be normalized and verified that the test failed. Then overwrote the contents of the translations.properties file with the contents from the …

Fixed NormalisationTest to convert different OS line endings to LFs before doing the comparison

---

CHANGES.md

changlog update
1. How did you test the change? Be descriptive. Untested code will not be accepted. -- no code changes
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? -- no code changes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. -- no code changes
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. -- not tested

Changelog update

---

src/main/java/org/openpnp/spi/PartAlignment.java
src/main/java/org/openpnp/util/TravellingSalesman.java

Fix a minor issue in logging the metric used by TravelingSalesman.

fix travel cost metric logging
